### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by lispking**
It is recommended to use the full English names instead of abbreviations, as it will be easier to understand.

### CODE REVIEW

**Review by ronny-mysten — APPROVED** [review]
Thanks @lispking ! Some recent CI changes are failing. I think an approval will fix but unsure. If not, I'll recreate. Just fyi; nothing more for you to do.

**Comment by ronny-mysten** [comment]
Moved to https://github.com/MystenLabs/sui/pull/20586

**Comment by lispking** [comment]
oh, become a contributor is so hard @ronny-mysten

**Comment by ronny-mysten** [comment]
> oh, become a contributor is so hard @ronny-mysten

Apologies! Yeah, there was a CI change that ended up being a bigger issue than I had hoped. 

After finally getting this in, there is a reason that the original `tyname` was used. The autogen process turns the variable name into a link when it has the same name as the package (see image). Not the worst thing in the world, but if you wanted, you could submit another PR and change the name again to something like `typename` instead.

If you do make this or similar changes in the future, you can't update the associated markdown file directly. The CI will fail. Instead, make your changes then run `UPDATE=1 cargo nextest run build_system_packages` from the `crates/sui-framework` directory. This will update the md file for you and will pass CI...at least the part of the CI that checks those autogen pages.

image

Let me know if you have any questions and thanks again for contributing (even if I had to deny you credit this time)!

**Comment by lispking** [comment]
This is a very good suggestion. At the same time, put this instruction in the document to prevent similar problems from occurring among future contributors. This will also reduce the workload for the official side.  @ronny-mysten

**Pull request closed without merging**
