### PR TITLE
Merge bytecode snapshots

### PR DESCRIPTION
**Pull request by lxfind**
## Description 

This PR simplifies the framework snapshot flow:
1. Merges the snapsnot between mainnet and testnet. This will require us to always ship unique protocol version bytecode globally.
2. Move the GIT_REVISION related code to a shared file in sui-types so that all files can use it directly.
3. Remove the need to pass any arguments to sui-framework-snapshot

## Test Plan 
CI

How did you test the new or updated feature?

---
If your changes are not user-facing and not a breaking change, you can skip the following section. Otherwise, please indicate what changed, and then add to the Release Notes section as highlighted during the release process.

### Type of Change (Check all that apply)

- [ ] user-visible impact
- [ ] breaking change for a client SDKs
- [ ] breaking change for FNs (FN binary must upgrade)
- [ ] breaking change for validators or node operators (must upgrade binaries)
- [ ] breaking change for on-chain data layout
- [ ] necessitate either a data wipe or data migration

### CODE REVIEW

**Comment by dariorussi** [comment]
can we please explains what we have to do when we upgrade a protocol version?
I am still very unclear about the steps. 
I add a new version, I change the snapshots in protocol version, at that point all is good, except I get an error here.
What are the steps?

**Comment by lxfind** [comment]
Snapshots shouldn't be added when we introduce a new version.
We need to introduce snapshots whenever we release a version to a production network.
I am going to work with PE to make this a require step whenever we release something, so hopefully developers don't need to worry about this in the future. In the short term, we just need to make sure to always git checkout the revision that we released to prod, and run the command in README.txt, cherry pick the generated files back to main branch

**Comment by dariorussi** [comment]
> Snapshots shouldn't be added when we introduce a new version.
> We need to introduce snapshots whenever we release a version to a production network.
> I am going to work with PE to make this a require step whenever we release something, so hopefully developers don't need to worry about this in the future. In the short term, we just need to make sure to always git checkout the revision that we released to prod, and run the command in README.txt, cherry pick the generated files back to main branch

so we are saying that those tests should never fail for a PR? and only be enabled when we release to prod?

**Comment by lxfind** [comment]
The tests attempt to upgrade from the latest released version (which is the snapshoted version) to the currenet latest version in code. So this should never fail

**Review by dariorussi — APPROVED** [review]
I'll try to sync my PR after this and see what happens.
Thanks!!!

**Pull request merged**
