### PR TITLE
[narwhal/fix] recover certificates from last_round - 1

### PR DESCRIPTION
**Pull request by akichidis**
Resolves: https://github.com/MystenLabs/sui/issues/5617

### CODE REVIEW

**Review by huitseeker — COMMENTED** [review]
Would it be possible to add a test besides the 3 already there (`recover_*`) in `core_tests` that exercise the scenario you envision in this case?

**Review by mwtian — APPROVED** [review]
1. Do we need a test?
2. I thought we persist the header before proposing it, or is that only a plan? If we rebuild the header instead, the parents or the batches could be different from a previously broadcasted header at the same round. Will this run into equivocation protection / deduplication in other nodes? To me, I feel like the simplest recover strategy might be to recover and propose the same header if one exists before crash, and try fetching certificates from all other nodes. Anyway we can keep iterating on this because there are definitely more work.

**Comment by laura-makdah** [comment]
This functionality was taken care of by  https://github.com/MystenLabs/sui/pull/5633 and so this PR does not need to be merged.

**Comment by akichidis** [comment]
Closing this PR as we went with https://github.com/MystenLabs/sui/pull/5633

**Pull request closed without merging**
