### PR TITLE
[docs] add custom indexer example to doc page

### PR DESCRIPTION
**Pull request by zihehuang**
## Description 

Linking custom indexer example to doc page

## Test plan 

manually

---

## Release notes

Check each box that your changes affect. If none of the boxes relate to your changes, release notes aren't required.

For each box you select, include information after the relevant heading that describes the impact of your changes that a user might notice and any actions they must take to implement updates. 

- [ ] Protocol: 
- [ ] Nodes (Validators and Full nodes): 
- [ ] Indexer: 
- [ ] JSON-RPC: 
- [ ] GraphQL: 
- [ ] CLI: 
- [ ] Rust SDK:
- [ ] REST API:

### CODE REVIEW

**Review by ronny-mysten — CHANGES_REQUESTED** [review]
Can we move that example source into `sui/examples/rust/custom-indexer`?

**Comment by zihehuang** [comment]
I think this gives a more realistic `Cargo.toml` file that project teams can reference. Moving it to the main repo would introduce that Rust workspace related configs that make running the example more difficult

**Comment by ronny-mysten** [comment]
Doesn't this work?
```
[package]
name = "custom-indexer"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.81"
tokio = { version = "1.38.0", features = ["full"]}
sui_types = { git = "https://github.com/mystenlabs/sui", package = "sui-types"}
sui_data_ingestion_core = { git = "https://github.com/mystenlabs/sui", package = "sui-data-ingestion-core"}
anyhow = "1.0.86"

[workspace]
# Add an optional note to explain 

[[bin]]
name = "custom-indexer"
path = "main.rs"
```
If it's in its own repo, it'll be forgotten about (esp. if you're not at SF anymore because you started your own company making billions). And if it's in the sui repo, we can test it as part of the ci to make sure it's updated when needed. And we could also import the code into the page if desired instead of forcing the user navigate to the repo.

**Comment by zihehuang** [comment]
Yup that worked. I guess I was missing the workspace config

**Comment by ronny-mysten** [comment]
Sweet. With it in there we can add the code to the doc (check the preview from the vercel comment). There's still the link to take the user to the repo, but they can also use the copy code button to never leave the page. I'll wait to get your thoughts before merging.

**Review by ronny-mysten — APPROVED** [review]

**Comment by zihehuang** [comment]
Not sure how you did the linking magic but it looks good. We can keep both so people have options

**Pull request merged**
