### PR TITLE
[move] Bump Move version

### PR DESCRIPTION
**Pull request by amnn**
Includes fix to module-handle order stability issue in move-language/move#904

## Test Plan

```
$ cargo nextest run
```

### CODE REVIEW

**Review by tnowacki — APPROVED** [review]
Why a draft?

**Comment by amnn** [comment]
@tnowacki, there's some strangeness with module orders in the build output of `sui-framework`, and I can't figure out if it's because of a stale dependency on the old `move-compiler` during `build` or something else -- so I was checking by submitting to CI first.

I can't seem to shake it locally though, even after fixing workspace-hack and deleting `target`.

**Comment by amnn** [comment]
Yep, sadly persistent -- needs further investigation -- the order of modules is very strange, it interleaves `sui::...` and `std::...` modules, which does not really make sense.

**Comment by amnn** [comment]
For example:

```
// Move bytecode v6
module 2.address {
use 0000000000000000000000000000000000000001::ascii;
use 0000000000000000000000000000000000000001::string;
use 0000000000000000000000000000000000000002::hex;
use 0000000000000000000000000000000000000001::bcs;
```

(From my local network)

**Comment by tnowacki** [comment]
> For example:
> 
> ```
> // Move bytecode v6
> module 2.address {
> use 0000000000000000000000000000000000000001::ascii;
> use 0000000000000000000000000000000000000001::string;
> use 0000000000000000000000000000000000000002::hex;
> use 0000000000000000000000000000000000000001::bcs;
> ```
> 
> (From my local network)

da eff

**Pull request merged**
