### PR TITLE
[Explorer] Reduces the size of the copy icon that is used with IDs

### PR DESCRIPTION
**Pull request by Andrew47**
* Reflecting the scarcity of copy icons in the new Figma designs, the default for the Longtext component is now no copy button.
* Two copy buttons are taken from the Figma designs: 16 x 16 and  24 x 24 pixels.
* The copy icons used for the IDs in headers are swapped for the 24 x 24 version.
* The copy icons used for IDs elsewhere are swapped for the 16 x 16 version. This shrinks most copy icons.
* When examining the website on a smart phone, the 16 x 16 icons disappear.

Here's a video showing how these changes play out across the website:

https://user-images.githubusercontent.com/11377188/189197029-0fe482c9-f650-4586-8dec-f48512fc05a4.mp4

The above description has been updated as of 8 September 2022

### CODE REVIEW

**Comment by Jibz1** [comment]
@Andrew47 the `✔️success` seems off

**Comment by mystie711** [comment]
Figma reference,
https://www.figma.com/file/kSD0qXCIDZA4KQVNepA5hR/02-Explorer?node-id=158%3A35722

The proportions seem off within the badge. 
These kind of misalignments usually happen because of the icon shape is chosen when exporting assets vs the icon container. One good way to always ensure you are exporting the correct asset is to look for a perfect square proportion on export.

**Review by mystie711 — DISMISSED** [review]
@Andrew47 just a few more pixel pushes and this should be ready to go.
image

**Comment by Andrew47** [comment]
@mystie711 --> Does this work?

image

**Comment by mystie711** [comment]
@Andrew47 the text alignment looks better. But now the check icon looks off center vertically by a pixel. May need to handle their placements individually?

**Pull request merged**
