### PR TITLE
Update sui-move-library.md

### PR DESCRIPTION
**Pull request by georgescharlesbrain**
suggest better wording
add some extra info

### CODE REVIEW

**Review by randall-Mysten — APPROVED** [review]

**Comment by georgescharlesbrain** [comment]
Hello @randall-Mysten
To be sure about the process here. Does this one need an additional review by Ronny?
Does each PR need to be reviewed by 2 persons?

**Comment by randall-Mysten** [comment]
nope, just one approval. Ronny is another tech writer here, so it assigns both of us to any PR that changes a .md file.

**Review by randall-Mysten — APPROVED** [review]

**Comment by georgescharlesbrain** [comment]
@randall-Mysten 
Also, missing the merge request from your side?
Then I wonder what auto-merge actually means :p.

**Review by randall-Mysten — APPROVED** [review]

**Comment by georgescharlesbrain** [comment]
Still didn't merge it seems :)

**Comment by randall-Mysten** [comment]
> Still didn't merge it seems :)

Checking, looks like it is unhappy about the tests not completing but they are also not running. Or it cleared my Approval for some reason.

**Review by randall-Mysten — APPROVED** [review]

**Pull request merged**
