### PR TITLE
Enforce narwhal header timestamp monotonic with respect to it's parents

### PR DESCRIPTION
**Pull request by andll**

### CODE REVIEW

**Review by gdanezis — APPROVED** [review]
Lets see if this invariant holds, since it should.

**Comment by akichidis** [comment]
@andll this is a good check, but I don't believe we do enforce the monotonicity during the header creation https://github.com/MystenLabs/sui/blob/main/narwhal/primary/src/proposer.rs#L205-L219

so my expectation would be that we see this erroring

**Review by mwtian — COMMENTED** [review]
Great idea to enforce this, but I don't think header.timestamp > all parents are ensured at Proposer. Can it happen that an advanced header gets signed by a quorum, becomes a parent in a header where the node's local clock is slower? Maybe proposer should wait to propose until its time is past all parent timestamps, or we can create a Narwhal clock, or am I missing something?

Also, can we expand the error message a bit, e.g. `Header {0} has timestamp {1}, smaller than parent {2} with timestamp {3}"? That will help troubleshoot the issue. We did see one validator with inaccurate local clock in wave 3.0.

**Review by mwtian — APPROVED** [review]

**Review by akichidis — APPROVED** [review]

**Comment by andll** [comment]
Thanks for adding proposer enforcement in https://github.com/MystenLabs/sui/pull/10148 @mwtian !

**Pull request merged**
