### PR TITLE
[sui-json-rpc] Use more efficient parser

### PR DESCRIPTION
**Pull request by tnowacki**
- Use the newer parser for Moves type tags
- This should improve performance as the newer parser doesn't allocate as much (it doesn't copy out each intermediate string)

### CODE REVIEW

**Comment by sblackshear** [comment]
Could you also fix https://github.com/MystenLabs/sui/blob/main/crates/sui/src/client_commands.rs#L15?

**Comment by tnowacki** [comment]
> Could you also fix https://github.com/MystenLabs/sui/blob/main/crates/sui/src/client_commands.rs#L15?

Done

**Comment by velvia** [comment]
LGTM, but I guess this is just switching the libraries or functions used.  I'm curious about the details of those libraries, but will trust you here.  :)

**Comment by tnowacki** [comment]
> LGTM, but I guess this is just switching the libraries or functions used. I'm curious about the details of those libraries, but will trust you here. :)

A quick summary: The original parser for type tags copied each substring while tokenizing. The new parser just creates sub-string references. You can think about it as generating a `Iterator<(Tok, String)>` vs `Iterator<(Tok, &str)>`

**Review by sblackshear — APPROVED** [review]

**Pull request merged**
