### PR TITLE
fix: update Sui environment setup

### PR DESCRIPTION
**Pull request by emmanuel-ferdman**
## Description 

PR #17253 moved the location of the Sui environment setup file. This PR adjusts sources to changes.

## Test plan 

Checked the doc.

---

## Release notes

Check each box that your changes affect. If none of the boxes relate to your changes, release notes aren't required.

For each box you select, include information after the relevant heading that describes the impact of your changes that a user might notice and any actions they must take to implement updates. 

- [ ] Protocol: 
- [ ] Nodes (Validators and Full nodes): 
- [ ] Indexer: 
- [ ] JSON-RPC: 
- [ ] GraphQL: 
- [ ] CLI: 
- [ ] Rust SDK:

### CODE REVIEW

**Review by ronny-mysten — APPROVED** [review]

**Comment by emmanuel-ferdman** [comment]
@ronny-mysten can you please merge the changes into main?

**Comment by emmanuel-ferdman** [comment]
Hi @ronny-mysten, can you please check why it's stuck on CI?

**Comment by emmanuel-ferdman** [comment]
Hi @ronny-mysten, can you please check why it's stuck on CI?

**Comment by emmanuel-ferdman** [comment]
Hi @ronny-mysten @aschran @Jordan-Mysten @williampsmith @amnn, can you please review this small PR when you get the chance?

**Comment by emmanuel-ferdman** [comment]
@amnn should be good now - the branch is updated to latest changes in `main`. Thank you for the review.

**Pull request merged**
