### PR TITLE
Fix typo for std::debug in docs

### PR DESCRIPTION
**Pull request by Deagler**
- Docs are incorrect on debugging page. `Std::Debug` --> `std::debug`

### CODE REVIEW

**Comment by randall-Mysten** [comment]
@tharbert and @huitseeker Could you please confirm these changes?

**Comment by huitseeker** [comment]
@randall-Mysten pinged better reviewers :)

**Comment by randall-Mysten** [comment]
@huitseeker Thank you!

**Comment by huitseeker** [comment]
This PR is issued against the wrong branch, u fortynat es muy we need it reissued against main for a merge @Deagler

**Pull request closed without merging**
