### PR TITLE
Switch to system memory allocator by default

### PR DESCRIPTION
**Pull request by mwtian**
This switches memory allocator to the system provided allocator for running Sui nodes. `jemalloc` can be loaded dynamically instead, so the C++ logic will be able to use jemalloc as well. This has the benefits that C++ allocations can be profiled, and there might be less fragmentation (I believe in Facebook rocksdb is used with jemalloc).

Sui node docker image is configured with jemalloc profiling enabled by default.

Image build is tested at https://github.com/MystenLabs/sui-operations/actions/runs/3339609372

If this works well, I can add setting up jemalloc to the instructions for running Sui validators / fullnodes.

### CODE REVIEW

**Review by velvia — COMMENTED** [review]
I'm fine with this change, except that this creates a burden for anyone who runs Sui locally to need to append LD_PRELOAD or else it will break.  That doesn't seem that friendly.

What I recommend is that you wait for my PR, because in my PR I'm going to remove the automatic jemalloc-based profiling and switch it to my custom profiler/allocator.    What I'm saying is, I can incorporate your PR in my PR, but it will mean that people can run Sui locally and it won't break (ie, LD_PRELOAD with jemalloc becomes optional, which is what we want)

**Comment by mwtian** [comment]
I can definitely wait. But not using LD_PRELOAD is fine since it switches to the system memory allocator. The periodic jemalloc dump becomes a no-op, and I can delete that if you prefers.

**Comment by velvia** [comment]
Oh I see.  If you think it is a nop then go ahead

**Review by velvia — APPROVED** [review]

**Comment by mwtian** [comment]
Great, thanks Evan!

**Pull request merged**
