### PR TITLE
[CI] use seed specific to commit for Mysticeti simtest

### PR DESCRIPTION
**Pull request by mwtian**
## Description 

When a simtest is flaky, unrelated PRs can encounter failures which cannot be easily reproduced locally or in simtest nightly. It doesn't seem productive to block the PR submission in this case.

## Test Plan 

CI

---
If your changes are not user-facing and do not break anything, you can skip the following section. Otherwise, please briefly describe what has changed under the Release Notes section.

### Type of Change (Check all that apply)

- [ ] protocol change
- [ ] user-visible impact
- [ ] breaking change for a client SDKs
- [ ] breaking change for FNs (FN binary must upgrade)
- [ ] breaking change for validators or node operators (must upgrade binaries)
- [ ] breaking change for on-chain data layout
- [ ] necessitate either a data wipe or data migration

### CODE REVIEW

**Comment by mystenmark** [comment]
This should be deterministic. You could use the current commit hash to derive a seed.

**Comment by mystenmark** [comment]
I'm also a bit ambivalent about this. We have found and fixed many many bugs over that past year because they were blocking PRs. I agree its odd to put the burden on the author of an unrelated PR, but we are only so-so about keeping up with the nightly failure reports, which are supposed to find these bugs

**Comment by mwtian** [comment]
I think blocking unrelated PRs are not very fair to people working on projects unrelated to core, because of prioritization issues in core. As a middle ground, how about I just make the change to the Mysticeti workflow?

**Comment by mwtian** [comment]
It seems @mystenmark likes the comment above. Adding @arun-koshy for Mysticeti CI change.

**Review by arun-koshy — APPROVED** [review]

**Pull request merged**
