### PR TITLE
[sui-test-validator] update sui-test-validator options and dockerfile

### PR DESCRIPTION
**Pull request by vladilen11**
## Description 

Give the address configuration to the developer allows for more flexibility in starting `sui-test-validator`.

## Test Plan 

How did you test the new or updated feature?

---
If your changes are not user-facing and not a breaking change, you can skip the following section. Otherwise, please indicate what changed, and then add to the Release Notes section as highlighted during the release process.

### Type of Change (Check all that apply)

- [ ] protocol change
- [ ] user-visible impact
- [ ] breaking change for a client SDKs
- [ ] breaking change for FNs (FN binary must upgrade)
- [ ] breaking change for validators or node operators (must upgrade binaries)
- [ ] breaking change for on-chain data layout
- [ ] necessitate either a data wipe or data migration

#### sui-test-validator change

**sui-test-validator** cmd:

```bash
$ ./target/release/sui-test-validator --help
Start a Sui validator and fullnode for easy testing

Usage: sui-test-validator [OPTIONS]

Options:
  -c, --config-dir <CONFIG_DIR>                Config directory that will be used to store network config, node db, keystore sui genesis -f --with-faucet generates a genesis config that can be
                                               used to start this process. Example: sui-test-validator --config-dir ~/.sui/sui_config We can use any config dir that is generated by the sui genesis
      --fullnode-rpc-addr <FULLNODE_RPC_ADDR>  Address to start the Fullnode RPC server on [default: 127.0.0.1:9000]
      --faucet-addr <FAUCET_ADDR>              Address to start the Sui faucet on [default: 127.0.0.1:9123]
      --indexer-rpc-addr <INDEXER_RPC_ADDR>    Address to start the Indexer RPC server on [default: 127.0.0.1:9124]
      --pg-port <PG_PORT>                      Port for the Indexer Postgres DB 5432 is the default port for postgres on Mac [default: 5432]
      --pg-host <PG_HOST>                      Hostname for the Indexer Postgres DB [default: localhost]
      --epoch-duration-ms <EPOCH_DURATION_MS>  The duration for epochs (defaults to one minute) [default: 60000]
      --with-indexer                           if we should run indexer
      --use-indexer-experimental-methods       TODO(gegao): remove this after indexer migration is complete
  -h, --help                                   Print help
  -V, --version                                Print version
```

1. start at `127.0.0.1`
```bash
./target/release/sui-test-validator
```

2. start at `0.0.0.0`
```bash
./target/release/sui-test-validator --fullnode-rpc-addr "0.0.0.0:9000" --faucet-addr "0.0.0.0:9123"
```

#### Add sui-test-validator Dockerfile

Hopefully the mystenlabs team will maintain a docker image of sui-test-validator, which is really important for developers.

```bash
docker run -id -p 9000:9000 -p 9123:9123 vladilenaksana/sui-test-validator:0.0.2 sui-test-validator --fullnode-rpc-addr "0.0.0.0:9000" --faucet-addr "0.0.0.0:9123"
```

### CODE REVIEW

**Comment by vladilen11** [comment]
Is anyone could help this pr? I think this dockerfile is very useful for developers. @patrickkuo

**Comment by stefan-mysten** [comment]
Hi @vladilen11 

Just to understand, what do you want to have in a Dockerfile, just a local network running?

Important to note, we are just about to deprecate `sui-test-validator` binary. Its functionality was integrated into `sui start`. 
In a nutshell, you can replace the most basic usage of `sui-test-validator` with 
- `sui start --with-faucet --force-regenesis`.

Regarding the host and ports, I see the issue that you need to have the service listening on 0.0.0.0 for Docker to work properly.

**Comment by vladilen11** [comment]
@stefan-mysten Yes, I want to be able to boot a localnet directly through docker, because sui-test-validator had a lot of people having problems(https://obelisk.build/engine/docs/quick-start/faq) with postgres before, so we want to start it through docker.

Our primary goal in doing this is to allow move contract developers to focus their efforts on contract development rather than tedious environment configuration.

You're right, the modification I gave to `sui-test-validator` was so that I could expose the faucet api and the rpc.

---

But since `sui-test-validator` will be deprecated, do you think there's still a need for my pr to be merged in?

Also I observed that I still can't specify the address of the faucet or fullnode in the sui start command, I guess I can recreate a pr to refine the details here.
```
      --with-faucet[=<FAUCET_PORT>]
          Start a faucet with default host and port: 127.0.0.1:9123, or on the port provided. When providing a specific value, please use the = sign between the flag and value:
          `--with-faucet=6123`

      --fullnode-rpc-port <FULLNODE_RPC_PORT>
          Port to start the Fullnode RPC server on. Default port is 9000

          [default: 9000]
```

**Comment by vladilen11** [comment]
Anyway, I think it would be best if this pr could be merged, as it means that the idea of the modification is okay and my contribution makes sense.  😄 I don't mind that `sui-test-validator` will be abandoned, and I'll continue to refine the details on `sui start` if this idea/pr is approved. cc @stefan-mysten

**Comment by stefan-mysten** [comment]
@vladilen11 I have not forgot about this. Just put up a PR #18607 that should enable this for `sui start`.

**Comment by stefan-mysten** [comment]
@vladilen11 everything now starts on `0.0.0.0`, so it should unblock you when using Docker. Let me know if you spot any issues.

**Pull request closed without merging**
