### PR TITLE
Fix broken release

### PR DESCRIPTION
**Pull request by oxade**
Release mode broken due to dbg assert

```
mbp>    cargo build --release
   Compiling sui-types v0.1.0 (/Users/ade/Documents/work/proc/fastx/sui_types)
   Compiling sui-verifier v0.1.0 (/Users/ade/Documents/work/proc/fastx/sui_programmability/verifier)
   Compiling sui-network v0.1.0 (/Users/ade/Documents/work/proc/fastx/network_utils)
   Compiling sui-framework v0.1.0 (/Users/ade/Documents/work/proc/fastx/sui_programmability/framework)
   Compiling test_utils v0.1.0 (/Users/ade/Documents/work/proc/fastx/test_utils)
   Compiling sui-adapter v0.1.0 (/Users/ade/Documents/work/proc/fastx/sui_programmability/adapter)
error[E0425]: cannot find value `num_immutable_objects` in this scope
   --> sui_programmability/adapter/src/adapter.rs:784:62
    |
784 |         by_value_objects.len() + mutable_ref_objects.len() + num_immutable_objects == num_objects
    |                                                              ^^^^^^^^^^^^^^^^^^^^^ not found in this scope
```

### CODE REVIEW

**Review by mystenmark — APPROVED** [review]

**Comment by oxade** [comment]
Weird that unrelated tests are failing too

**Review by huitseeker — DISMISSED** [review]
Thanks for the fix! See https://github.com/MystenLabs/sui/pull/1333 for the source.

**Comment by huitseeker** [comment]
@oxade The errors are indeed concerning: what seemed to have happened is PR #632 reintroduced log as a dependency of core, whereas #706 and in fact https://github.com/MystenLabs/sui/pull/298 before it have switched the entire code base to use tracing. Except all of these PRs are really old, and any [E0659](https://doc.rust-lang.org/error-index.html#E0659) we see here should have come up a while ago. 🤔

**Review by huitseeker — APPROVED** [review]

**Comment by oxade** [comment]
@huitseeker thanks for handling the errors

**Pull request merged**
