### PR TITLE
[DeepBook] Fix place market order annotation

### PR DESCRIPTION
**Pull request by ccbond**

### CODE REVIEW

**Comment by wiggins-dev** [comment]
This have been corrected in https://github.com/MystenLabs/sui/pull/11562

**Comment by ccbond** [comment]
Above annotation may don't case may not have a serious impact. But the function named `swap_exact_base_for_quote`, what may cause me to understand it means to exchange the base currency for the quote currency based on a precise amount and the current market price. In other words, its purpose is to execute a buy order in a trading pair to obtain a specified quantity of the base currency. But, it will swap all base assrt what passed, doesn't swap `quantity` base coin.

**Comment by ccbond** [comment]
so maybe rename the `quantity` to `quantity_limit`, this `quantity` in this way just used to do assert.
```
    // for smart routing
    public fun swap_exact_base_for_quote<BaseAsset, QuoteAsset>(
        pool: &mut Pool<BaseAsset, QuoteAsset>,
        quantity_limit: u64,
        base_coin: Coin<BaseAsset>,
        quote_coin: Coin<QuoteAsset>,
        clock: &Clock,
        ctx: &mut TxContext,
    ): (Coin<BaseAsset>, Coin<QuoteAsset>, u64) {
        let original_val = coin::value(&quote_coin);
        let (ret_base_coin, ret_quote_coin) = place_market_order(
            pool,
            quantity_limit,
            false,
            base_coin,
            quote_coin,
            clock,
            ctx
        );
        let ret_val = coin::value(&ret_quote_coin);
        (ret_base_coin, ret_quote_coin, ret_val - original_val)
    }
```

**Comment by ccbond** [comment]
@wiggins-dev

**Comment by OPTIMUS-PX** [comment]
MystenLabs/sui] [DeepBook] Fix place market order annotation (PR #11626)

**Pull request closed without merging**
