### PR TITLE
[GraphQL] Extract header through axum's extractor rather than manually

### PR DESCRIPTION
**Pull request by stefan-mysten**
## Description 

This PR uses axum's TypedHeader to extract the `ShowUsage` header from the request.

## Test Plan 

Existing tests.

---
If your changes are not user-facing and do not break anything, you can skip the following section. Otherwise, please briefly describe what has changed under the Release Notes section.

### Type of Change (Check all that apply)

- [ ] protocol change
- [ ] user-visible impact
- [ ] breaking change for a client SDKs
- [ ] breaking change for FNs (FN binary must upgrade)
- [ ] breaking change for validators or node operators (must upgrade binaries)
- [ ] breaking change for on-chain data layout
- [ ] necessitate either a data wipe or data migration

### CODE REVIEW

**Review by emmazzz — APPROVED** [review]

**Review by amnn — APPROVED** [review]
Thanks @stefan-mysten! Glad this is working now, did you figure out what was wrong with the TypedHeader approach before?

**Comment by stefan-mysten** [comment]
> Thanks @stefan-mysten! Glad this is working now, did you figure out what was wrong with the TypedHeader approach before?

Not sure I follow your question (wrong in what sense?), but here are my thoughts. I don't think there was anything wrong, we just did not use the `TypedHeader` extract pattern and instead got all headers and checked if `ShowUsage` is present. As you see, I have not changed any crate's version, everything was there.

**Comment by amnn** [comment]
The context is that originally we did use `TypedHeader`, and at some point, Ade reverted back to getting all the headers because it was seemingly not working, correlated with an upgrade to either `async_graphql` or `axum`. (So it may be worth confirming that the header is working as expected now as well, although I think we do have a test for this among the transactional tests).

**Comment by stefan-mysten** [comment]
Manual test worked. CI is failing because somehow in the `test_simple_client_simulator_cluster` test, the show usage header is added automatically?!?!? 

I'll look into it, check for tests/add more if needed, to make sure everything works as expected.

**Comment by amnn** [comment]
> the show usage header is added automatically?!?!?

IIRC this was the problem -- the header was being detected even when it wasn't actually there!

**Comment by stefan-mysten** [comment]
> > the show usage header is added automatically?!?!?
> 
> IIRC this was the problem -- the header was being detected even when it wasn't actually there!

Excellent, thanks for remembering this. I will look into it!

**Comment by stefan-mysten** [comment]
> The context is that originally we did use `TypedHeader`, and at some point, Ade reverted back to getting all the headers because it was seemingly not working, correlated with an upgrade to either `async_graphql` or `axum`. (So it may be worth confirming that the header is working as expected now as well, although I think we do have a test for this among the transactional tests).

I looked more into this. In [one GitHub issue](https://github.com/tokio-rs/axum/discussions/1437#discussioncomment-3774565), I found that `TypedHeader` is not the right choice here. From what I understand, it should only be used when working with standardized headers (see https://docs.rs/headers/latest/headers/index.html), and not a custom one.

We have two options: keep it as it was or implement `FromRequestParts` trait.

**Comment by stefan-mysten** [comment]
> > The context is that originally we did use `TypedHeader`, and at some point, Ade reverted back to getting all the headers because it was seemingly not working, correlated with an upgrade to either `async_graphql` or `axum`. (So it may be worth confirming that the header is working as expected now as well, although I think we do have a test for this among the transactional tests).
> 
> I looked more into this. In [one GitHub issue](https://github.com/tokio-rs/axum/discussions/1437#discussioncomment-3774565), I found that `TypedHeader` is not the right choice here. From what I understand, it should only be used when working with standardized headers (see https://docs.rs/headers/latest/headers/index.html), and not a custom one.
> 
> We have two options: keep it as it was or implement `FromRequestParts` trait.

Looked more into this. The way headers are extracted is that they are extracted into the `HeaderValue` type. As we're passing a header name only, without a value, it does not get extracted in a `HeaderValue` type, and it is dropped. The same would happen when using `FromRequestParts`, so going forward (also thinking that we'll have to bump axum version at some point), we have two options: 1) keep as is (+1 from me), or 2) make `x-sui-rpc-show-usage` to take a bool value.

**Pull request closed without merging**
