### PR TITLE
Fix the event tab hight set to set 100vh on transaction page 

### PR DESCRIPTION
**Pull request by Jibz1**
Before
Screen Shot 2022-08-25 at 4 04 06 PM

After
Screen Shot 2022-08-25 at 4 03 51 PM

### CODE REVIEW

**Review by mystie711 — APPROVED** [review]

**Comment by Jordan-Mysten** [comment]
On transactions with lots of events, this causes there to be two individually scrollable containers (the main body, and the events body). I'm not sure if this is really expected or intended on the design side cc @mystie711 

Screen Shot 2022-08-26 at 10 05 20 AM

**Comment by mystie711** [comment]
Thanks for the tag @Jordan-Mysten. Since the scroll bars only show up on hover+interaction this won't look too bad.

For this particular use case, I believe it is a better ux to allow easy "view + scrollability" of events-list panel vs forcing a collapse/expand interaction.

**Comment by Jordan-Mysten** [comment]
> Since the scroll bars only show up on hover+interaction this won't look too bad.

This is only true on mobile & macos, on windows the scrollbar is persistent. 

I agree about "view + scrollability", I just more mean that the document should scroll, not the nested section.

**Comment by Jibz1** [comment]
@Jordan-Mysten we may also want to reduce the height of `main` element, because currently every page on the explorer regardless of the content size will have a scrollbar. By reducing the height of `main` and the height of the `Event` div we should only have a single scrollbar that matches the design.

**Review by Jordan-Mysten — APPROVED** [review]
Approving for now, since this really isn't a regression. We should revisit this in the future though.

**Pull request merged**
