### PR TITLE
v1 execution layer

### PR DESCRIPTION
**Pull request by dariorussi**
## Description 

Make a v1 execution layer. 
From now on the production release will always be `v_next_` while `latest` is the development branch. We will come up with a cadence for deploying `latest`, which is likely to be variable and be few weeks apart.
This should change nothing for everybody developing on the execution layer.
Hot fixes should go to `v_next_` and `latest` otherwise development should go to `_latest_` and they will be deployed at some point. 
`suivm` is going to disappear soon and become `latest`.
`latest` will be the release to go to `devnet` while `v_next_` will go to `testnet` and `mainnet`.

We will write a post about what is going on to keep everybody up to date.

## Test Plan 

Existing tests

---
If your changes are not user-facing and not a breaking change, you can skip the following section. Otherwise, please indicate what changed, and then add to the Release Notes section as highlighted during the release process.

### Type of Change (Check all that apply)

- [ ] protocol change
- [ ] user-visible impact
- [ ] breaking change for a client SDKs
- [ ] breaking change for FNs (FN binary must upgrade)
- [ ] breaking change for validators or node operators (must upgrade binaries)
- [ ] breaking change for on-chain data layout
- [ ] necessitate either a data wipe or data migration

### CODE REVIEW

**Review by amnn — APPROVED** [review]
LGTM!  Double confirming that as per the PR description, once this change lands, no more changes to the `latest` execution layer will make it to a production network.  It's also worth landing this quickly so that we don't effectively rollback a change that did land.

**Comment by dariorussi** [comment]
> LGTM! Double confirming that as per the PR description, once this change lands, no more changes to the latest execution layer will make it to a production network. It's also worth landing this quickly so that we don't effectively rollback a change that did land.

correct, though the non determinism error is back. I suppose that `static` initialized that @lxfind was referring to is back in action :)
I'll find where that is and change it

**Comment by dariorussi** [comment]
@amnn could you check the latest commit and make suggestions if you see anything wrong.
That fixes the sim test but it creates some other problems (I think, we'll see the run).
Basically there were a bunch of hardcoded `latest` dependencies that I changes to `v1`

**Comment by amnn** [comment]
😢 sounds reasonable.  Let's meet when I'm back from the builder house to strategise on how to get this over the line?

**Comment by dariorussi** [comment]
not needed an longer

**Pull request closed without merging**
