### PR TITLE
[GraphQL/Cursor] EndOfEpochTransaction

### PR DESCRIPTION
**Pull request by amnn**
## Description

Cursor framework and rename of `transactions` and `systemPackages` fields related to the `EndOfEpochTransaction`.

## Test Plan

```
sui-graphql-e2e-tests$ cargo nextest run \
  -j 1 --features pg_integration         \
  -- system.move
```

## Stack
- #15467 
- #15470 
- #15471 
- #15472 
- #15473
- #15474 
- #15475

### CODE REVIEW

**Comment by wlmyng** [comment]
@amnn i think this might need a rebase?

**Review by wlmyng — APPROVED** [review]
nice

**Comment by amnn** [comment]
Will prepare the stack for landing based off this PR!

**Comment by wlmyng** [comment]
> Will prepare the stack for landing based off this PR!

and so it begins! exciting

**Pull request merged**
