### PR TITLE
🐛 ZkSend 'fetch' on 'Window': Illegal invocation bug

### PR DESCRIPTION
**Pull request by git-marcopitra**
## Description 

While I was testing the ZkSend SDK, I faced the error `TypeError: Failed to execute 'fetch' on 'Window': Illegal invocation`, live on [ZkSend CSR project preview](https://zksend-csr.vercel.app/),

The browser inspector says that the error is on `SuiGraphQLClient`, so I tried to bind fetch `window.fetch.bind(window)` from the client side, and it is working properly, but if it cannot be fixed on `SuiGraphQLClient` itself, we can add it as an optional parameter for the function to bind it directly on the client if a user is facing the same error

## Test Plan 

I used my repo to make everything work properly, binding the fetch and inferring into `SuiGraphQLClient`. As you can see in the following link, and can access the preview link to verify that everything is working good.

https://github.com/git-marcopitra/zksend-csr/pull/1

---
If your changes are not user-facing and do not break anything, you can skip the following section. Otherwise, please briefly describe what has changed under the Release Notes section.

### Type of Change (Check all that apply)

- [ ] protocol change
- [ ] user-visible impact
- [ ] breaking change for a client SDKs
- [ ] breaking change for FNs (FN binary must upgrade)
- [ ] breaking change for validators or node operators (must upgrade binaries)
- [ ] breaking change for on-chain data layout
- [ ] necessitate either a data wipe or data migration

### CODE REVIEW

**Comment by hayes-mysten** [comment]
Thanks for the detailed report and fix!  I just fixed this issue in the GraphQL client yesterday (https://github.com/MystenLabs/sui/pull/17006).  If you upgrade this should be fixed now.    There will be another fix going out in the next couple hours (https://github.com/MystenLabs/sui/pull/17013)

**Comment by hayes-mysten** [comment]
I think the issue you ran into should be fixed by the change I mentioned above, but this could still be useful for environments that don't support fetch.

If you can add a changeset, I can get this merged for you

**Comment by git-marcopitra** [comment]
> I think the issue you ran into should be fixed by the change I mentioned above, but this could still be useful for environments that don't support fetch.
> 
> If you can add a changeset, I can get this merged for you

Perfect, let me update in a bit

**Comment by hayes-mysten** [comment]
I merged your commits into another PR to add a little cleanup.  Thanks for adding this!

**Pull request closed without merging**
