### PR TITLE
fixed explorer link only pointing to the default env link

### PR DESCRIPTION
**Pull request by Jibz1**

### CODE REVIEW

**Review by pchrysochoidis — CHANGES_REQUESTED** [review]
We have [Explorer](https://github.com/MystenLabs/fastnft/blob/a7ec54bed3476de76c1d72779d343ea55261162e/wallet/src/ui/app/components/explorer-link/Explorer.ts) for this. The problem is that it doesn't take into account the current API_ENV (if the user changed the the env) We should update that I think.

(This MR only fixes the address link, we need to fix the others al well right?)

**Comment by pchrysochoidis** [comment]
> > We have [Explorer](https://github.com/MystenLabs/fastnft/blob/a7ec54bed3476de76c1d72779d343ea55261162e/wallet/src/ui/app/components/explorer-link/Explorer.ts) for this. The problem is that it doesn't take into account the current API_ENV (if the user changed the api env) We should update that I think.
> > (This MR only fixes the address link, we need to fix the others as well right?)
> 
> What of working in local environment.

Not sure what you mean. Now that we have the switch we should open links to the explorer based on the selected API_ENV, right?

**Comment by Jibz1** [comment]
> > > We have [Explorer](https://github.com/MystenLabs/fastnft/blob/a7ec54bed3476de76c1d72779d343ea55261162e/wallet/src/ui/app/components/explorer-link/Explorer.ts) for this. The problem is that it doesn't take into account the current API_ENV (if the user changed the api env) We should update that I think.
> > > (This MR only fixes the address link, we need to fix the others as well right?)
> > 
> > 
> > What of working in local environment.
> 
> Not sure what you mean. Now that we have the switch we should open links to the explorer based on the selected API_ENV, right?

That is what this fix address.

**Comment by Jibz1** [comment]
@666lcz I seen it

**Comment by 666lcz** [comment]
fixed in https://github.com/MystenLabs/sui/pull/2882

**Pull request closed without merging**
