### PR TITLE
[crypto] Add Networking key and Switch to BLS12-381

### PR DESCRIPTION
**Pull request by punwai**
**Closing this PR as it is now being splitted into 2 parts**: #4408 to first change the Network Key and another (upcoming) one which will change the BLS

This PR switches the Sui network to run on the BLS12-381 signature scheme. This change causes the following breaking changes (and fixes):
- AuthorityQuorumSignInfo now holds a single aggregated signature vs. a vector of signatures. This is reflected in the explorer.
- We edit the keytool file to generate BLS12-381 keypairs as well as ed25519, and secp256k1. The BLS12-381 will not be flagged, while the other two are. There is no ambiguity here despite the lack of a flags for BLS, as all keypair files will have the signature scheme (bls || ed25519 || secpk1) tagged to the file name, and any attempt to use BLS key files in place of ed25519 or secp256k1 should fail due to serialization error.
- Our Proof of Possessions are now running on BLS12-381.

TODO: ensure that production engineers expect this, and prepare PR that fixes CLI config files (merged instantly), as well as staging and devnet (left unmerged until when we include this in the next release). @huitseeker any comments?

Adjacent PRs:
Fixes the config files for when we productionize BLS https://github.com/MystenLabs/sui-operations/pull/366. I have attempted to deploy a 4-node cluster docker image with these configs - so they should be working.
Private Testnet Genesis https://github.com/MystenLabs/private-testnet-genesis/pull/9

### CODE REVIEW

**Comment by punwai** [comment]
Just letting you know that this should be reviewed before the other one is merged so that Sui doesn't lag behind too much!

**Review by kchalkias — COMMENTED** [review]
@punwai can you make this PR only NetworkKey specific and add the 4 lines for BLS in another one? Or at least update commit message and title?

**Review by huitseeker — COMMENTED** [review]
My only comment is that of @kchalkias, i.e. to split the change between the addition of the network key on the one hand, and that of BLS on the other hand. This would allow pulling the cord on BLS if we face production issues.

**Comment by punwai** [comment]
> @punwai can you make this PR only NetworkKey specific and add the 4 lines for BLS in another one? Or at least update commit message and title? 

We can create a PR that reverts the BLS change back to ed25519 (the 4 lines) which makes the previous PR effectively changing the network configs. Obviously, this would require changes to the fabfile, but if we are going to merge BLS anyways, perhaps it is fine to have it broken for a commit.

**Comment by punwai** [comment]
Thanks @joyqvq for helping close this!

**Pull request closed without merging**
