### PR TITLE
Explore tx

### PR DESCRIPTION
**Pull request by Jibz1**
- Added transaction card component which maps the transaction data to different display types
- The transaction page displays transfers and Calls
- Modified mock_data.json to include tx data. Even though `id`, `category`, `sender`, and `status` are not part of the transaction data, I added them to keep the `findDataFromID` method working. 

Todo 
Add @stella3d transaction commit

Screen Shot 2022-04-27 at 10 18 57 PM

Transactions with Call types
Screen Shot 2022-04-28 at 3 34 40 PM

### CODE REVIEW

**Comment by 666lcz** [comment]
Great work! A few nits on the UI:

1. The object references(in the `Object Reference` field and `Gas Payment` field in the screenshot) has three fields: ObjectId, Sequence Number, and Object Digest. I feel like most users only care about the ObjectId. For simplicity, can we remove the other two and make `ObjectId` a hyperlink to the `Object Result` page? cc @bwann52 if you have any thoughts

2. Consider rename `Signature` to `Validator Signatures` to differentiate with `Tx Signatures`(by the transaction initiator). Also let's add annotations to the validator signatures (e.g., "Name", "Signature" for the first and second element). An example would be:

CleanShot 2022-04-28 at 11 39 17

**Comment by Jibz1** [comment]
@666lcz ObjectId, Sequence Number, and Object Digest in that sequence, meaning the first number in `gas_payment` array will always be the `ObjectId`?
Screen Shot 2022-04-28 at 2 53 41 PM

**Comment by bwann52** [comment]
UI feedback:
- Remove results from status
- @sblackshear raised the point we may have multiple "Tos" in this case should we replace with sender address and receiver address? @666lcz what do you think?
- Replace "Transaction Kind" with "Transaction Type"
- not a priority, but if easy can we decrease the white space between row title and row content?

**Comment by 666lcz** [comment]
> ObjectId, Sequence Number, and Object Digest in that sequence, meaning the first number in gas_payment array will always be the ObjectId

Synced offline, the answer is yes

**Comment by Jibz1** [comment]
@bwann52 @Andrew47 slight page design update. @666lcz @bwann52 please review the attached image
Screen Shot 2022-04-28 at 6 56 18 PM

**Comment by bwann52** [comment]
There is no design revamp, let's make sure we are building on the same, simple design patterns for this build. cc @666lcz @Andrew47 @Jibz1 

@Jibz1 per your last screenshot
1. What does object reference mean?
2. Let's not say "tx" instead write it out as "Transactions" for style consitency
3. Per last comment, instead of from/to let's go with sender/receiver
4. Instead of Gas Payment, let's say Gas Fee

**Comment by 666lcz** [comment]
@Jibz1 , Let's stick with the style that Andrew has been using in https://github.com/MystenLabs/sui/pull/1678 (e.g., black header instead of blue, same icone)

**Pull request closed without merging**
