### PR TITLE
[explorer] Redesigns Header and Footer

### PR DESCRIPTION
**Pull request by Andrew47**
As of 30 June 2022, the previous header/footer can be seen in the currently deployed website: https://explorer.staging.sui.io/

The new header and footer in Firefox, showing difference between Desktop and Galaxy Fold apperance:

https://user-images.githubusercontent.com/11377188/176648305-7bb87f88-ffb8-4845-b0ac-dec3246bc29c.mp4

The new header and footer in Google Chrome, showing difference between Desktop and Galaxy Fold apperance:

https://user-images.githubusercontent.com/11377188/176648911-a1099889-29cf-4102-916d-7d1fcac82aa6.mp4

I've also tested the new header and footer in Safari and Microsoft Edge.

### CODE REVIEW

**Review by Jibz1 — APPROVED** [review]

**Review by 666lcz — CHANGES_REQUESTED** [review]
This is great! A few nits to be addressed:


CleanShot 2022-07-01 at 08 35 46


1. The bottom spacing of the footer seems to be off
2. we are missing "medium" from the read column
3. the position/alignment of the icon seems to be a little bit off
CleanShot 2022-07-01 at 08 39 03
CleanShot 2022-07-01 at 08 40 03
4. we don't support search by Epoch yet, can we remove it for now?
CleanShot 2022-07-01 at 08 43 08
5. We probably want to reduce the max length of the search bar

CleanShot 2022-07-01 at 08 45 13

6. The vertical spacing needs to be adjusted
CleanShot 2022-07-01 at 08 46 15

CleanShot 2022-07-01 at 08 46 04

**Comment by Andrew47** [comment]
Done. See Slack regarding Blog vs Medium links. Current approach is to have just a 'Blog' link (see https://sui.io/).

**Comment by Andrew47** [comment]
@666lcz --> Given the above changes, is this good for merge?

**Review by 666lcz — APPROVED** [review]

**Comment by 666lcz** [comment]
Looks good! Thanks for addressing the comments!

**Pull request merged**
