### PR TITLE
[move-2024] Change  default TOML to be 2024 beta

### PR DESCRIPTION
**Pull request by cgswords**
## Description 

Change  default TOML to be 2024 beta

## Test Plan 

Local testing, plus other tests still work.

---
If your changes are not user-facing and do not break anything, you can skip the following section. Otherwise, please briefly describe what has changed under the Release Notes section.

### Type of Change (Check all that apply)

- [ ] protocol change
- [x] user-visible impact
- [ ] breaking change for a client SDKs
- [ ] breaking change for FNs (FN binary must upgrade)
- [ ] breaking change for validators or node operators (must upgrade binaries)
- [ ] breaking change for on-chain data layout
- [ ] necessitate either a data wipe or data migration

### Release notes

Changes the default `Move.toml` for `sui move new` and `move new` to use the Move 2024 beta release.

### CODE REVIEW

**Review by tnowacki — APPROVED** [review]

**Review by rvantonder — COMMENTED** [review]
@cgswords can you hold off on merging this? I think if today someone started using this, and tries to publish a `2024.beta` edition it is going to fail dependency verification on `sui` framework packages (because it is going to compile the current `sui` framework with `2024.beta`, which I think mismatches the current on-chain bytecode). 

I need to double check things here and come up with a way to resolve if it's the case. As mentioned in our talk, we don't currently version compilation of sui framework packages, and always choose the current compiler. I may need to revisit how that works if we are enabling `2024.beta` but don't yet publish sui framework packages to chain with `2024.beta`.

**Comment by rvantonder** [comment]
In fact this change should probably come with an integration test that does something like

```
sui move build
sui move publish . --gas-budget 10000000   
```

I will help with that--I have a hunch I will need to make a change to toolchain versioning code before that "just works".

**Comment by rvantonder** [comment]
> which I think mismatches the current on-chain bytecode

Okay there's no mismatch, I was checking different changes locally (localnet vs testnet). 

Still, think it's worthwhile to have a test here, will see if I can tack on a commit to this PR!

**Comment by rvantonder** [comment]
On second thought--clarified with @cgswords I missed that `edition` is per package, so this won't affect framework compilation. I had thought specifying the edition in Move.toml is like specifying `--default-move-edition` but that's not the case.

**Review by rvantonder — APPROVED** [review]

**Pull request merged**
