### PR TITLE
Bump fastcrypto

### PR DESCRIPTION
**Pull request by jonas-lj**
## Description 

Update to the most recent version of fastcrypto. This includes an optimisation on how aggregated signatures with different messages are verified in BLS12-381.

The `schemars` dependency also had to be updated to match the version in fastcrypto.

### CODE REVIEW

**Review by kchalkias — COMMENTED** [review]
@jonas-lj now that we merged the arkworks dep version update in fastcrypto, can we update to that version?

**Review by kchalkias — APPROVED** [review]

**Comment by kchalkias** [comment]
simtest fails with:
--- STDERR:              
sui::reconfiguration_tests test_validator_resign_effects ---
thread '<unnamed>' panicked at 'timed out waiting for reconfiguration to complete: Elapsed', crates/sui/tests/reconfiguration_tests.rs:536:10
stack backtrace:

**Review by kchalkias — APPROVED** [review]

**Review by kchalkias — COMMENTED** [review]
Is it normal for the simtest to fail?

**Comment by jonas-lj** [comment]
> Is it normal for the simtest to fail?

No, it's because of this pr but I don't know why yet. I've asked around on slack to get some hints.

**Pull request merged**
