### PR TITLE
[move-compiler] Parallelize parsing files. Parallelize visitors. 

### PR DESCRIPTION
**Pull request by tnowacki**
## Description 

- Made parsing parallel
- Made visitor execution parallel
- Unfortunately, even the sui-framework is not large enough to really notice a difference (if anything it got a bit slower)

## Test plan 

- tests

---

## Release notes

Check each box that your changes affect. If none of the boxes relate to your changes, release notes aren't required.

For each box you select, include information after the relevant heading that describes the impact of your changes that a user might notice and any actions they must take to implement updates. 

- [ ] Protocol: 
- [ ] Nodes (Validators and Full nodes): 
- [ ] Indexer: 
- [ ] JSON-RPC: 
- [ ] GraphQL: 
- [ ] CLI: 
- [ ] Rust SDK:
- [ ] REST API:

### CODE REVIEW

**Review by dariorussi — COMMENTED** [review]
have you looked at the failures?
thoughts about them?

**Review by tzakian — APPROVED** [review]
This is disturbingly (delightfully?) short. 

Only thing: we order diagnostics before rendering them right? Just want to double that this won't lead to non-determinist ordering of lint warnings/errors from the compiler.

**Comment by tnowacki** [comment]
> This is disturbingly (delightfully?) short.
> 
> Only thing: we order diagnostics before rendering them right? Just want to double that this won't lead to non-determinist ordering of lint warnings/errors from the compiler.

This is the easy one. Modules for the other passes will be... annoying. 
And for things like typing and cfgir we might want to do per-function. Which will be... annoying

**Pull request merged**
