### PR TITLE
Update code coverage notification message

### PR DESCRIPTION
**Pull request by mwtian**
## Description 

Instruct oncall to look over the code coverage report.

## Test plan 

👀

---

## Release notes

Check each box that your changes affect. If none of the boxes relate to your changes, release notes aren't required.

For each box you select, include information after the relevant heading that describes the impact of your changes that a user might notice and any actions they must take to implement updates. 

- [ ] Protocol: 
- [ ] Nodes (Validators and Full nodes): 
- [ ] Indexer: 
- [ ] JSON-RPC: 
- [ ] GraphQL: 
- [ ] CLI: 
- [ ] Rust SDK:

### CODE REVIEW

**Comment by ebmifa** [comment]
I don't think this will be helpful, there is an action item to do daily here, look at the reports and see if code coverage has decreased.
Screenshot 2024-05-02 at 8 58 44 AM
See https://app.codecov.io/github/MystenLabs/sui/tree/main?search=&components%5B0%5D=Sui%20Types&displayType=list as well
Perhaps, maybe we need to create a notion page runbook for this. Which I think is better than this PR.

Thoughs?

**Comment by mwtian** [comment]
Can these threshold checks be automated and can be fixed in some way? Otherwise people will just get desensitized on the notifications. But I can definitely update the runbook.

**Comment by ebmifa** [comment]
Yeah, it was on my to do list, but got side tracked with higher priority items. I'll try to get to it soon.

**Comment by mwtian** [comment]
How about this message, or do we have more comprehensive rules?

**Review by ebmifa — APPROVED** [review]

**Pull request merged**
