### PR TITLE
[bridge] emit CommitteeMemberUrlUpdateEvent event 

### PR DESCRIPTION
**Pull request by longbowlu**
## Description 

1. emit CommitteeMemberUrlUpdateEvent when a validator updates url
2. add url checks when validator add or update bridge url
3. update a comment: the Blocklist payload contains 20 bytes evm addresses instead of 33 bytes pub keys

## Test plan 

How did you test the new or updated feature?

---

## Release notes

Check each box that your changes affect. If none of the boxes relate to your changes, release notes aren't required.

For each box you select, include information after the relevant heading that describes the impact of your changes that a user might notice and any actions they must take to implement updates. 

- [ ] Protocol: 
- [ ] Nodes (Validators and Full nodes): 
- [ ] Indexer: 
- [ ] JSON-RPC: 
- [ ] GraphQL: 
- [ ] CLI: 
- [ ] Rust SDK:

### CODE REVIEW

**Review by dariorussi — APPROVED** [review]
it seems good to me

**Comment by dariorussi** [comment]
@longbowlu can you explain the protocol version change? I get lost every time we bump protocol versions

**Comment by longbowlu** [comment]
> @longbowlu can you explain the protocol version change? I get lost every time we bump protocol versions

I think we have to bump the version but i might be wrong. If I don't bump it, the snapshot compatibility test fails. Thoughts? @dariorussi  @patrickkuo

**Review by patrickkuo — APPROVED** [review]
LGTM, thanks for adding this.

**Comment by patrickkuo** [comment]
Will need to bump the protocol version because snapshot version 51 has been created already (in sui-framework-snapshot)

**Comment by longbowlu** [comment]
> > I think we have to bump the version but i might be wrong. If I don't bump it, the snapshot compatibility test fails. Thoughts? @dariorussi @patrickkuo
> 
> Will need to bump the protocol version because snapshot version 51 has been created already (in sui-framework-snapshot)

theoretically speaking, can we update the snapshot? since it's not on testnet/mainnet yet

**Comment by patrickkuo** [comment]
> > > I think we have to bump the version but i might be wrong. If I don't bump it, the snapshot compatibility test fails. Thoughts? @dariorussi @patrickkuo
> > 
> > 
> > Will need to bump the protocol version because snapshot version 51 has been created already (in sui-framework-snapshot)
> 
> theoretically speaking, can we update the snapshot? since it's not on testnet/mainnet yet

I don’t know, will need to ask @ebmifa

**Pull request merged**
