### PR TITLE
[doc] Fork the Sui repo instead of cloning

### PR DESCRIPTION
**Pull request by sblackshear**

### CODE REVIEW

**Review by huitseeker — COMMENTED** [review]
This is non-standard tooling, in the sense that it requires folks to register with GIthub and create an account (which git very much does not).  It also makes people create a local fork on that GitHub account. 

I do not think this has a place in installation instructions. Rather, this should be in "contributing" instructions.

**Comment by longbowlu** [comment]
> This is non-standard tooling, in the sense that it requires folks to register with GIthub and create an account (which git very much does not). It also makes people create a local fork on that GitHub account.
> 
> I do not think this has a place in installation instructions. Rather, this should be in "contributing" instructions.

I have to sadly agree although I understand where this comes from :/

**Comment by sblackshear** [comment]
I understand the objections. One response is that this paves a smoother path from trying out Sui to becoming a contributor. But guessing that is not the most common flow.

**Comment by huitseeker** [comment]
> One response is that this paves a smoother path from trying out Sui to becoming a contributor

Oh we should definitely suggest a `gh fork`, and it's a great idea, in the section where we address "how to contribute" or otherwise talk to that persona.

**Comment by Clay-Mysten** [comment]
> > One response is that this paves a smoother path from trying out Sui to becoming a contributor
> 
> Oh we should definitely suggest a `gh fork`, and it's a great idea, but in the section where we address "how to contribute" or otherwise talk to that persona.

We do that already here:
https://docs.sui.io/contribute#send-pull-requests

**Comment by sblackshear** [comment]
Sounds like this is redundant then--thanks for setting me straight!

**Pull request closed without merging**
