### PR TITLE
Remove usage of Session from adapter

### PR DESCRIPTION
**Pull request by dariorussi**
## Description 

This is the first step in removing Session from the execution layer/adapter.
It actually gets rid of Session entirely, however more work is planned to rework how the VM is using the traits from the adapter (specifically storage traits).
This is in its own version so we can commit without worrying too much about minor changes in behavior. FWIW I tested on a node syncing from when `latest` was introduced and it seems to work fine anyway.
However a couple of changes are coming around publishing that will need a protocol config so versioning the execution layer is a good step in that direction.
Please notice that this is a "copy" from #13000 and the massive change is just due to the copy of the execution layer

## Test Plan 

Existing tests. Will add more related to changes to publishing

---
If your changes are not user-facing and not a breaking change, you can skip the following section. Otherwise, please indicate what changed, and then add to the Release Notes section as highlighted during the release process.

### Type of Change (Check all that apply)

- [ ] protocol change
- [ ] user-visible impact
- [ ] breaking change for a client SDKs
- [ ] breaking change for FNs (FN binary must upgrade)
- [ ] breaking change for validators or node operators (must upgrade binaries)
- [ ] breaking change for on-chain data layout
- [ ] necessitate either a data wipe or data migration

### CODE REVIEW

**Comment by dariorussi** [comment]
ok this is a bit crazy but I am not sure what to do. I am not sure if there is a good way to diff the changes against latest (@amnn).
Also looking for suggestion on how to make more changes in this PR and show what they are as opposed to see the entire mess

**Comment by dariorussi** [comment]
changed `rem_sess` to `rem-sess` so cargo is happy, few more things to fix though

**Comment by dariorussi** [comment]
also for context, maybe I should dump this PR and any execution version change should follow those steps:
1- create the version with no changes at all. That will be likely just trusting the PR but it would be a PR that all it does is to create a copy (the massive PR)
2- add changes as PR stacked on top of that
3- squash and merge

thoughts?
happy to dump this in favor of the other model....

**Comment by amnn** [comment]
Yes, what you've suggested in your follow-up is what I would do, roughly: Create the cut in its own PR and then make changes on top of that.

I would also not squash the changes into the cut PR when landing, because then you'll have the same problem in identifying what actually changed when looking at the commit history.

**Comment by dariorussi** [comment]
I am going to make the different steps as outlined above, closing this

**Pull request closed without merging**
