### PR TITLE
chore: bump narwhal version

### PR DESCRIPTION
**Pull request by joyqvq**

### CODE REVIEW

**Comment by joyqvq** [comment]
big bump in narwhal: https://github.com/MystenLabs/narwhal/compare/5ba330d0cefa33ba835ffe56489e6500a2909d8a..88670339ac76ecb8a5d337ed33a1711af0df5386 anything breaking?

**Review by huitseeker — CHANGES_REQUESTED** [review]
This will break in authority.rs.
I believe the last commit you can get w/o adaptations in NW is 8fe3369aba281352e626d2ed49542c608148f2ce.

See https://github.com/MystenLabs/narwhal/pull/602
And its test branch: https://github.com/MystenLabs/sui/compare/main...huitseeker:update_narwhal_pointers_2?expand=1

**Review by huitseeker — CHANGES_REQUESTED** [review]
The d67e27d33b8515f919f45694660fceb20db626c4 NW commit is not merged to main and so can't be used. As you're updating this branch, you will essentially, fixing failure by failure, reproduce work done in https://github.com/MystenLabs/sui/compare/main...huitseeker:update_narwhal_pointers_2?expand=1

**Comment by joyqvq** [comment]
> The d67e27d33b8515f919f45694660fceb20db626c4 NW commit is not merged to main and so can't be used. As you're updating this branch, you will essentially, fixing failure by failure, reproduce work done in https://github.com/MystenLabs/sui/compare/main...huitseeker:update_narwhal_pointers_2?expand=1

I decided to use the last commit without needing to fix anything, for now just to unblock myself. will send a follow up when narwhal fix lands

**Comment by punwai** [comment]
@joyqvq Please forcepush to this PR :(

**Comment by joyqvq** [comment]
point to commit in this PR: https://github.com/MystenLabs/narwhal/pull/602/commits wait till it lands

**Review by huitseeker — APPROVED** [review]
Thank you @joyqvq !

**Pull request merged**
