### PR TITLE
Show object owner

### PR DESCRIPTION
**Pull request by mystenmark**
(stacked on #3272)

Example output:

```
$ ./target/debug/sui-tool fetch-object  --id 0xab2eb165e48069bfbc3276b806783fa8a9368cd3 --genesis /Users/mlogan/.sui/sui_config/genesis.blob --history --concise
validator                                                          version  digest                                                             parent_cert                                   owner
k#047e8458515c06dc7402b2410c79126b8492d6d546188c753b4b08825cc1ca87 1        o#6f3014f0a65bbbaef5904a345b853e88eb7cd062857a06d627ece739ee6a83df 8VmPRPVf/YnrvfQDDCJYQaueDZyl9ND4JvHBTQ/mxuM=  address(0x0c71e68d657f6d8241f4a89e377fec381db2a8b5)
k#047e8458515c06dc7402b2410c79126b8492d6d546188c753b4b08825cc1ca87 0        o#44c44c9f20cda0f8d43ba6489440e72cbcd0d18c67261309aada40a18ad15fc5 <genesis>                                     no-owner-available
k#9decab06c6d7a8e463469b0b31090be37337f5eb27e07eb1ba4407d41b6a6c9b 1        o#6f3014f0a65bbbaef5904a345b853e88eb7cd062857a06d627ece739ee6a83df 8VmPRPVf/YnrvfQDDCJYQaueDZyl9ND4JvHBTQ/mxuM=  address(0x0c71e68d657f6d8241f4a89e377fec381db2a8b5)
k#9decab06c6d7a8e463469b0b31090be37337f5eb27e07eb1ba4407d41b6a6c9b 0        o#44c44c9f20cda0f8d43ba6489440e72cbcd0d18c67261309aada40a18ad15fc5 <genesis>                                     no-owner-available
k#a999d83d14d9db70091053c9fbae0bdefdd3c6ee492a1a750122647d5ea2d7fa 1        o#6f3014f0a65bbbaef5904a345b853e88eb7cd062857a06d627ece739ee6a83df 8VmPRPVf/YnrvfQDDCJYQaueDZyl9ND4JvHBTQ/mxuM=  address(0x0c71e68d657f6d8241f4a89e377fec381db2a8b5)
k#a999d83d14d9db70091053c9fbae0bdefdd3c6ee492a1a750122647d5ea2d7fa 0        o#44c44c9f20cda0f8d43ba6489440e72cbcd0d18c67261309aada40a18ad15fc5 <genesis>                                     no-owner-available
k#d5edb8eabc6dfe61f1befa5d7b1e40ed865464f2b8c0d19394fdde0f87020d5b 1        o#6f3014f0a65bbbaef5904a345b853e88eb7cd062857a06d627ece739ee6a83df 8VmPRPVf/YnrvfQDDCJYQaueDZyl9ND4JvHBTQ/mxuM=  address(0x0c71e68d657f6d8241f4a89e377fec381db2a8b5)
k#d5edb8eabc6dfe61f1befa5d7b1e40ed865464f2b8c0d19394fdde0f87020d5b 0        o#44c44c9f20cda0f8d43ba6489440e72cbcd0d18c67261309aada40a18ad15fc5 <genesis>                                     no-owner-available
```

### CODE REVIEW

**Comment by lxfind** [comment]
Thanks! What's the reason to not just print the original owner object?

**Comment by lxfind** [comment]
also I have a feeling that we might lose the table view quickly: the returned object response contains the move struct layout, which should allow us easily print the move data in json format (we do that in sui client)

**Comment by lxfind** [comment]
that said, we may want to consider keep the implementation as simple as possible

**Comment by mystenmark** [comment]
> Thanks! What's the reason to not just print the original owner struct?

to be friendly to unix tools that understand fields (awk, sort, uniq, etc)

> also I have a feeling that we might lose the table view quickly: the returned object response contains the move struct layout, which should allow us easily print the move data in json format (we do that in sui client)

we can definitely do that in the verbose output. The concise output is really important for processing with unix tools, imo. For instance, see the description of #3272 for a one-liner that quickly verifies all validators have the same history for an object.

**Review by damirka — APPROVED** [review]
Looks good to me! Thanks!

**Pull request merged**
