### PR TITLE
finish moving all crates into the crates directory

### PR DESCRIPTION
**Pull request by bmwill**
This finishes up the migration to having all crates be defined in the `crates/` directory

### CODE REVIEW

**Comment by patrickkuo** [comment]
Can we hold this off for a few days unless it’s blocking other work? It will be hard to rebase for my PR :|

**Comment by bmwill** [comment]
> Can we hold this off for a few days unless it’s blocking other work? It will be hard to rebase for my PR :|

Given there are very few actual code changes in this PR (just moving code around) you really shouldn't see very many conflicts. Git should be able to understand that the files moved and apply your changes to the moved files.

At someone we're going to have to rip the band-aid off though and I'd rather get these things in sooner rather than later

**Comment by mystenmark** [comment]
Maybe we can try rebasing @patrickkuo's branch onto this branch first to verify the "it shouldn't generate many conflicts" theory? I know git is supposed to do what you say, but I feel like its iffy in practice

**Comment by bmwill** [comment]
I'll commit to handle any merge conflicts if they do arise. In fact I'll do that immediately once this lands and push the changes somewhere for @patrickkuo to look at

**Comment by bmwill** [comment]
As it turns out the PR in question https://github.com/MystenLabs/sui/pull/2087 already has merge conflicts with the tip of main. These are due to some changes I made over the weekend to merge fullnode and validator into a single binary.

**Review by mystenmark — APPROVED** [review]

**Pull request merged**
