### PR TITLE
Bump Sui GraphQl version: `v2024.7.0`

### PR DESCRIPTION
**Pull request by ebmifa**
## Description 
Bump Sui GraphQl version: `v2024.7.0`

## Test plan 
`cargo build --release`

### CODE REVIEW

**Comment by stefan-mysten** [comment]
@ebmifa I am slightly confused why this is `2024.8` instead of `2024.4`.

**Comment by ebmifa** [comment]
@stefan-mysten this is for the main branch, since the next branch cut is going to be `2024.8` in August, right>

**Comment by stefan-mysten** [comment]
Oh, I see, ok. I thought it's for the 2024.4 branch.

**Review by amnn — APPROVED** [review]
Our next version will be `2024.7.0` (start of the Q3) but accepting to unblock!

**Pull request merged**
