### PR TITLE
Improve perf or TransactionManager::enqueue

### PR DESCRIPTION
**Pull request by mystenmark**
Haven't tested this yet, please let me know what you think of the general approach.

### CODE REVIEW

**Review by mwtian — COMMENTED** [review]
I like the lock protected inner object approach! For enqueueing on a separate task, let me double check to see if we really need that.

**Comment by mystenmark** [comment]
> For enqueueing on a separate task, let me double check to see if we really need that.

I'm not quite sure either - but if we don't put it on a separate task, the consensus task still has to do all the work it did before. The only difference is that it there could be less lock contention. But I'm not sure how much of an issue that was - I would expect that during normal operation, the main source of enqueue operations is going to be the consensus task itself. In any case feel free to try this with and without the second commit and see if it makes any difference.

**Comment by mwtian** [comment]
Hopefully after https://github.com/MystenLabs/sui/pull/6537 only the 1st commit would be needed.

**Review by mwtian — APPROVED** [review]
Useful optimizations, thanks!

**Comment by mystenmark** [comment]
Sorry I didn't see your last comment - the same thing actually occurred to me at one point and then I forgot about it!

**Comment by mwtian** [comment]
It's fine. Fixing it in my next PR!

**Pull request merged**
