### PR TITLE
[bridge 8/n] make authority aggregation function more generic

### PR DESCRIPTION
**Pull request by longbowlu**
## Description 

`BridgeClient` needs to talk to bridge authorities similar to how AuthorityAggregator works. This PR make `quorum_map_then_reduce_with_timeout_and_prefs` and `quorum_map_then_reduce_with_timeout` more generic, and move them to a new crate `sui-common` because we don't want `sui-bridge` to depend on `sui-core`.

Why it's not in `mysten-common` crate? because that crate does not depend on any `sui` stuff and i don't want to break it..

The most important thing in this PR is to make sure the original member functions now trait method `weight` and `shuffle_by_stake_with_rng` does not change.

## Test Plan 

All existing tests.

---
If your changes are not user-facing and not a breaking change, you can skip the following section. Otherwise, please indicate what changed, and then add to the Release Notes section as highlighted during the release process.

### Type of Change (Check all that apply)

- [ ] protocol change
- [ ] user-visible impact
- [ ] breaking change for a client SDKs
- [ ] breaking change for FNs (FN binary must upgrade)
- [ ] breaking change for validators or node operators (must upgrade binaries)
- [ ] breaking change for on-chain data layout
- [ ] necessitate either a data wipe or data migration

### Release notes
[bridge 8/n] make authority aggregation function more generic

### CODE REVIEW

**Comment by lxfind** [comment]
I am not sure if this is the right thing to do, for a few reasons:
1. sui-bridge already depends on sui-core, unfortunately, since it depends on sui-sdk, which depends on sui-json-rpc, which in turn depends on sui-core. To remove that dependency completely is doable but requires some significant refactoring.
2. Even if we can get rid of that dependency eventually, I prefer to not have a crate called sui-common because the name is too vague and we may end up putting random stuff to it. If you really want to, sui-authority-aggregation is a clearer name to start. If we find more stuff that we want to share between sui-bridge and core in the future, we can come up with better names

**Comment by longbowlu** [comment]
> I am not sure if this is the right thing to do, for a few reasons:
> 
> 1. sui-bridge already depends on sui-core, unfortunately, since it depends on sui-sdk, which depends on sui-json-rpc, which in turn depends on sui-core. To remove that dependency completely is doable but requires some significant refactoring.
> 2. Even if we can get rid of that dependency eventually, I prefer to not have a crate called sui-common because the name is too vague and we may end up putting random stuff to it. If you really want to, sui-authority-aggregation is a clearer name to start. If we find more stuff that we want to share between sui-bridge and core in the future, we can come up with better names

> sui-bridge already depends on sui-core

oh that's unfortunate, i forgot about it ...

To be honest this PR itself is much larger than simply copying the function, so I'm totally open to do it instead for now, which will make my life easier. @lxfind wdyt?

**Comment by lxfind** [comment]
> simply copying the function

That seems strictly worse than just depending on sui-core? Or just rename this crate to be very specific and revisit it latter.

**Comment by longbowlu** [comment]
> > simply copying the function
> 
> That seems strictly worse than just depending on sui-core? Or just rename this crate to be very specific and revisit it latter.

I wouldn't say it's "strictly" worse - it makes the bridge code a bit more flexible in some small details (which we can see from https://github.com/MystenLabs/sui/pull/15294). But renaming this crate to be `sui-authority-aggregation` sounds good to me as well.

**Comment by longbowlu** [comment]
renamed the crate to `sui-authority-aggregation`

**Review by lxfind — APPROVED** [review]

**Review by arun-koshy — APPROVED** [review]

**Pull request merged**
