### PR TITLE
[Fix fork] TransactionManager respects type argument dependencies

### PR DESCRIPTION
**Pull request by mystenmark**
based on #7940

### CODE REVIEW

**Review by bmwill — APPROVED** [review]

**Review by mwtian — COMMENTED** [review]
Are we sure that when the package becomes available, it is in the list of outputs sent to `objects_committed()`?

**Comment by mystenmark** [comment]
> Are we sure that when the package becomes available, it is in the list of outputs sent to `objects_committed()`?

yes - we respect package dependencies most of the time, just not in the case of type arguments

**Review by mwtian — APPROVED** [review]
Agree. I hope this can be verified with a unit test but up to you to decide.

**Comment by mystenmark** [comment]
> Agree. I hope this can be verified with a unit test but up to you to decide.

```
        // If commit_certificate returns an error, tx_guard will be dropped and the certificate
        // will be persisted in the log for later recovery.
        let output_keys: Vec<_> = inner_temporary_store
            .written
            .iter()
            .map(|(_, ((id, seq, _), _, _))| ObjectKey(*id, *seq))
            .collect();
```

**Comment by mystenmark** [comment]
I'm pretty sure existing tests cover this case

**Pull request merged**
