### PR TITLE
Improve wallet error message

### PR DESCRIPTION
**Pull request by no2chem**
Hi all 👋

This project is looking like its off to a good start 🎉!

I tried to quickly test things out by deploying a wallet. One issue I found myself stuck for a few minutes was the wallet - it wasn't immediately clear I needed to run `sui genesis` first, and I thought something was wrong with my installation.

I made a quick change to wallet by using anyhow::Context (which the project already uses) to add a helpful error message that could help save people some time in the future.

### CODE REVIEW

**Comment by awelc** [comment]
Good catch! We are trying to handle it more comprehensively in #1057, though. Let's keep this one open until an actual fix lands, one way or the other.

**Comment by no2chem** [comment]
Sounds good.

Having a .sui directory in $HOME seems like a good idea. I'd also suggest maybe renaming `wallet` to `sui_wallet`, but that's a personal preference...

**Review by huitseeker — APPROVED** [review]
Sorry for getting to this so late @no2chem! Thanks for the contribution!

**Comment by awelc** [comment]
I would not merge it "as is" as the help message is no longer accurate after https://github.com/MystenLabs/sui/pull/1057 landed. You still have to run genesis, but you don't have to run wallet in the same directory where genesis was ran.

**Comment by awelc** [comment]
@no2chem - thank you for the contribution (and your kind words!) but since the original problem is mitigated I am going to close this PR.

**Pull request closed without merging**
