### PR TITLE
[CLI] fix `sui keytool zk-login-sign-and-execute-tx` command bug

### PR DESCRIPTION
**Pull request by bityoume**
## Description 

[CLI] fix `sui keytool zk-login-sign-and-execute-tx` command bug

image

## Test plan 

How did you test the new or updated feature?

---

## Release notes

Check each box that your changes affect. If none of the boxes relate to your changes, release notes aren't required.

For each box you select, include information after the relevant heading that describes the impact of your changes that a user might notice and any actions they must take to implement updates. 

- [ ] Protocol: 
- [ ] Nodes (Validators and Full nodes): 
- [ ] Indexer: 
- [ ] JSON-RPC: 
- [ ] GraphQL: 
- [x] CLI:  Fixed the code to ensure it has a `gas coin` for the `sui keytool zk-login-sign-and-execute-tx` command.
- [ ] Rust SDK:

### CODE REVIEW

**Comment by stefan-mysten** [comment]
Thanks @bityoume. Can you also add a descriptive message for the `release notes` section?

@joyqvq could you have a quick look to see if this works as initially intended?

**Comment by joyqvq** [comment]
curious why do you need this cli ? while im ok with this change to make it more resilient, this is for our testing scaffolding to work, but it only works for devnet or localnet.

**Review by joyqvq — APPROVED** [review]

**Comment by bityoume** [comment]
> curious why do you need this cli ? while im ok with this change to make it more resilient, this is for our testing scaffolding to work, but it only works for devnet or localnet.

@joyqvq Because I am writing an introductory article about the SUI CLI, so I am trying out each command :)

**Comment by bityoume** [comment]
> Thanks @bityoume. Can you also add a descriptive message for the `release notes` section?
> 
> @joyqvq could you have a quick look to see if this works as initially intended?

@stefan-mysten I have already added a descriptive message for the release notes section, is that ok?

**Comment by stefan-mysten** [comment]
Looks good, thanks @bityoume!

**Pull request merged**
