### PR TITLE
[test-utils] Inject additional genesis objects for test cluster.

### PR DESCRIPTION
**Pull request by amnn**
## Description 

Adds the ability to add or replace genesis objects for tests that use `TestCluster` or `Swarm`.

## Test Plan 

New tests confirming new objects can be read, and this functionality can be used to replace genesis packages:

```
sui/crates/test-utils$ cargo simtest
```

### CODE REVIEW

**Comment by bmwill** [comment]
What's the main motivation behind this and is there potentially another way to achieve what you want? I was sort of hoping that we could be eliminated this feature as a whole instead of making it more prevalent. In particular I'm planning on ensuring this functionality is completely disabled and impossible to use for future testnet and mainnet genesises.

**Comment by amnn** [comment]
It's to test framework upgrades, where the validator is detecting the need for an upgrade by checking whether the digest of the framework in the store differs from the digest for the framework it has built into its binary.  My plan was to replace the sui framework in genesis with one that can be upgraded to with the framework in the binary, so this is only intended for test, I don't think this conflicts with your aim for making this impossible for testnet/mainnet geneses.

**Comment by mystenmark** [comment]
> What's the main motivation behind this and is there potentially another way to achieve what you want? I was sort of hoping that we could be eliminated this feature as a whole instead of making it more prevalent. In particular I'm planning on ensuring this functionality is completely disabled and impossible to use for future testnet and mainnet genesises.

@bmwill Hopefully you can live with this for now, its required for testing framework upgrades. We can do whatever needs to be done to prevent this in mainnet/testnet, we only need this exposed for tests.

**Review by bmwill — APPROVED** [review]
Yeah i'm good with this, I have another idea/way to achieve what we want for genesis of non-test networks

**Pull request merged**
