### PR TITLE
[refactor] introduce an LRU cache inside certificate store

### PR DESCRIPTION
**Pull request by akichidis**
## Description 

This PR is introducing an LRU cache in the certificate_store in order to minimise the impact from the read operations (only on the primary index at the moment). That will help:
* reduce the number of reads against rocksdb
* avoid deserialisation costs of Certificate 

relevant metrics for cache hit/miss have been added.

The cache has been set to hold 100 * 60 items (100 nodes X 60 rounds) - but we can tune further. Also, we only populate the cache when we write a certificate - especially for the cases we are interested I don't consider we need to re-populate on read.

## Test Plan 

Added unit tests

---
If your changes are not user-facing and not a breaking change, you can skip the following section. Otherwise, please indicate what changed, and then add to the Release Notes section as highlighted during the release process.

### Type of Change (Check all that apply)

- [ ] user-visible impact
- [ ] breaking change for a client SDKs
- [ ] breaking change for FNs (FN binary must upgrade)
- [ ] breaking change for validators or node operators (must upgrade binaries)
- [ ] breaking change for on-chain data layout
- [ ] necessitate either a data wipe or data migration

### CODE REVIEW

**Review by kchalkias — COMMENTED** [review]
In some other uses of LRU we had a wrapper over the lru dependency. Shall we reuse that logic here as a template? ie check this PR
https://github.com/MystenLabs/sui/pull/9056

*maybe @mystenmark and @benr-ml who did that before can provide more intel on this (ie we use this for metrics etc)

**Review by kchalkias — COMMENTED** [review]
Check this LRU pattern from @benr-ml as well
https://github.com/MystenLabs/sui/pull/9712

**Review by arun-koshy — APPROVED** [review]
Nice addition Tasos! 🚀

**Review by mwtian — COMMENTED** [review]
I think adding a data structures that keeps certificates above GC round consistently should not be much more complex. If we add that in future, do you think we still need the cache?

**Comment by akichidis** [comment]
> I think adding a data structures that keeps certificates above GC round consistently should not be much more complex. If we add that in future, do you think we still need the cache?

@mwtian let's talk more about what you have in mind because for sure I can see other alternatives than this cache. I would still prefer adding this for the time being so we get some gains and we can always remove it later as it's not too invasive. What do you think?

**Pull request merged**
