### PR TITLE
Update proof-of-stake.md

### PR DESCRIPTION
**Pull request by econmysten**
added links and fixed typos

### CODE REVIEW

**Review by Clay-Mysten — APPROVED** [review]
I saw no Committees subsection under Validators and so Links to Quorums instead

**Comment by econmysten** [comment]
this is the committee section

**Review by Clay-Mysten — COMMENTED** [review]
This was replaced in:
https://github.com/MystenLabs/sui/commit/54ed9596542d85e3802470f55d98f66f02ca8693

Also note the extra space before closing parenthesis.

**Comment by Clay-Mysten** [comment]
Just noting you saw that committees section doesn't exist.

**Comment by econmysten** [comment]
did see that -- why was it removed?

**Comment by econmysten** [comment]
ok asking alberto what happened

**Pull request merged**
