### PR TITLE
RegEx for account_index in derivation path

### PR DESCRIPTION
**Pull request by Riyuk-04**
- Changing the regex to incorporate variable account_index as mentioned in [https://sui.io/resources-sui/cryptography-in-sui-wallet-specifications/](url)

### CODE REVIEW

**Review by joyqvq — APPROVED** [review]
thanks for catching!

**Review by joyqvq — CHANGES_REQUESTED** [review]
run pnpm changeset

**Comment by Riyuk-04** [comment]
Changeset created

**Comment by joyqvq** [comment]
maybe a rebase to main? the package lock json diff seems not needed

**Review by asonnino — APPROVED** [review]

**Review by joyqvq — APPROVED** [review]

**Review by huitseeker — APPROVED** [review]

**Pull request merged**
