### PR TITLE
Note verbose messaging for failed builds

### PR DESCRIPTION
**Pull request by Clay-Mysten**

### CODE REVIEW

**Comment by awelc** [comment]
I think that the proposed change wouldn't hurt, but the gist of the problem is that people don't know what do to with a message they get when trying to publish a package. I would then suggest adding something similar to the following at the end of the "publish-packages" section (https://github.com/MystenLabs/sui/blob/main/doc/src/contribute/cli-client.md#publish-packages):

```
> **Important:** In case publishing attempt results in an error regarding verification failure, please try to [build your package
> locally](https://github.com/MystenLabs/sui/blob/main/doc/src/build/move/build-test.md#building-a-package) (using `sui
> move build` command) to get a more verbose verifier error message.
```

Please not that the blurb above already uses markup formatting we normally use for the "important" boxes.

**Comment by Clay-Mysten** [comment]
> I think that the proposed change wouldn't hurt, but the gist of the problem is that people don't know what do to with a message they get when trying to publish a package. I would then suggest adding something similar to the following at the end of the "publish-packages" section (https://github.com/MystenLabs/sui/blob/main/doc/src/contribute/cli-client.md#publish-packages):
> 
> ```
> > **Important:** In case publishing attempt results in an error regarding verification failure, please try to [build your package
> > locally](https://github.com/MystenLabs/sui/blob/main/doc/src/build/move/build-test.md#building-a-package) (using `sui
> > move build` command) to get a more verbose verifier error message.
> ```
> 
> Please not that the blurb above already uses markup formatting we normally use for the "important" boxes.

Thanks for the suggested language, @awelc ! Please see this PR when you get a chance:
https://github.com/MystenLabs/sui/pull/4282

**Comment by Clay-Mysten** [comment]
@awelc just let me know if I should merge or revert this. Thanks!

**Review by bhenhsi — APPROVED** [review]

**Comment by Clay-Mysten** [comment]
Since this was done in devnet, I'm closing in favor of this PR in main:
https://github.com/MystenLabs/sui/pull/4301

**Pull request closed without merging**
