### PR TITLE
[sdk] Fix nested type parsing in TypeTag

### PR DESCRIPTION
**Pull request by kklas**
I've fixed the parsing of nested types in TypeTag ([this comment](https://github.com/MystenLabs/sui/blob/main/sdk/typescript/src/signers/txn-data-serializers/type-tag-serializer.ts#L62-L63)). Also implemented a `tagToString` function which does the oposite of `parseFromStr` (converts `TagType` -> `string`)

NOTE: I've removed `normalizeSuiAddress` from address field parsing in `parseFromString` because I don't think this is the right place to use it (`0x2::sui::SUI` becomes `{ address: 0x000000...00002::sui::SUI, ...}`). Especially because the RPC should support both https://github.com/MystenLabs/sui/pull/6777:
> For RPC requests, people should be able to pass either way as long as it's supported by parse_sui_struct_tag.

Changes:
- fixed parsing of nested struct types
- added `parseFromString` function
- made `TypeTagParser` methods static
- exported TypeTagParser in `index.ts`
- removed `normalizeSuiAddress` from parsing struct type address field

Test plan -- added unit tests.

### CODE REVIEW

**Review by 666lcz — APPROVED** [review]
Great work! Thank you for your contribution

**Comment by Pooh0203** [comment]
I like ur project

**Review by 666lcz — CHANGES_REQUESTED** [review]
@kklas I noticed that this change has broken some end to end tests. Do you mind following the instructions in https://github.com/MystenLabs/sui/tree/main/sdk/typescript#testing to repro locally and fix the test?

**Comment by Ahmedpooh** [comment]
I wouldn't mind On the contrary, very excited about it I want to work with you, I am convinced of your project

**Review by Ahmedpooh — COMMENTED** [review]
commit.

11374d2

**Comment by Ahmedpooh** [comment]
commit.

11374d2

**Comment by kklas** [comment]
@666lcz The test failures were (unsurprisingly) due to removal of `normalizeSuiAddress` due to I suspect
- the rpc backend expects normalized addresses
- rpc-txn-data-serializer normalizes addresses and comparison with local serializer fails
- dryRun normalizes and comparison fails

I still feel like `normalizeSuiAddress` is a crutch in this context so I've made it an optional arg. It should probably be removed once the code is refactored to support short addresses.

**Comment by Ahmedpooh** [comment]
I like ur job

**Comment by Ahmedpooh** [comment]
And like ur work

**Review by 666lcz — APPROVED** [review]
Thanks for fixing the test!

**Comment by Ahmedpooh** [comment]
#7055

**Pull request merged**
