### PR TITLE
Release memory used for historical items

### PR DESCRIPTION
**Pull request by mystenmark**

### CODE REVIEW

**Review by velvia — APPROVED** [review]
LGTM although this doesn't explain why the memory shoots up when a validator is restarted (as the stream would not load old historical items... would it?)

**Comment by mystenmark** [comment]
> LGTM although this doesn't explain why the memory shoots up when a validator is restarted (as the stream would not load old historical items... would it?)

It could actually - gossip and node sync starts at seq 0 until it records a later starting point in the follower db

**Comment by lxfind** [comment]
Not sure if I understand this. In the `else` case, the `items` is empty, right? Why would re-assigning it release any memory?

**Comment by mystenmark** [comment]
> Not sure if I understand this. In the `else` case, the `items` is empty, right? Why would re-assigning it release any memory?

It is empty, but its capacity will not be zero if it previously contained items. (At least, I assume that VecDeque never releases memory when removing items. Vec doesn't).

**Pull request merged**
