### PR TITLE
Temp disable shared_object_transaction test

### PR DESCRIPTION
**Pull request by lxfind**
The test seems to be always stuck

### CODE REVIEW

**Review by sblackshear — APPROVED** [review]

**Comment by huitseeker** [comment]
isn't this what #1601 is meant to address?

**Comment by lxfind** [comment]
> isn't this what #1601 is meant to address?

I am not sure. Maybe? It can always turn this back if it's fixed there.

**Comment by asonnino** [comment]
> > isn't this what #1601 is meant to address?
> 
> I am not sure. Maybe? It can always turn this back if it's fixed there.

No #1601  is fixing something else. But this is very strange because the test works fine on my local machine (so it is hard to debug on the CI)

**Comment by lxfind** [comment]
I can repro on my Mac. I will try to take a look

**Pull request merged**
