### PR TITLE
initital for creating Golang SDK

### PR DESCRIPTION
**Pull request by Romainua**
Let’s it would be start golang sdk for developers

### CODE REVIEW

**Comment by randall-Mysten** [comment]
@Romainua Sorry, I lost track of this one.

**Comment by Romainua** [comment]
@randall-Mysten reopened. Added Subscribe to JSON-RPC Real-Time Events

**Comment by randall-Mysten** [comment]
> @randall-Mysten reopened. Added Subscribe to JSON-RPC Real-Time Events

Thank you. I am asking some SDK folks to confirm, so it may take a couple of days to review.

**Comment by Romainua** [comment]
> > @randall-Mysten reopened. Added Subscribe to JSON-RPC Real-Time Events
> 
> Thank you. I am asking some SDK folks to confirm, so it may take a couple of days to review.

Great, thanks! If it will past I want to continue develop together.

**Comment by 666lcz** [comment]
@Romainua Thanks for the initiation. There are already a few GoLang SDK for Sui created by the community:
- https://github.com/coming-chat/go-sui-sdk
- https://github.com/block-vision/sui-go-sdk

that will welcome your contribution.

We don't want to duplicate efforts and compete with these existing community projects.

**Pull request closed without merging**
