### PR TITLE
Start tracking package lineage in analytics pipelines

### PR DESCRIPTION
**Pull request by sadhansood**
## Description 

This PR starts tracking the root package id for every package and records it under a newly added column called "root_package_id" in the package table. In future, once we have canonical package names, we could use other methods to track and record package lineage under the same column

## Test Plan 

Running locally and verifying

### CODE REVIEW

**Comment by gegaowp** [comment]
I missed some context here, why do we need to track the root package ID, is this related to package upgrading?

**Comment by bmwill** [comment]
Added @amnn since he's the expert on upgradability

**Review by amnn — COMMENTED** [review]
You should be able to do this slightly more simply, by processing the output objects in the checkpoint alone. For every output object that is a package, you can ask it for its `original_package_id`, which is the "root package id" you are tracking IIUC:

https://github.com/MystenLabs/sui/blob/5d8a8672a61a65548c39d999f341e034e38c38ff/crates/sui-types/src/move_package.rs#L472

From there, you can recover the lineage by also tracking the version of the object (which increases by one for each upgrade).

(Also nit, if it's not a big deal to change it, it would be helpful to standardise on the name of this ID -- `original_package_id` would be best for that).

**Comment by sadhansood** [comment]
> You should be able to do this slightly more simply, by processing the output objects in the checkpoint alone. For every output object that is a package, you can ask it for its `original_package_id`, which is the "root package id" you are tracking IIUC:
> 
> https://github.com/MystenLabs/sui/blob/5d8a8672a61a65548c39d999f341e034e38c38ff/crates/sui-types/src/move_package.rs#L472
> 
> From there, you can recover the lineage by also tracking the version of the object (which increases by one for each upgrade).
> 
> (Also nit, if it's not a big deal to change it, it would be helpful to standardise on the name of this ID -- `original_package_id` would be best for that).

Thanks, that was super helpful!

**Review by amnn — APPROVED** [review]
Looks great!

**Pull request merged**
