### PR TITLE
feat: decode or verify tx command

### PR DESCRIPTION
**Pull request by joyqvq**
## Description 

Rename `sui keytool decode-tx-bytes` to `sui keytool decode-or-verify-tx`. This command now can take an optional signature arg, if provided, decode the tx_data and outputs the verification result for the signature against the tx data. 

## Test Plan 

test cli output
```
╭────────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ tx     │ ╭────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮        │
│        │ │ V1 │ ╭────────────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮ │        │
│        │ │    │ │ kind       │ ╭─────────────────────────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮ │ │        │
│        │ │    │ │            │ │ ProgrammableTransaction │ ╭──────────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮ │ │ │        │
│        │ │    │ │            │ │                         │ │ inputs   │ ╭───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮ │ │ │ │        │
│        │ │    │ │            │ │                         │ │          │ │ ╭────────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮ │ │ │ │ │        │
│        │ │    │ │            │ │                         │ │          │ │ │ Object │ ╭──────────────┬───────────────────────────────────────────────────────────────────────────────────────────────────╮ │ │ │ │ │ │        │
│        │ │    │ │            │ │                         │ │          │ │ │        │ │ SharedObject │ ╭────────────────────────┬──────────────────────────────────────────────────────────────────────╮ │ │ │ │ │ │ │        │
│        │ │    │ │            │ │                         │ │          │ │ │        │ │              │ │ id                     │  0x...  │ │ │ │ │ │ │ │        │
│        │ │    │ │            │ │                         │ │          │ │ │        │ │              │ │ initial_shared_version │  0                                                            │ │ │ │ │ │ │ │        │
│        │ │    │ │            │ │                         │ │          │ │ │        │ │              │ │ mutable                │  true                                                                │ │ │ │ │ │ │ │        │
│        │ │    │ │            │ │                         │ │          │ │ │        │ │              │ ╰────────────────────────┴──────────────────────────────────────────────────────────────────────╯ │ │ │ │ │ │ │        │
│        │ │    │ │            │ │                         │ │          │ │ │        │ ╰──────────────┴───────────────────────────────────────────────────────────────────────────────────────────────────╯ │ │ │ │ │ │        │
│        │ │    │ │            │ │                         │ │          │ │ ╰────────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯ │ │ │ │ │        │
│        │ │    │ │            │ │                         │ │          │ │ ╭────────┬─────────────────────────────────────────────────────────────────────────────────────────────────╮                      │ │ │ │ │        │
│        │ │    │ │            │ │                         │ │          │ │ │ Object │ ╭──────────────────┬──────────────────────────────────────────────────────────────────────────╮ │                      │ │ │ │ │        │
│        │ │    │ │            │ │                         │ │          │ │ │        │ │ ImmOrOwnedObject │ ╭──────────────────────────────────────────────────────────────────────╮ │ │                      │ │ │ │ │        │
│        │ │    │ │            │ │                         │ │          │ │ │        │ │                  │ │  0x...  │ │ │                      │ │ │ │ │        │
│        │ │    │ │            │ │                         │ │          │ │ │        │ │                  │ │  0                                                            │ │ │                      │ │ │ │ │        │
│        │ │    │ │            │ │                         │ │          │ │ │        │ │                  │ │  xxx                        │ │ │                      │ │ │ │ │        │
│        │ │    │ │            │ │                         │ │          │ │ │        │ │                  │ ╰──────────────────────────────────────────────────────────────────────╯ │ │                      │ │ │ │ │        │
│        │ │    │ │            │ │                         │ │          │ │ │        │ ╰──────────────────┴──────────────────────────────────────────────────────────────────────────╯ │                      │ │ │ │ │        │
│        │ │    │ │            │ │                         │ │          │ │ ╰────────┴─────────────────────────────────────────────────────────────────────────────────────────────────╯                      │ │ │ │ │        │
│        │ │    │ │            │ │                         │ │          │ ╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯ │ │ │ │        │
│        │ │    │ │            │ │                         │ │ commands │ ╭──────────────────────────────────────────────────────────────────────────────────────────────────────────╮                          │ │ │ │        │
│        │ │    │ │            │ │                         │ │          │ │ ╭──────────┬───────────────────────────────────────────────────────────────────────────────────────────╮ │                          │ │ │ │        │
│        │ │    │ │            │ │                         │ │          │ │ │ MoveCall │ ╭────────────────┬──────────────────────────────────────────────────────────────────────╮ │ │                          │ │ │ │        │
│        │ │    │ │            │ │                         │ │          │ │ │          │ │ package        │  0x...  │ │ │                          │ │ │ │        │
│        │ │    │ │            │ │                         │ │          │ │ │          │ │ module         │  xxx                                               │ │ │                          │ │ │ │        │
│        │ │    │ │            │ │                         │ │          │ │ │          │ │ function       │  xxx                                                                │ │ │                          │ │ │ │        │
│        │ │    │ │            │ │                         │ │          │ │ │          │ │ type_arguments │                                                                      │ │ │                          │ │ │ │        │
│        │ │    │ │            │ │                         │ │          │ │ │          │ │ arguments      │ ╭─────────────────╮                                                  │ │ │                          │ │ │ │        │
│        │ │    │ │            │ │                         │ │          │ │ │          │ │                │ │ ╭───────┬─────╮ │                                                  │ │ │                          │ │ │ │        │
│        │ │    │ │            │ │                         │ │          │ │ │          │ │                │ │ │ Input │  0  │ │                                                  │ │ │                          │ │ │ │        │
│        │ │    │ │            │ │                         │ │          │ │ │          │ │                │ │ ╰───────┴─────╯ │                                                  │ │ │                          │ │ │ │        │
│        │ │    │ │            │ │                         │ │          │ │ │          │ │                │ │ ╭───────┬─────╮ │                                                  │ │ │                          │ │ │ │        │
│        │ │    │ │            │ │                         │ │          │ │ │          │ │                │ │ │ Input │  1  │ │                                                  │ │ │                          │ │ │ │        │
│        │ │    │ │            │ │                         │ │          │ │ │          │ │                │ │ ╰───────┴─────╯ │                                                  │ │ │                          │ │ │ │        │
│        │ │    │ │            │ │                         │ │          │ │ │          │ │                │ ╰─────────────────╯                                                  │ │ │                          │ │ │ │        │
│        │ │    │ │            │ │                         │ │          │ │ │          │ ╰────────────────┴──────────────────────────────────────────────────────────────────────╯ │ │                          │ │ │ │        │
│        │ │    │ │            │ │                         │ │          │ │ ╰──────────┴───────────────────────────────────────────────────────────────────────────────────────────╯ │                          │ │ │ │        │
│        │ │    │ │            │ │                         │ │          │ ╰──────────────────────────────────────────────────────────────────────────────────────────────────────────╯                          │ │ │ │        │
│        │ │    │ │            │ │                         │ ╰──────────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯ │ │ │        │
│        │ │    │ │            │ ╰─────────────────────────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯ │ │        │
│        │ │    │ │ sender     │  0x...                                                                                                                │ │        │
│        │ │    │ │ gas_data   │ ╭─────────┬──────────────────────────────────────────────────────────────────────────────╮                                                                                         │ │        │
│        │ │    │ │            │ │ payment │ ╭──────────────────────────────────────────────────────────────────────────╮ │                                                                                         │ │        │
│        │ │    │ │            │ │         │ │ ╭──────────────────────────────────────────────────────────────────────╮ │ │                                                                                         │ │        │
│        │ │    │ │            │ │         │ │ │  0x...  │ │ │                                                                                         │ │        │
│        │ │    │ │            │ │         │ │ │  0                                                            │ │ │                                                                                         │ │        │
│        │ │    │ │            │ │         │ │ │  xxx                        │ │ │                                                                                         │ │        │
│        │ │    │ │            │ │         │ │ ╰──────────────────────────────────────────────────────────────────────╯ │ │                                                                                         │ │        │
│        │ │    │ │            │ │         │ ╰──────────────────────────────────────────────────────────────────────────╯ │                                                                                         │ │        │
│        │ │    │ │            │ │ owner   │  0x...          │                                                                                         │ │        │
│        │ │    │ │            │ │ price   │  0                                                                         │                                                                                         │ │        │
│        │ │    │ │            │ │ budget  │  0                                                                  │                                                                                         │ │        │
│        │ │    │ │            │ ╰─────────┴──────────────────────────────────────────────────────────────────────────────╯                                                                                         │ │        │
│        │ │    │ │ expiration │  None                                                                                                                                                                              │ │        │
│        │ │    │ ╰────────────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯ │        │
│        │ ╰────┴─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯        │
│ result │ ╭─────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮ │
│        │ │ Err │ ╭─────────────────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮ │ │
│        │ │     │ │ IncorrectSigner │ ╭───────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮ │ │ │
│        │ │     │ │                 │ │ error │  Incorrect signer, expected 0x..., got 0x...  │ │ │ │
│        │ │     │ │                 │ ╰───────┴─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯ │ │ │
│        │ │     │ ╰─────────────────┴─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯ │ │
│        │ ╰─────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯ │
╰────────┴─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

```
---
If your changes are not user-facing and do not break anything, you can skip the following section. Otherwise, please briefly describe what has changed under the Release Notes section.

### Type of Change (Check all that apply)

- [ ] protocol change
- [x] user-visible impact
- [ ] breaking change for a client SDKs
- [ ] breaking change for FNs (FN binary must upgrade)
- [ ] breaking change for validators or node operators (must upgrade binaries)
- [ ] breaking change for on-chain data layout
- [ ] necessitate either a data wipe or data migration

### Release notes
Rename `sui keytool decode-tx-bytes` to `sui keytool decode-or-verify-tx`. This command now can take an optional signature arg, if provided, decode the tx_data and outputs the verification result for the signature against the tx data.

### CODE REVIEW

**Review by stefan-mysten — COMMENTED** [review]
This looks overall ok, just wanted to double check that we're ok breaking existing commands. How many folks you estimate are using this command?

**Comment by joyqvq** [comment]
> This looks overall ok, just wanted to double check that we're ok breaking existing commands. How many folks you estimate are using this command?

this is a debug command not on the execution path to break any existing flows. its not removing the previous functionality but to add an additional arg so it does more, although there is a rename

**Review by stefan-mysten — APPROVED** [review]

**Comment by stefan-mysten** [comment]
> > This looks overall ok, just wanted to double check that we're ok breaking existing commands. How many folks you estimate are using this command?
> 
> this is a debug command not on the execution path to break any existing flows. its not removing the previous functionality but to add an additional arg so it does more, although there is a rename

In general, I think it is a good practice to avoid renaming existing commands, unless we do a proper refactoring and we rename more than just one command at a time, such that we have a big breaking change at once, rather than incrementally. 

Accepting to unblock.

**Comment by stefan-mysten** [comment]
> > In general, I think it is a good practice to avoid renaming existing commands, unless we do a proper refactoring and we rename more than just one command at a time, such that we have a big breaking change at once, rather than incrementally.
> 
> This is marked as user impact and highlighted in the release note. is it sufficient or you want to old command and its function to be marked as deprecated only?

All good, LGTM!

**Pull request merged**
