### PR TITLE
Address post-merge comments from 2106

### PR DESCRIPTION
**Pull request by mystenmark**
#2106

### CODE REVIEW

**Comment by lxfind** [comment]
What's the reason to add a QueryHelpers instead of implementing them in the store?

**Comment by mystenmark** [comment]
> What's the reason to add a QueryHelpers instead of implementing them in the store?

mainly because it would require making AuthorityState::database public which I don't feel good about. It also didn't feel appropriate to be checking API errors (e.g. `MAX_TX_RANGE_SIZE`) in authority_store.rs

**Comment by lxfind** [comment]
So for future reference, what kind of functions should go to QueryHelpers?

**Comment by mystenmark** [comment]
> So for future reference, what kind of functions should go to QueryHelpers?

I think anything that needs to be shared between GatewayState and AuthorityState. But since the plan is to phase out the gateway (at least the read-only parts), that part of GatewayState should actually go away entirely and the code can be moved back into AuthorityState, and QueryHelpers deleted. Sound good? I can leave a comment in the code to that effect if you agree.

**Review by lxfind — APPROVED** [review]

**Pull request merged**
