### PR TITLE
[frenemies] Migrate and fix leaderboard limit issues

### PR DESCRIPTION
**Pull request by amnn**
- Duplicate `frenemies` into `old-frenemies` and `new-frenemies`, with `new-` depending on `old-`.
- Introduce a fix for leaderboard score insertion to honour the limit.

## Test Plan

```
examples$ sui move test --path old-frenemies
examples$ sui move test --path new-frenemies --gas-limit 1000000
```

### CODE REVIEW

**Comment by arty-arty** [comment]
Could you take a look, please 😊?
I'm very curious if this is the right fix for frenemies leaderboard overflow problem :)

**Review by tzakian — APPROVED** [review]
Looks good! Thanks for the quick fix!

**Comment by amnn** [comment]
> Could you take a look, please 😊? I'm very curious if this is the right fix for frenemies leaderboard overflow problem :)
> 
> #8203

Hey @arty-arty, thanks for submitting a fix!  It doesn't quite work, the issue was not that we were using strict equality instead of an upperbound check, it was that we were not popping elements off the leaderboard when the new score being added was a new top score.  See the middle commit in this PR for the fix for that.

**Comment by arty-arty** [comment]
Hello, Ashok!

Thanks a lot for responding :)
Yes, got it, now you pop everything above the size while there is too much.
Which seems super-buletproof-safe and no way of overflow now!

Just wanted to fix the invariant and have some math satisfaction) And
screwed it by forgetting to pop :( I felt something was wrong. And hit
commit second time just at the same time your mail arrived :))

Wishing all the best,
Arthem

**Pull request merged**
