### PR TITLE
Fix posting benchmark results

### PR DESCRIPTION
**Pull request by mwtian**
Currently CI fails on posting benchmark results, e.g. https://github.com/MystenLabs/sui/actions/runs/3629560587/jobs/6121910430#step:8:15. This PR tries to fix the way benchmark outputs are filtered and escaped, so legible benchmark results can be displayed.

Also, we have not been running Narwhal benchmarks for awhile. Add Narwhal benchmark to the CI workflow.

### CODE REVIEW

**Review by huitseeker — COMMENTED** [review]
This looks promising overall! did you have an occasion to run a test (perhaps on a fork of the repo, adding a manual trigger?)

**Comment by mwtian** [comment]
Running tests right now, e.g.
- comment: https://github.com/MystenLabs/sui/commit/39b25f5bc8bcdfe617c476af7b75db41772e83ab#commitcomment-92212348
- benchmark: https://github.com/MystenLabs/sui/actions/runs/3632863985/jobs/6129202098

Somehow newlines are still lost somewhere. Planning to timebox the investigation.

**Comment by mwtian** [comment]
The output looks acceptable to me now. PTAL.
https://github.com/MystenLabs/sui/commit/cef76c9e17217a29107db52b66c4cce90886b63e#commitcomment-92218247

**Review by arun-koshy — APPROVED** [review]
Thanks for fixing this!

**Pull request merged**
