### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by rex4539**

### CODE REVIEW

**Comment by rex4539** [comment]
Rebased to fix conflict

**Comment by rex4539** [comment]
Rebased to fix conflicts

**Review by randall-Mysten — APPROVED** [review]
Awesome, thanks for making all of these updates!

**Comment by randall-Mysten** [comment]
@bmwill These look good to me. Deferring approval to an engineer.

**Comment by rex4539** [comment]
Rebased to fix conflict

**Comment by bmwill** [comment]
@rex4539 sorry i didn't see this till now, i've triggered CI to run but it looks like there's another conflict that needs to be resolved, once that's done we'll get this in.

**Comment by rex4539** [comment]
Rebased

**Comment by rex4539** [comment]
I think I may have fixed one of the build errors.

**Pull request merged**
