### PR TITLE
Sui JSON support optional input

### PR DESCRIPTION
**Pull request by patrickkuo**
a fix to enable optional input via sui json.

example:

`call --package 0x2 --module sui_system --function request_add_delegation_mul_coin --args 0x5 [0x75a556740fb6e45219b1069ca08143ab086e9283, 0x907ae3c07cba82c26e363097e56f2aa0837547c2, 0xcf9b1967ee44e060c36a9b93d8075a0ccefce803] [200000000000000] 0x0879e3ec427b091fc22c1f765fdec22ea71a2150 --gas-budget 10000` 

We are using array to represent optional values, empty array `[]` indicate None.

### CODE REVIEW

**Review by sblackshear — APPROVED** [review]
LGTM, thanks!

**Review by awelc — CHANGES_REQUESTED** [review]
LGTM as well, but I think we should document this in https://github.com/MystenLabs/sui/blob/main/doc/src/reference/sui-json.md

**Comment by tnowacki** [comment]
Thanks! I think this solves #7142?

**Comment by patrickkuo** [comment]
> Thanks! I think this solves #7142?

Yes.

But I will revert the changes in Sui JSON and move the u64 to String magic to the CLI, the u64 String checks in Sui JSON is correct.

**Comment by patrickkuo** [comment]
Moved the u64 -> String conversion to the CLI, also added more e2e tests.

Sui Json will continue to enforce u64 String.

**Comment by patrickkuo** [comment]
> LGTM as well, but I think we should document this in https://github.com/MystenLabs/sui/blob/main/doc/src/reference/sui-json.md

I am not changing the Sui JSON u64 string enforcement logic, so don't need to change the doc.

**Comment by awelc** [comment]
> I am not changing the Sui JSON u64 string enforcement logic, so don't need to change the doc.

I was thinking of documenting how to encode `Option` in the [Type coercion rules](https://github.com/MystenLabs/sui/blob/main/doc/src/reference/sui-json.md#type-coercion-rules) section unless you can think of a better place where developers would be able to find this info.

**Comment by patrickkuo** [comment]
> > I am not changing the Sui JSON u64 string enforcement logic, so don't need to change the doc.
> 
> I was thinking of documenting how to encode `Option` in the [Type coercion rules](https://github.com/MystenLabs/sui/blob/main/doc/src/reference/sui-json.md#type-coercion-rules) section unless you can think of a better place where developers would be able to find this info.

ah! of course! will add that

**Comment by patrickkuo** [comment]
hi @awelc, does this looks ok to you?

**Review by awelc — APPROVED** [review]

**Pull request merged**
