### PR TITLE
Bumping sui version to v0.24.0

### PR DESCRIPTION
**Pull request by ebmifa**

### CODE REVIEW

**Review by 666lcz — APPROVED** [review]

**Comment by ebmifa** [comment]
@bmwill and @longbowlu I assume that 
```
output.bpl(68423,4): Error: call to undeclared procedure: $1_vector_insert'$2_voting_power_VotingPowerInfo'
output.bpl(68706,4): Error: call to undeclared procedure: $1_vector_insert'$2_voting_power_VotingPowerInfo'
```
failure in move prover is not related to this change
output.bpl(68423,4): Error: call to undeclared procedure: $1_vector_insert'$2_voting_power_VotingPowerInfo'
output.bpl(68706,4): Error: call to undeclared procedure: $1_vector_insert'$2_voting_power_VotingPowerInfo'

**Comment by lxfind** [comment]
That's a known failure and should not be blocking.

**Comment by ebmifa** [comment]
@lxfind 
What about https://github.com/MystenLabs/sui/actions/runs/4008985268/jobs/6884030133 ?

**Comment by lxfind** [comment]
Not familiar with the explorer code. @Jordan-Mysten

**Pull request merged**
