### PR TITLE
Simplify handle_batch_streaming

### PR DESCRIPTION
**Pull request by sadhansood**
This PR is an attempt to simplify how batch streaming works. Currently, the way things work is upon receiving a streaming request the server - 
1. subscribes to a broadcast channel which is being updated by batching service upon receiving an in order transaction or closing a batch (time interval or max size)
2. cap the request range `[start, end]` to `[start, min(end, start + 1000)]`. I believe this is because the way things work are not truly streaming in nature today. The function `batches_and_transactions()` will first download the entire historical batches and txns from db in memory (and hence the above cap in the request range) and then publish those to the stream
3. After realizing that `end` is larger tha max sequence txn in db, read from the broadcast stream until the end (if we are too late to drain the broadcast channel and lost events, close the stream)
4. There is also a race in function `batches_and_transactions()`when returning trailing txns could be streamed before the corresponding batch. For example, if there were trailing txns: 100,101,102,103 and corresponding batch could be for 100,101,102 and so the returned response stream could look like: t100,t101,t102,t103,b[100-102] whereas it should always be t100,t101,t102,b[100-102],t103

The new design runs a much simpler state machine to truly stream the response (with no need to download a large response in memory or worry about being too late to drain the broadcast channel):
1.  read next batch (`b`) from db
2. if found batch in step 1, stream from db all txns in `b`
3. stream `b`
5. goto step 1

### CODE REVIEW

**Comment by sadhansood** [comment]
I'd also like the folks to comment on whether if we think we even need the batch service. With post processing not using it anymore, could we perhaps just compute the `Batch` inline in handle_batch_streaming() without needing to store it in db at all? If that is the case, this thing will become even simpler in implementation.

**Comment by sadhansood** [comment]
> Wouldn't we always need some kind of Batch to make https://www.notion.so/mystenlabs/Sui-indexer-1fb39b0922834edea2aa5bcbf1ab87d1 work?

Oh forgot about the batch triggers, in that case yes we need to keep batches

**Comment by lxfind** [comment]
@mystenmark @bmwill and I chatted about this a bit, and it seems that eventually we should be able to have indexer to fully rely on checkpoints. Regardless, let me review this PR and merge it to make things simpler. And down the line once the new checkpoint is ready we may delete batches entirely

**Review by lxfind — APPROVED** [review]
Love seeing code deleted!

**Comment by sadhansood** [comment]
> @mystenmark @bmwill and I chatted about this a bit, and it seems that eventually we should be able to have indexer to fully rely on checkpoints. Regardless, let me review this PR and merge it to make things simpler. And down the line once the new checkpoint is ready we may delete batches entirely

Makes sense, looks like checkpoints are going to make things better overall. I will merge this for now, and @mystenmark if you have additional comments please feel free to leave them here and i'll handle them in a follow up pr

**Pull request merged**
