### PR TITLE
[Wallet] Fix display inconsistency for domain names when nickname is set

### PR DESCRIPTION
**Pull request by yjshi2015**
## Description 

_If a user sets a nickname in their Sui wallet and later applies for a domain name, the domain name does not display, leading to confusion about whether it is active. Additionally, there is no direct way for users to view or manage their domain name in the wallet interface. see https://github.com/MystenLabs/sui/issues/20409_

Enhanced the wallet’s domain name display logic to provide a seamless way to show domain names, even if the user has already set a nickname. The improvements are as follows:

When the user clicks “EDIT NICKNAME,” the domain name is displayed as an option, allowing the user to choose whether to display the domain name or continue using the nickname.

image

## Test plan 

1. Tested the scenario where both a nickname and a domain name are set to ensure the UI includes functionality to display either the domain name or the nickname, allowing users to switch between them.

2. Tested the scenario where only a nickname is set to verify the nickname displays correctly and the user address remains accessible.

3. Tested the scenario where neither a nickname nor a domain name is set to ensure the user address displays by default.

https://github.com/user-attachments/assets/8ffc02d8-214c-41cd-941b-286166fb17fe

## Release notes

Check each box that your changes affect. If none of the boxes relate to your changes, release notes aren't required.

For each box you select, include information after the relevant heading that describes the impact of your changes that a user might notice and any actions they must take to implement updates. 

- [ ] Protocol: 
- [ ] Nodes (Validators and Full nodes): 
- [ ] Indexer: 
- [ ] JSON-RPC: 
- [ ] GraphQL: 
- [ ] CLI: 
- [ ] Rust SDK:
- [ ] REST API:

### CODE REVIEW

**Comment by yjshi2015** [comment]
Hi @pchrysochoidis,  @mystieanwaya,  @mamos-mysten,  could you kindly review this PR when you have a chance? It addresses the issue where domain names do not display if a nickname is already set, causing user confusion. This PR implements a feature that allows users to choose between displaying their domain name or nickname when editing, improving the wallet’s usability. Thanks!

**Comment by mamos-mysten** [comment]
Hey @yjshi2015, first of all thank you for the contribution! We're current working on a major update to the extension that will be released soon. As such, we're not planning any releases for the current extension other than for critical bugfixes. 

I've made a ticket internally to track this request so that we can make sure this issue is correctly resolved with the updated version of the extension.

**Comment by yjshi2015** [comment]
> Hey @yjshi2015, first of all thank you for the contribution! We're current working on a major update to the extension that will be released soon. As such, we're not planning any releases for the current extension other than for critical bugfixes.
> 
> I've made a ticket internally to track this request so that we can make sure this issue is correctly resolved with the updated version of the extension.

Very much looking forward to the new release!

**Comment by yjshi2015** [comment]
> Hey @yjshi2015, first of all thank you for the contribution! We're current working on a major update to the extension that will be released soon. As such, we're not planning any releases for the current extension other than for critical bugfixes.
> 
> I've made a ticket internally to track this request so that we can make sure this issue is correctly resolved with the updated version of the extension.

Very much looking forward to the new release!

**Pull request closed without merging**
