### PR TITLE
[cli] Fix cli client publish path

### PR DESCRIPTION
**Pull request by stefan-mysten**
## Description 

Fixes the issue with providing a path to a Move project with `sui client publish <path>`, and failing to find the directory.

## Test plan 

Existing tests. Manual checks
```bash
~/src/sui/examples > sui client publish move/first_package 
~/src/sui/examples/move > sui client publish first_package 
~/src/sui/examples/move/first_package > sui client publish . 
```
---

## Release notes

Check each box that your changes affect. If none of the boxes relate to your changes, release notes aren't required.

For each box you select, include information after the relevant heading that describes the impact of your changes that a user might notice and any actions they must take to implement updates. 

- [ ] Protocol: 
- [ ] Nodes (Validators and Full nodes): 
- [ ] Indexer: 
- [ ] JSON-RPC: 
- [ ] GraphQL: 
- [ ] CLI: 
- [ ] Rust SDK:

### CODE REVIEW

**Review by amnn — APPROVED** [review]
Thanks for fixing this @stefan-mysten! Could you explain how the fix works? In particular, where the CLI was trying to access the path from that the non-canonical path didn't work?

I believe that at some point in the build process, we effectively `cd` into the project directory so that tools can rely on the current working directory being the project directory, so this fix suggests to me that some part of the process is still trying to access the package at its relative path, after `cd`-ing into it, which is what is causing the problem, an I'd like to understand which part that is, and whether we should be fixing that instead.

**Comment by stefan-mysten** [comment]
> Thanks for fixing this @stefan-mysten! Could you explain how the fix works? In particular, where the CLI was trying to access the path from that the non-canonical path didn't work?
> 
> I believe that at some point in the build process, we effectively `cd` into the project directory so that tools can rely on the current working directory being the project directory, so this fix suggests to me that some part of the process is still trying to access the package at its relative path, after `cd`-ing into it, which is what is causing the problem, an I'd like to understand which part that is, and whether we should be fixing that instead.

Somehow, after cd-ing in the folder, the package path is still passed to some other functions, but now we're effectively in that folder. So for example, if we're passing `first_package` as the path where the project is, then at some point it changes the cwd to this folder, and then later it still passes the package_path to some other calls, which now fails because they cannot find a `first_package/first_package` folder.

**Comment by stefan-mysten** [comment]
> > Thanks for fixing this @stefan-mysten! Could you explain how the fix works? In particular, where the CLI was trying to access the path from that the non-canonical path didn't work?
> > I believe that at some point in the build process, we effectively `cd` into the project directory so that tools can rely on the current working directory being the project directory, so this fix suggests to me that some part of the process is still trying to access the package at its relative path, after `cd`-ing into it, which is what is causing the problem, an I'd like to understand which part that is, and whether we should be fixing that instead.
> 
> Somehow, after cd-ing in the folder, the package path is still passed to some other functions, but now we're effectively in that folder. So for example, if we're passing `first_package` as the path where the project is, then at some point it changes the cwd to this folder, and then later it still passes the package_path to some other calls, which now fails because they cannot find a `first_package/first_package` folder.

@amnn figured out where this issue comes from: https://github.com/MystenLabs/sui/blob/main/crates/sui/src/client_commands.rs#L889C1-L889C98

The current folder is changed if no `--lock-file` is passed (which is not an option, it's set to `clap(skip)`, then the line above will use `package_path`, while already being in that folder, so it fails. 

I see two ways to fix this: 
- the one I already did, which will pass the right package path to `compile_package` function call and to this call https://github.com/MystenLabs/sui/blob/main/crates/sui/src/client_commands.rs#L889C1-L889C98
- add this code in both `compile_package` and in this `if let SuiClientCommandresult::TransactionBlock` code block
```
                    let package_path = if build_config.lock_file.is_some() {
                        package_path
                    } else {
                        std::path::Path::new(".").to_path_buf()
                    };
```

**Comment by stefan-mysten** [comment]
cc @rvantonder might be related to some work you're doing, so just an FYI.

**Comment by nikos-kitmeridis** [comment]
Hi @stefan-mysten, after upgrading locally to 1.29, I am getting impacted by this change.
This command that used to work 
```
sui client publish --skip-fetch-latest-git-deps --skip-dependency-verification --with-unpublished-dependencies --gas-budget 2000000000 --json ./test_token
```
now requires the full path of the `test_token` dir otherwise it throws the following error:
```
Failed to publish the Move module(s), reason: Failed to canonicalize package path: No such file or directory (os error 2)
```
Is this expected?

**Comment by stefan-mysten** [comment]
Hey @nikos-kitmeridis 

That's interesting. From my knowledge, the publish command was not changed in any way that I know of. Maybe it might have been touched by @rvantonder in some of the automated address management work he was doing.

**Comment by nikos-kitmeridis** [comment]
> From my knowledge, the publish command was not changed in any way that I know of.
Aren't the lines 940-945 from this PR's changed file a change in the publish command?

**Comment by stefan-mysten** [comment]
Yes, this PR tries to fix the case when a relative path is given, for which the command was failing before.

**Comment by rvantonder** [comment]
@nikos-kitmeridis @stefan-mysten fix here: https://github.com/MystenLabs/sui/pull/18531

(@nikos-kitmeridis the regression happened in a more recent PR, unrelated to this one, but which reordered the statements made in this PR)

**Comment by stefan-mysten** [comment]
Thanks @rvantonder for fixing this. If I would have added a test before, probably we wouldn't have gotten into this situation. Sorry for that :(

**Pull request merged**
