### PR TITLE
[explorer]: remove blue background for logos

### PR DESCRIPTION
**Pull request by plam-ml**
## Description 

- Remove gradient background, unless it is for the fallback plain text
- https://mysten.atlassian.net/browse/APPS-779

Screenshot 2023-04-13 at 6 05 50 PM

## Test Plan 

How did you test the new or updated feature?

---
If your changes are not user-facing and not a breaking change, you can skip the following section. Otherwise, please indicate what changed, and then add to the Release Notes section as highlighted during the release process.

### Type of Change (Check all that apply)

- [ ] user-visible impact
- [ ] breaking change for a client SDKs
- [ ] breaking change for FNs (FN binary must upgrade)
- [ ] breaking change for validators or node operators (must upgrade binaries)
- [ ] breaking change for on-chain data layout
- [ ] necessitate either a data wipe or data migration

### CODE REVIEW

**Review by mystie711 — APPROVED** [review]

**Comment by williamrobertson13** [comment]
image

@mystie711 how do we want to handle validators who have white logos? also, @plam-ml I think we might want to add `object-fit-contain` to the avatar images because several validators didn't use correctly sized images

**Comment by mystie711** [comment]
> > image
> > @mystie711 how do we want to handle validators who have white logos? also, @plam-ml I think we might want to add `object-fit: contain` to the avatar images because several validators didn't use correctly sized images
> 
> Thanks for catching this @williamrobertson13! Is there any magic possible...where if the logo only has white color then we use the blue gradient? If not, then let's use our #grey-40 as background color for all validators with logo asset available.

Btw, we need to also apply these rules for Wallet as well. The validator icons show up in Staking flows.

**Comment by plam-ml** [comment]
Added `object-fit: contain` and update bg color to `gray40`. Pls review again @williamrobertson13

**Review by williamrobertson13 — APPROVED** [review]
lgtm!

**Pull request merged**
