### PR TITLE
Switch to Clap. Bump Move version

### PR DESCRIPTION
**Pull request by tnowacki**
- Switch from structopt to clap v3
- Bump Move version

### CODE REVIEW

**Comment by tnowacki** [comment]
The Move repo recently switched from structopt to clap v3. Some crates in Sui were still using both. 

After Clap 3.1.8, I was able to switch to clap with the new version of `arg_enum`

**Comment by tnowacki** [comment]
The codecov /patch and /roject passes are "failing", what do I do to resolve that?

**Comment by oxade** [comment]
@tnowacki cool change
But why did we make this change? What are the benefits?

**Comment by tnowacki** [comment]
>@tnowacki cool change
But why did we make this change? What are the benefits?

structopt uses clap, but structopt is more or less unnecessary for our usages after clap v3. All of the proc macros that structopt has are integrated in clap after 3.0

**Comment by oxade** [comment]
> > @tnowacki cool change
> > But why did we make this change? What are the benefits?
> 
> structopt uses clap, but structopt is more or less unnecessary for our usages after clap v3. All of the proc macros that structopt has are integrated in clap after 3.0

Great to know! thanks

**Pull request merged**
