### PR TITLE
update Sui GraphQL Examples Errors

### PR DESCRIPTION
**Pull request by cczufish**
## Description 

update Sui GraphQL Examples Errors

Cannot query field “address” on Type Address
address -> location : SuiAddress! 

Cannot query field “type” on Type Event
sendingModule -> sendingModuleId

Cannot query field “address” on Type Object
address -> location : SuiAddress! 

Field "type" is not defined by type "ObjectFilter". Did you mean "ty"?
type  ->  ty 

Cannot query field "address" on type "ObjectOwner

Cannot query field "defaultPageSize" on type "ServiceConfig". Did you mean'maxPageSize"?

Field "signatures" of type "[TransactionSignature]" must have a selection of subfields. Didyou mean "signatures { ... ]"?

Cannot query field "commitTimestamp" on type "ConsensusCommitPrologueTransaction"
Did you mean "timestamp"?

Cannot query field "consensusCommitDigest" on type'ConsensusCommitPrologueTransaction"

Cannot query field "objectConnection" on type "GenesisTransaction"

### CODE REVIEW

**Review by wlmyng — CHANGES_REQUESTED** [review]
This doesn't look right to me. If you build graphql-rpc from main, or run any tests locally, you will see that the existing examples are correct.

**Comment by cczufish** [comment]
> This doesn't look right to me. If you build graphql-rpc from main, or run any tests locally, you will see that the existing examples are correct.

https://graphql-beta.mainnet.sui.io

**Comment by cczufish** [comment]
> This doesn't look right to me. If you build graphql-rpc from main, or run any tests locally, you will see that the existing examples are correct.

https://docs.sui.io/references/sui-api/beta-graph-ql#using-sui-graphql-rpc That means you need to update the links here, hahaha

**Comment by wlmyng** [comment]
> > This doesn't look right to me. If you build graphql-rpc from main, or run any tests locally, you will see that the existing examples are correct.
> 
> https://docs.sui.io/references/sui-api/beta-graph-ql#using-sui-graphql-rpc That means you need to update the links here, hahaha

I think you identify a pain point where someone would expect the repo's examples to work against the deployed service, but because the examples are on main and the deployed service is on another commit, there may potentially be some discrepancies. I think a quick workaround would be to just link to the repo at the commit in our docs, until we figure out a stronger versioning story.

In any case, it doesn't make sense to revert the changes to the examples on main.

**Comment by wlmyng** [comment]
https://github.com/MystenLabs/sui/pull/15334

**Comment by amnn** [comment]
Thanks for the report @cczufish !  As the link has now been updated in the docs, I'll close it, because as @wlmyng, we want to be able to keep the examples in `main` up-to-date with the implementation in `main`.

**Pull request closed without merging**
