### PR TITLE
Replace saturating_add(1) with checked_add(1).unwrap()

### PR DESCRIPTION
**Pull request by mystenmark**

### CODE REVIEW

**Review by lxfind — COMMENTED** [review]
If you are just going to unwrap, why checked_add, instead of just +1?

**Review by longbowlu — APPROVED** [review]
Is there a legit use case for `saturating_add` in this repo?

**Comment by longbowlu** [comment]
> If you are just going to unwrap, why checked_add, instead of just +1?

one diff is +1 does not panic by default in debug build

**Comment by mystenmark** [comment]
> Is there a legit use case for `saturating_add` in this repo?

Sure. Here's one: https://github.com/MystenLabs/sui/blob/d6a9015f16050ad1a00906f0c4914dc9d4347384/crates/sui-network/src/discovery/mod.rs#L465

**Comment by mystenmark** [comment]
> If you are just going to unwrap, why checked_add, instead of just +1?

As Lu said, in a release build that would overflow back to 0 for unsigned types, or cause UB for signed types.

**Review by lxfind — APPROVED** [review]

**Pull request merged**
