### PR TITLE
Randomize object IDs for better random test coverage

### PR DESCRIPTION
**Pull request by mystenmark**
Follow up to https://github.com/MystenLabs/sui/pull/6467

### CODE REVIEW

**Comment by andll** [comment]
Can you explain little bit more how this work? Why putting the objects into thread local make them more random?

**Comment by mystenmark** [comment]
> Can you explain little bit more how this work? Why putting the objects into thread local make them more random?

Putting them in thread local doesn't make them more random - using ObjectID::random() makes them more random. They are in thread_locals because existing tests assum they can call these methods and receive the same output every time. The thread_local caches the results for the duration of the tests, while allowing different execution from one test run to the next.

**Review by andll — APPROVED** [review]
Ok, got it

**Comment by andll** [comment]
I guess one worry I still have is that this is going in direction of making tests *more* flaky, e.g. if there is some race condition it will show up in same tests and not all.

**Comment by mystenmark** [comment]
> Maybe random generator there can make use of some fixed seed, so that failure can be reproduced? And then this seed is random (and printed) for usual runs, but also can be set with environment variable? [or is this already what is happening in msim?]

Precisely! Here's my test run with this code, but without @amnn's fix, which fails after some number of iterations:

```
[ mlogan@MARKs-MacBook-Pro ( 2:57PM) ~/dev/sui/crates/sui  <err: 100>63e4918ae ]
; MSIM_TEST_NUM=20  RUST_LOG=none cargo simtest shared_object_sync
    Updating git repository `https://github.com/mystenmark/hyper-madsim-fork.git`
    Updating git repository `https://github.com/MystenLabs/mysten-sim.git`
    Finished simulator [optimized + debuginfo] target(s) in 1.21s
    Starting 1 tests across 10 binaries (72 skipped)
        FAIL [  14.560s]           sui::shared_objects_tests shared_object_sync

--- STDOUT:                        sui::shared_objects_tests shared_object_sync ---

running 1 test
note: run with `MSIM_TEST_SEED=3400027067477071008` environment variable to reproduce this error
test shared_object_sync ... FAILED

failures:

failures:
    shared_object_sync

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 5 filtered out; finished in 14.51s


--- STDERR:                        sui::shared_objects_tests shared_object_sync ---
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: TransactionInputObjectsErrors { errors: [SharedObjectPriorVersionsPendingExecution { object_id: 0x1aa7479acb9f52c00137bf7e76eabb862c8485ab, version_not_ready: SequenceNumber(1) }] }', crates/sui/tests/shared_objects_tests.rs:288:6
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

   Canceling due to test failure: 0 tests still running
------------
     Summary [  14.562s] 1 tests run: 0 passed, 1 failed, 72 skipped
error: test run failed
Updated 1 path from the index
```

And then the deterministic reproduction:

```
[ mlogan@MARKs-MacBook-Pro ( 2:57PM) ~/dev/sui/crates/sui  <err: 100>63e4918ae ]
; MSIM_TEST_SEED=3400027067477071008 RUST_LOG=none cargo simtest shared_object_sync
Using MSIM_TEST_SEED=3400027067477071008 from the environment
    Updating git repository `https://github.com/mystenmark/hyper-madsim-fork.git`
    Updating git repository `https://github.com/MystenLabs/mysten-sim.git`
    Finished simulator [optimized + debuginfo] target(s) in 0.67s
    Starting 1 tests across 10 binaries (72 skipped)
        FAIL [   5.971s]           sui::shared_objects_tests shared_object_sync

--- STDOUT:                        sui::shared_objects_tests shared_object_sync ---

running 1 test
note: run with `MSIM_TEST_SEED=3400027067477071008` environment variable to reproduce this error
test shared_object_sync ... FAILED

failures:

failures:
    shared_object_sync

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 5 filtered out; finished in 5.96s


--- STDERR:                        sui::shared_objects_tests shared_object_sync ---
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: TransactionInputObjectsErrors { errors: [SharedObjectPriorVersionsPendingExecution { object_id: 0x1aa7479acb9f52c00137bf7e76eabb862c8485ab, version_not_ready: SequenceNumber(1) }] }', crates/sui/tests/shared_objects_tests.rs:288:6
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

   Canceling due to test failure: 0 tests still running
------------
     Summary [   5.971s] 1 tests run: 0 passed, 1 failed, 72 skipped
error: test run failed
Updated 1 path from the index
```

**Pull request merged**
