### PR TITLE
add an admin endpoint to print node config

### PR DESCRIPTION
**Pull request by longbowlu**
## Description 

As title 

## Test Plan 

tested locally

```
curl 127.0.0.1:49932/node-config | grep package_deny_list
```
---
If your changes are not user-facing and not a breaking change, you can skip the following section. Otherwise, please indicate what changed, and then add to the Release Notes section as highlighted during the release process.

### Type of Change (Check all that apply)

- [ ] user-visible impact
- [ ] breaking change for a client SDKs
- [ ] breaking change for FNs (FN binary must upgrade)
- [ ] breaking change for validators or node operators (must upgrade binaries)
- [ ] breaking change for on-chain data layout
- [ ] necessitate either a data wipe or data migration

### CODE REVIEW

**Review by mwtian — APPROVED** [review]
This can only be examined by the validator, right?

**Comment by longbowlu** [comment]
> This can only be examined by the validator admin themselves, right?

yes

**Comment by lxfind** [comment]
How is this different from asking them to run:
```
grep -A 3 package_deny_list node_config.yaml
```

**Comment by longbowlu** [comment]
> How is this different from asking them to run:
> 
> ```
> grep -A 3 package_deny_list node_config.yaml
> ```

config (e.g. deny list) could be placed in the wrong place which will be ignored when reading the file. The curl command prints the validated info so we could ask operators to run this to check if they have the right config.

**Review by arun-koshy — APPROVED** [review]

**Pull request merged**
