### PR TITLE
narwhal: remove invalid unsafe impl of Send + Sync

### PR DESCRIPTION
**Pull request by bmwill**

### CODE REVIEW

**Review by andll — APPROVED** [review]
Good find!

**Review by andll — APPROVED** [review]

**Comment by akichidis** [comment]
@bmwill apologies my ignorance here but why is this invalid use of `unsafe` ?

**Comment by bmwill** [comment]
@akichidis `Send` and `Sync` are how the rust compiler delivers on its promise of "fearless concurrency", they essentially dictate what types can be sent to other threads as well as concurrently shared between threads. This impl that existed unilaterally said that these types were Send and Sync despite there being situations where that would very much not be the case (T not being Send or Sync).

**Comment by akichidis** [comment]
> @akichidis `Send` and `Sync` are how the rust compiler delivers on its promise of "fearless concurrency", they essentially dictate what types can be sent to other threads as well as concurrently shared between threads. This impl that existed unilaterally said that these types were Send and Sync despite there being situations where that would very much not be the case (T not being Send or Sync).

Ah got it . Thanks a lot @bmwill for explaining this!

**Pull request merged**
