### PR TITLE
tracing: simplify tracing infra and support json output

### PR DESCRIPTION
**Pull request by bmwill**
Enable output tracing log events in a JSON format  by setting the `RUST_LOG_JSON` envvar.

### CODE REVIEW

**Comment by allan-bailey** [comment]
What do the logs look like?
Also, how are fields added to the logs?

**Comment by bmwill** [comment]
> What do the logs look like?
> 
> Also, how are fields added to the logs?
> 
> 

You can look at the format of the output from tracings docs:

https://docs.rs/tracing-subscriber/latest/tracing_subscriber/fmt/format/struct.Json.html#example-output

**Review by asonnino — APPROVED** [review]
Do we plan to remove open telemetry support?
I don't see problems with the PR but defer entirely to others about to best handle logs

**Comment by bmwill** [comment]
> Do we plan to remove open telemetry support?
> 
> I don't see problems with the PR but defer entirely to others about to best handle logs

It's not currently being used by anything that I'm aware of so I opted to remove it to clean up a large number of dependencies that were being added due to this as well as simplify our logging infra.

**Pull request merged**
