### PR TITLE
fix: Remove redundant dot in error message

### PR DESCRIPTION
**Pull request by howjmay**
## Description 

Like the following example error messages contains a redundant trailing dot.

```
Transaction execution failed due to issues with transaction inputs, please review the errors and try again: Gas budget: 1000 is lower than min: 1000000..
```

## Test plan 

Run `ExecuteTransactionBlock` with the update. Then the trailing dot will be removed

### CODE REVIEW

**Comment by amnn** [comment]
The change itself looks reasonable to me, but it looks like there are some tests (particularly, some snapshot tests) that also need to be updated -- would you mind updating those?

**Comment by howjmay** [comment]
Sure let me work on it

**Comment by amnn** [comment]
It looks like there are still some more tests that need to be updated. See the output here for an example: https://github.com/MystenLabs/sui/actions/runs/8982457752/job/24675989734?pr=17362

**Comment by howjmay** [comment]
Hi sorry for waiting. I was busy on sdk. I think I have fixed the errors!

**Comment by amnn** [comment]
Almost -- you have one more test that needs updating. It's a little difficult to read the CI output in this case, so I have snipped out the relevant failure:

```
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Snapshot Differences ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Snapshot file: crates/sui/tests/snapshots/ptb_files_tests__move_call_fun_resolution.ptb.snap
Snapshot: move_call_fun_resolution.ptb
Source: crates/sui/tests/ptb_files_tests.rs:97
────────────────────────────────────────────────────────────────────────────────
Expression: results.join("\n")
────────────────────────────────────────────────────────────────────────────────
-old snapshot
+new results
────────────┬───────────────────────────────────────────────────────────────────
   30    30 │    ╭─[4:13]
   31    31 │  3 │ --assign zero_x_zero @0x0
   32    32 │  4 │ --move-call zero_x_zero::option::is_none<u64> a
   33    33 │    ·             ─────┬─────
   34       │-   ·                  ╰── Object 0x0000000000000000000000000000000000000000000000000000000000000000 does not exist.
         34 │+   ·                  ╰── Object 0x0000000000000000000000000000000000000000000000000000000000000000 does not exist
   35    35 │  5 │ --move-call std::Option::is_none<u64> a
   36    36 │    ╰────
   37    37 │ 
   38    38 │   × Error when processing PTB
────────────┴───────────────────────────────────────────────────────────────────
Stopped on the first failure. Run `cargo insta test` to run all snapshots.
test test_ptb_files::ptb_files/move_call/move_call_fun_resolution.ptb ... FAILED

failures:

---- test_ptb_files::ptb_files/move_call/move_call_fun_resolution.ptb ----
test panicked: snapshot assertion for 'move_call_fun_resolution.ptb' failed in line 97


failures:
    test_ptb_files::ptb_files/move_call/move_call_fun_resolution.ptb

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 38 filtered out; finished in 26.33s
```

**Comment by howjmay** [comment]
Sorry I didn't know that was the same error caused by this change. I have changed `ptb_files_tests__move_call_fun_resolution.ptb.snap` file

**Review by amnn — APPROVED** [review]
Looks good, thanks for sticking with this change @howjmay !

**Comment by howjmay** [comment]
Thank you for help too @amnn !

**Pull request merged**
