### PR TITLE
Remove unused imported module and update some CLI command

### PR DESCRIPTION
**Pull request by vietanhvo**
+ The function sword_create didn't use any function from the tx_context module. Remove it to eliminate the warning
+ The "0x" prefix is already declared in export. So we must delete it for the command works correctly

### CODE REVIEW

**Comment by Clay-Mysten** [comment]
Thank you! This looks right to me yet am asking my experts to confirm. Thanks again!

**Review by Clay-Mysten — APPROVED** [review]

**Comment by vietanhvo** [comment]
I'm not sure about that. However, on my Ubuntu, the command with the "0x" prefix didn't work and displayed this error
image
So, I think this is because the prefix is already exported in $OBJECT and $RECIPIENT. If we use 0x$OBJECT, it will become 0x0x... When I delete them, the command work perfectly for me

**Comment by Clay-Mysten** [comment]
> I'm not sure about that. However, on my Ubuntu, the command with the "0x" prefix didn't work and displayed this error image So, I think this is because the prefix is already exported in $OBJECT and $RECIPIENT. If we use 0x$OBJECT, it will become 0x0x... When I delete them, the command work perfectly for me

Thank you. I'm adding others to confirm this fix is needed.

**Comment by Clay-Mysten** [comment]
@awelc can you take a look at this? Thanks!

**Review by awelc — APPROVED** [review]
Good catch! Thank you for the PR!

**Pull request merged**
