### PR TITLE
updated script to append hakari exclude

### PR DESCRIPTION
**Pull request by laura-makdah**
## Description 

Adds a line to the hackari excludes when doing an execution layer cut to avoid manually addition 
I will merge this one after https://github.com/MystenLabs/sui/pull/14592 gets merged

## Test Plan 

How did you test the new or updated feature?

---
If your changes are not user-facing and do not break anything, you can skip the following section. Otherwise, please briefly describe what has changed under the Release Notes section.

### Type of Change (Check all that apply)

- [ ] protocol change
- [ ] user-visible impact
- [ ] breaking change for a client SDKs
- [ ] breaking change for FNs (FN binary must upgrade)
- [ ] breaking change for validators or node operators (must upgrade binaries)
- [ ] breaking change for on-chain data layout
- [ ] necessitate either a data wipe or data migration

### CODE REVIEW

**Comment by laura-makdah** [comment]
the prerequisite PR has now been merged

**Review by amnn — COMMENTED** [review]
Can you re-use the functionality in `update_toml` for this? Perhaps just add an extra parameter to that function for the path to the TOML file, and then you should be able to add a template string in the `hakari.toml` file for this file to pick up.

**Comment by laura-makdah** [comment]
If we re-use the function `update_toml` the code for how we update the file would need to be passed in as well, which I feel would make it harder to understand, since the only common code in both these functions is that we readlines and then update a file

**Comment by amnn** [comment]
> the code for how we update the file would need to be passed in as well

This should not be the case. `update_toml` looks for comments in the file it is modifying and treats them as template strings if they mention the `$CUT` variable, so by adding such a template string to the hakari TOML file, you should be able to re-use the logic.  See, e.g.:

https://github.com/MystenLabs/sui/blob/d67d8c2b85a7fd83be2599b1a13993860e3b2e17/sui-execution/Cargo.toml#L17-L31

For an example of template strings that mention the `$CUT` variable.

**Comment by laura-makdah** [comment]
I am not sure how to cleanly parametrize these parts: 
`if line.startswith("# ") and "$CUT" in line:` vs `if line == "third-party = [\n" and not appended:`
and then this part
`toml.write(line[2:].replace("$CUT", feature))` vs `line += "    { name = \"move-vm-runtime-" + feature + "\", path = \"external-crates/move/move-execution/" + feature + "/crates/move-vm-runtime\" },\n"
                appended = True`
                
From what I remember of using python years ago it was not common to parameterize conditional statements, but that may have changed

**Review by amnn — CHANGES_REQUESTED** [review]
This is a little bit moot because @bmwill is on the verge of sunsetting workspace-hack, in #16185, but for whatever reason I'm struggling to get across what I meant, so I've put up a new PR that demonstrates it: #16294 (I couldn't push on top of this PR, because we would need to rebase this PR to actually test the change and I didn't then want to force push to this branch).

**Comment by laura-makdah** [comment]
I see what you mean now! It would require us to manually go and add the line you added in the PR, which I wasn't expecting. It sounds like this PR can be closed though?

**Comment by amnn** [comment]
> It would require us to manually go and add the line you added in the PR, which I wasn't expecting.

Yes, that's right -- that's what I meant by this comment:

> `update_toml` looks for comments in the file it is modifying and treats them as template strings if they mention the $CUT variable, so by adding such a template string to the hakari TOML file, you should be able to re-use the logic.

But indeed, this PR can be closed and the one I mentioned earlier can take its place!

**Pull request closed without merging**
