### PR TITLE
Sui Windows installation instructions

### PR DESCRIPTION
**Pull request by patrickkuo**
I have manually tested `cargo install --git ...`, `cargo install --path ... ` and `cargo build --release` and they all works fine after the fix here https://github.com/MystenLabs/sui/pull/3147.

I have also tested all the `sui client` command and `sui console`, with local network setup, all working as expected using windows's command prompt.

`sui console` does not work in PowerShell, looks like it's a known issue in rustyline, I don't think this is critical, we can fix this later if there are use cases for PowerShell.

### CODE REVIEW

**Comment by patrickkuo** [comment]
We will need to make sure we upgrade devnet when we push out this doc changes

**Comment by Clay-Mysten** [comment]
> > Let's discuss in Slack. We call for Linux here:
> > https://docs.sui.io/build/fullnode#software-requirements
> 
> I have added prerequisites for linux as well to make it more complete, and also tested Sui-cli in ubuntu and can confirm it's working as excepted.
> 
> I agree we need a doc refactoring to put all the installation instruction in install.md

I will work on this next

**Review by Clay-Mysten — APPROVED** [review]
Thanks, Patrick.  Does it make sense for me to bring in the requirements from the fullnode doc? If so, will do. Thanks again!

**Comment by Clay-Mysten** [comment]
Hi Patrick, feel free to submit this and I will iterate upon it before the announcement.

**Comment by patrickkuo** [comment]
> Hi Patrick, feel free to submit this and I will iterate upon it before the announcement.

Thanks @Clay-Mysten !

**Pull request merged**
