### PR TITLE
Add connect to RPC server to Sui tokens section of Install docs

### PR DESCRIPTION
**Pull request by Clay-Mysten**

### CODE REVIEW

**Review by patrickkuo — COMMENTED** [review]
sui start is for starting local sui network, the user don't need this step if they want to request devnet tokens.

**Review by randall-Mysten — APPROVED** [review]

**Comment by Clay-Mysten** [comment]
> > sui start is for starting local sui network, the user don't need this step if they want to request devnet tokens.
> 
> A user is reporting they have to do this to run '`sui client active-address` in: #3497
> 
> I will test now. Does this dependency now exist?

I get:
```
claymurphy@Clays-MacBook-Pro ~ % sui client active-address
Config file ["/Users/claymurphy/.sui/sui_config/client.yaml"] doesn't exist, do you want to connect to a Sui RPC server [yN]?y
Sui RPC server Url (Default to Sui DevNet if not specified) : 
0x7dfa9a8b1e9adbef4142230d61507f04f3d27cf5
claymurphy@Clays-MacBook-Pro ~ % 
```

**Comment by patrickkuo** [comment]
> > > sui start is for starting local sui network, the user don't need this step if they want to request devnet tokens.
> > 
> > 
> > A user is reporting they have to do this to run '`sui client active-address` in: #3497
> > I will test now. Does this dependency now exist?
> 
> I get:
> 
> ```
> claymurphy@Clays-MacBook-Pro ~ % sui client active-address
> Config file ["/Users/claymurphy/.sui/sui_config/client.yaml"] doesn't exist, do you want to connect to a Sui RPC server [yN]?y
> Sui RPC server Url (Default to Sui DevNet if not specified) : 
> 0x7dfa9a8b1e9adbef4142230d61507f04f3d27cf5
> claymurphy@Clays-MacBook-Pro ~ % 
> ```

this is the correct way to connect to the devnet, if the user is getting `Too many authority errors were detected`, they need to run `sui client switch --gateway https://gateway.devnet.sui.io:443` to point the client to devnet

**Review by patrickkuo — CHANGES_REQUESTED** [review]
we don't need `sui start` to connect to the devnet

**Comment by Clay-Mysten** [comment]
> > > > sui start is for starting local sui network, the user don't need this step if they want to request devnet tokens.
> > > 
> > > 
> > > A user is reporting they have to do this to run '`sui client active-address` in: #3497
> > > I will test now. Does this dependency now exist?
> > 
> > 
> > I get:
> > ```
> > claymurphy@Clays-MacBook-Pro ~ % sui client active-address
> > Config file ["/Users/claymurphy/.sui/sui_config/client.yaml"] doesn't exist, do you want to connect to a Sui RPC server [yN]?y
> > Sui RPC server Url (Default to Sui DevNet if not specified) : 
> > 0x7dfa9a8b1e9adbef4142230d61507f04f3d27cf5
> > claymurphy@Clays-MacBook-Pro ~ % 
> > ```
> 
> this is the correct way to connect to the devnet, if the user is getting `Too many authority errors were detected`, they need to run `sui client switch --gateway https://gateway.devnet.sui.io:443` to point the client to devnet

Alright, I have removed the added step and instead say, "Identify your address through either the Sui Wallet Browser Extension or by running the following command and electing to connect to a Sui RPC server if prompted:"

**Review by patrickkuo — APPROVED** [review]

**Pull request merged**
