### PR TITLE
Add benchmarking test suite for shared objects

### PR DESCRIPTION
**Pull request by sadhansood**
Shared object benchmarking script. The way to invoke it with defaults is:
```
cargo run --package sui-benchmark --bin shared
```

### CODE REVIEW

**Review by huitseeker — COMMENTED** [review]
A couple of items on direction:
- please note how we're creating an example binary in [sui-benchmark](https://github.com/MystenLabs/sui/tree/main/crates/sui-benchmark/src),
- one way to have a piece of code that's both a binary (which you can run in a staging environment) and a test (run by e.g. CI) is an [integration test](https://doc.rust-lang.org/rust-by-example/testing/integration_testing.html)
- you can look at [generate-format](https://github.com/MystenLabs/sui/blob/c809552100af23f726ef12c8f120d3a3092f4b21/crates/sui-core/tests/format.rs) for an example where we apply this discipline.

**Review by damirka — APPROVED** [review]
Apart from what @huitseeker already stated; I like the approach!

**Review by velvia — COMMENTED** [review]
Hey @sadhansood sorry I was sick and didn't really have time to look over this earlier.

I'm not sure I understand the design.  As I understand it:
* There are `num_workers` worker threads
* Each thread takes messages off of a channel.  
* Each thread keeps pushing more futures into the thread each of which seems to push another future into the thread?

It's not really clear to me how the system regulates how many requests (futures) are pushed out at once, or even when exactly they are inserted....   so would appreciate some explanation.

thanks

**Comment by sadhansood** [comment]
@velvia I'd also suggest looking at the latest version of this benchmark as that simplify things a little bit. But overall the idea is - the user decides how much throughput they want to test and workers will split that workload amongst themselves. Each worker has an interval ticker and will make a request per tick. On success, we add the counter and gas back in the pool for future use. We use an in flight ratio to decide how much extra counters we want to create to send requests on a tick which is needed if the latency of requests is more than 1 second. Eventually, if the system latency stabilizes at some number let's say 5s, having a ratio of 5 would be enough to get the desired throughput.

**Pull request merged**
