### PR TITLE
edition is changed for 2024.alpha

### PR DESCRIPTION
**Pull request by veliuysal**
This PR includes only edition changes. Our development is not working in the old edition. Also, you have published your blog "You can change 2024.beta edition with 2024.alpha or old version"

### CODE REVIEW

**Comment by tedks** [comment]
Hey Veli -- Could you say a little bit more about the problems you're having? Have you tried running `sui move migrate`?

**Comment by stefan-mysten** [comment]
@veliuysal what CLI version are you using to build your Move project? `sui -V`

**Comment by veliuysal** [comment]
> `sui -V`

sui 1.19.0-93e6b4845 in M1 Macbook Pro

**Comment by veliuysal** [comment]
> Hey Veli -- Could you say a little bit more about the problems you're having? Have you tried running `sui move migrate`?

Is there this subcommand in sui CLI? I have asked to CLI, response is in the below.
Screenshot 2024-11-12 at 23 12 36

**Comment by stefan-mysten** [comment]
Thanks. You have a very old `sui` CLI version, we'd recommend you [to install the latest version](https://docs.sui.io/guides/developer/getting-started/sui-install) (`v1.37`) and then run `sui move migrate` which should fix all your issues.

**Pull request closed without merging**
