### PR TITLE
[bugfix] - fix CallArg <-> SuiJson conversion logic

### PR DESCRIPTION
**Pull request by patrickkuo**
## Description 

This PR fixes a move value to SuiJson bug, SuiJson was mainly used for displaying human readable json back in the day, the move object to json conversion was "best effort" and occasionally converting number into ascii strings. This PR changes the conversion and now uses the function signature to determine the correct type before doing the conversion.

This RP also changes the input parameter of SuiProgrammableTransaction to SuiCallArg instead of using SuiJsonValue directly.

## Test Plan 

SuiJson conversion logic are covered by unit tests 
Also did some manual test locally.

Example PT response:
```
{
    "jsonrpc": "2.0",
    "result": {
        "digest": "3FuXQ4UHg7jUCWGrTvmagDYmq2wXggRU5S8Gx7YKQSkz",
        "transaction": {
            "data": {
                "messageVersion": "v1",
                "transaction": {
                    "kind": "ProgrammableTransaction",
                    "inputs": [
                        {
                            "type": "object",
                            "objectType": "sharedObject",
                            "object_id": "0x0000000000000000000000000000000000000000000000000000000000000005",
                            "initial_shared_version": 1,
                            "mutable": true
                        },
                        {
                            "type": "object",
                            "objectType": "immOrOwnedObject",
                            "object_id": "0xf2e2c3cf773758027959170d2d7369a08c3be9d455a35b3d316feaa1950fa453",
                            "version": 1,
                            "digest": "6aQw2cGxuSmf6SuLd8C7t2LnStM293GSi5D1kVwKPYsD"
                        },
                        {
                            "type": "pure",
                            "valueType": "address",
                            "value": "0xc64291042b33e860faa3f733953676cd7bc24462bf8fc79bc1d3ac2ac214ebc2"
                        }
                    ],
                    "commands": [
                        {
                            "MoveCall": {
                                "package": "0x0000000000000000000000000000000000000000000000000000000000000002",
                                "module": "sui_system",
                                "function": "request_add_stake",
                                "arguments": [
                                    {
                                        "Input": 0
                                    },
                                    {
                                        "Input": 1
                                    },
                                    {
                                        "Input": 2
                                    }
                                ]
                            }
                        }
                    ]
                },
                "sender": "0xce1bf7db5ad6b04bfc305c049f08b80d5ccdc5d6d65d2ded13e95516d1e9fa22",
                "gasData": {
                    "payment": [
                        {
                            "objectId": "0x3121afc2890c0eb0cad14d495b4682618c12a1ac73577e7f9a45b04619c755d9",
                            "version": 3,
                            "digest": "DWnuhB7WGepk4bHysVs4jvpDA1bMcWdEqgzoX6zkRHeq"
                        }
                    ],
                    "owner": "0xce1bf7db5ad6b04bfc305c049f08b80d5ccdc5d6d65d2ded13e95516d1e9fa22",
                    "price": 1,
                    "budget": 100000
                }
            },
            "txSignatures": [
                "AFCWZe8Gy8m/enRPZEygzUq23H3O8IANSYnP4jHc5i8pSJdt0f8ZBrUH+0vwnlxyos9A0CzPcoCKSWm66ZbMJgvMmmv2BbuYf+KmNsqJ2ti6sOAiFwS/SbKh1OCWydu6vg=="
            ]
        },
        "timestampMs": 1679239266370,
        "checkpoint": 1160
    },
    "id": 1
}
```

### CODE REVIEW

**Review by Jordan-Mysten — APPROVED** [review]
TS changes + API structure LGTM

**Comment by oxade** [comment]
I don't see many new tests. Are you confident we don't need additional tests?

**Review by plam-ml — APPROVED** [review]
lgtm

**Comment by patrickkuo** [comment]
> I don't see many new tests. Are you confident we don't need additional tests? @patrickkuo

I have added a few unit tests for String and option type as they require special handlings, the rest is covered by e2e tests, we have quite a few e2e tests in TS SDK which tests from move to the SDK end.

**Comment by oxade** [comment]
> > I don't see many new tests. Are you confident we don't need additional tests? @patrickkuo
> 
> I have added a few unit tests for String and option type as they require special handlings, the rest is covered by e2e tests, we have quite a few e2e tests in TS SDK which tests from move to the SDK end.

Right, I missed the SuiJson one, thank you.

**Review by oxade — APPROVED** [review]

**Pull request merged**
