### PR TITLE
Point jsonrpsee to forked version to support error metrics by error code

### PR DESCRIPTION
**Pull request by wlmyng**
## Description 

Corresponding change in the forked repo: https://github.com/wlmyng/jsonrpsee/pull/1
## Test Plan 

How did you test the new or updated feature?

---
If your changes are not user-facing and not a breaking change, you can skip the following section. Otherwise, please indicate what changed, and then add to the Release Notes section as highlighted during the release process.

### Type of Change (Check all that apply)

- [ ] user-visible impact
- [ ] breaking change for a client SDKs
- [ ] breaking change for FNs (FN binary must upgrade)
- [ ] breaking change for validators or node operators (must upgrade binaries)
- [ ] breaking change for on-chain data layout
- [ ] necessitate either a data wipe or data migration

### CODE REVIEW

**Review by patrickkuo — APPROVED** [review]
Nice one.

**Comment by patrickkuo** [comment]
You need to run hakari generate

**Comment by lxfind** [comment]
Is this a temporary walkaround? Do we plan to upstream this change?

**Comment by wlmyng** [comment]
> Is this a temporary walkaround? Do we plan to upstream this change?

Yes, and yes. I've opened an issue with the repo owners https://github.com/paritytech/jsonrpsee/issues/1129

It is complicated by the fact that we're two major versions behind, and I think this implementation is not as straightforward in the latest version.

**Pull request merged**
