### PR TITLE
Bump narwhal to `89c5974`

### PR DESCRIPTION
**Pull request by mwtian**
One notable change is that I have to bump the `rand` version to resolve dependency conflict.

### CODE REVIEW

**Review by tharbert — APPROVED** [review]

**Comment by joyqvq** [comment]
i might have broken a test on batch verify in the upgrade. https://github.com/MystenLabs/sui/pull/3891

still figuring out why there

**Comment by mwtian** [comment]
> i might have broken a test on batch verify in the upgrade. #3891
> 
> still figuring out why there

Sounds good. I encountered the same failure in `test_handle_reject_malicious_signature`. I will add comment to your PR and help push it through quicker.

**Comment by huitseeker** [comment]
I would consider closing this in favor of #3891 which passes tests save for the rocksdb upgrade.
The NW pointer in the present PR is actually newer, but I'd advise @joyqvq to bump that pointer in #3891

**Comment by mwtian** [comment]
Definitely, I was just testing some fixes to tests that I pushed to https://github.com/MystenLabs/sui/pull/3891. Closing again now.

**Pull request closed without merging**
