### PR TITLE
Dedupe json-rpc.md with new API reference

### PR DESCRIPTION
**Pull request by Romainua**
Update current json method

### CODE REVIEW

**Comment by patrickkuo** [comment]
AFAIK we are planning to removing the api docs from this page soon and use the [generated API doc](https://docs.sui.io/sui-jsonrpc) instead, @Clay-Mysten can you take a look at this?

**Comment by Clay-Mysten** [comment]
> AFAIK we are planning to removing the api docs from this page soon and use the [generated API doc](https://docs.sui.io/sui-jsonrpc) instead, @Clay-Mysten can you take a look at this?

Yes, let me take this deduping on. Thanks for the contribution, @Romainua . Please see the latest API reference docs at:
https://docs.sui.io/sui-jsonrpc

@patrickkuo , can we help people find the sources for those docs so they may contribute fixes there? Let's discuss in our meeting this week. Thanks!

**Comment by Clay-Mysten** [comment]
@patrickkuo and I had an excellent meeting where we ironed out the Comms/Talk workflow, most notably agreeing to remove the redundant methods from our JSON RPC contents:

In:
https://docs.sui.io/build/json-rpc#sui-json-rpc-api
Keep RPC Discover reference.

Remove the rest once the `curl` commands are automatically included in the API reference:
https://github.com/MystenLabs/sui/issues/3877#issuecomment-1212270291 
Also, I will confirm we aren’t losing any details in the descriptions.

Next (perhaps in a distinct issue):
Replace references to gateway with fullnode (soon).
The RPC server is our Gateway. It’s going away. 
We will need to update:
https://docs.sui.io/build/json-rpc
To replace RPC server with Fullnode.
Determine what to do with other references to our gateway (such as in the Learn section).

Update Talk index to reflect latest flow and new Talk (comms) menu:
https://docs.sui.io/build/comms

See related Build docs work in:
https://github.com/MystenLabs/sui/issues/1362

**Comment by Romainua** [comment]
> @patrickkuo and I had an excellent meeting where we ironed out the Comms/Talk workflow, most notably agreeing to remove the redundant methods from our JSON RPC contents:
> 
> In: https://docs.sui.io/build/json-rpc#sui-json-rpc-api Keep RPC Discover reference.
> 
> Remove the rest once the `curl` commands are automatically included in the API reference: [#3877 (comment)](https://github.com/MystenLabs/sui/issues/3877#issuecomment-1212270291) Also, I will confirm we aren’t losing any details in the descriptions.
> 
> Next (perhaps in a distinct issue): Replace references to gateway with fullnode (soon). The RPC server is our Gateway. It’s going away. We will need to update: https://docs.sui.io/build/json-rpc To replace RPC server with Fullnode. Determine what to do with other references to our gateway (such as in the Learn section).
> 
> Update Talk index to reflect latest flow and new Talk (comms) menu: https://docs.sui.io/build/comms
> 
> See related Build docs work in: #1362

Can I help with something of this?

**Comment by Clay-Mysten** [comment]
> > @patrickkuo and I had an excellent meeting where we ironed out the Comms/Talk workflow, most notably agreeing to remove the redundant methods from our JSON RPC contents:
> > In: https://docs.sui.io/build/json-rpc#sui-json-rpc-api Keep RPC Discover reference.
> > Remove the rest once the `curl` commands are automatically included in the API reference: [#3877 (comment)](https://github.com/MystenLabs/sui/issues/3877#issuecomment-1212270291) Also, I will confirm we aren’t losing any details in the descriptions.
> > Next (perhaps in a distinct issue): Replace references to gateway with fullnode (soon). The RPC server is our Gateway. It’s going away. We will need to update: https://docs.sui.io/build/json-rpc To replace RPC server with Fullnode. Determine what to do with other references to our gateway (such as in the Learn section).
> > Update Talk index to reflect latest flow and new Talk (comms) menu: https://docs.sui.io/build/comms
> > See related Build docs work in: #1362
> 
> Can I help with something of this?

Yes, please Roman! Can you compare the contents of the links above and ID differences so we can merge them in?

**Comment by Romainua** [comment]
> > > @patrickkuo and I had an excellent meeting where we ironed out the Comms/Talk workflow, most notably agreeing to remove the redundant methods from our JSON RPC contents:
> > > In: https://docs.sui.io/build/json-rpc#sui-json-rpc-api Keep RPC Discover reference.
> > > Remove the rest once the `curl` commands are automatically included in the API reference: [#3877 (comment)](https://github.com/MystenLabs/sui/issues/3877#issuecomment-1212270291) Also, I will confirm we aren’t losing any details in the descriptions.
> > > Next (perhaps in a distinct issue): Replace references to gateway with fullnode (soon). The RPC server is our Gateway. It’s going away. We will need to update: https://docs.sui.io/build/json-rpc To replace RPC server with Fullnode. Determine what to do with other references to our gateway (such as in the Learn section).
> > > Update Talk index to reflect latest flow and new Talk (comms) menu: https://docs.sui.io/build/comms
> > > See related Build docs work in: #1362
> > 
> > 
> > Can I help with something of this?
> 
> Yes, please Roman! Can you compare the contents of the links above and ID differences so we can merge them in?

Sorry, for clarification. Сompare these? 
https://docs.sui.io/build/json-rpc#sui-json-rpc-api
https://docs.sui.io/sui-jsonrpc

**Comment by Clay-Mysten** [comment]
> > > > @patrickkuo and I had an excellent meeting where we ironed out the Comms/Talk workflow, most notably agreeing to remove the redundant methods from our JSON RPC contents:
> > > > In: https://docs.sui.io/build/json-rpc#sui-json-rpc-api Keep RPC Discover reference.
> > > > Remove the rest once the `curl` commands are automatically included in the API reference: [#3877 (comment)](https://github.com/MystenLabs/sui/issues/3877#issuecomment-1212270291) Also, I will confirm we aren’t losing any details in the descriptions.
> > > > Next (perhaps in a distinct issue): Replace references to gateway with fullnode (soon). The RPC server is our Gateway. It’s going away. We will need to update: https://docs.sui.io/build/json-rpc To replace RPC server with Fullnode. Determine what to do with other references to our gateway (such as in the Learn section).
> > > > Update Talk index to reflect latest flow and new Talk (comms) menu: https://docs.sui.io/build/comms
> > > > See related Build docs work in: #1362
> > > 
> > > 
> > > Can I help with something of this?
> > 
> > 
> > Yes, please Roman! Can you compare the contents of the links above and ID differences so we can merge them in?
> 
> Sorry, for clarification. Сompare these? https://docs.sui.io/build/json-rpc#sui-json-rpc-api https://docs.sui.io/sui-jsonrpc

Yes, or rather the whole set of methods at:
https://docs.sui.io/build/json-rpc

**Comment by Romainua** [comment]
> > > > > @patrickkuo and I had an excellent meeting where we ironed out the Comms/Talk workflow, most notably agreeing to remove the redundant methods from our JSON RPC contents:
> > > > > In: https://docs.sui.io/build/json-rpc#sui-json-rpc-api Keep RPC Discover reference.
> > > > > Remove the rest once the `curl` commands are automatically included in the API reference: [#3877 (comment)](https://github.com/MystenLabs/sui/issues/3877#issuecomment-1212270291) Also, I will confirm we aren’t losing any details in the descriptions.
> > > > > Next (perhaps in a distinct issue): Replace references to gateway with fullnode (soon). The RPC server is our Gateway. It’s going away. We will need to update: https://docs.sui.io/build/json-rpc To replace RPC server with Fullnode. Determine what to do with other references to our gateway (such as in the Learn section).
> > > > > Update Talk index to reflect latest flow and new Talk (comms) menu: https://docs.sui.io/build/comms
> > > > > See related Build docs work in: #1362
> > > > 
> > > > 
> > > > Can I help with something of this?
> > > 
> > > 
> > > Yes, please Roman! Can you compare the contents of the links above and ID differences so we can merge them in?
> > 
> > 
> > Sorry, for clarification. Сompare these? https://docs.sui.io/build/json-rpc#sui-json-rpc-api https://docs.sui.io/sui-jsonrpc
> 
> Yes, or rather the whole set of methods at: https://docs.sui.io/build/json-rpc

But if I am not mistaken, they will be removed and replace from https://docs.sui.io/sui-jsonrpc

**Comment by Clay-Mysten** [comment]
> > > > > > @patrickkuo and I had an excellent meeting where we ironed out the Comms/Talk workflow, most notably agreeing to remove the redundant methods from our JSON RPC contents:
> > > > > > In: https://docs.sui.io/build/json-rpc#sui-json-rpc-api Keep RPC Discover reference.
> > > > > > Remove the rest once the `curl` commands are automatically included in the API reference: [#3877 (comment)](https://github.com/MystenLabs/sui/issues/3877#issuecomment-1212270291) Also, I will confirm we aren’t losing any details in the descriptions.
> > > > > > Next (perhaps in a distinct issue): Replace references to gateway with fullnode (soon). The RPC server is our Gateway. It’s going away. We will need to update: https://docs.sui.io/build/json-rpc To replace RPC server with Fullnode. Determine what to do with other references to our gateway (such as in the Learn section).
> > > > > > Update Talk index to reflect latest flow and new Talk (comms) menu: https://docs.sui.io/build/comms
> > > > > > See related Build docs work in: #1362
> > > > > 
> > > > > 
> > > > > Can I help with something of this?
> > > > 
> > > > 
> > > > Yes, please Roman! Can you compare the contents of the links above and ID differences so we can merge them in?
> > > 
> > > 
> > > Sorry, for clarification. Сompare these? https://docs.sui.io/build/json-rpc#sui-json-rpc-api https://docs.sui.io/sui-jsonrpc
> > 
> > 
> > Yes, or rather the whole set of methods at: https://docs.sui.io/build/json-rpc
> 
> But if I am not mistaken, they will be removed and replace from https://docs.sui.io/sui-jsonrpc

 Yes I merely want to make sure we don't lose anything when we remove those contents

**Comment by Romainua** [comment]
> > > > > > > @patrickkuo and I had an excellent meeting where we ironed out the Comms/Talk workflow, most notably agreeing to remove the redundant methods from our JSON RPC contents:
> > > > > > > In: https://docs.sui.io/build/json-rpc#sui-json-rpc-api Keep RPC Discover reference.
> > > > > > > Remove the rest once the `curl` commands are automatically included in the API reference: [#3877 (comment)](https://github.com/MystenLabs/sui/issues/3877#issuecomment-1212270291) Also, I will confirm we aren’t losing any details in the descriptions.
> > > > > > > Next (perhaps in a distinct issue): Replace references to gateway with fullnode (soon). The RPC server is our Gateway. It’s going away. We will need to update: https://docs.sui.io/build/json-rpc To replace RPC server with Fullnode. Determine what to do with other references to our gateway (such as in the Learn section).
> > > > > > > Update Talk index to reflect latest flow and new Talk (comms) menu: https://docs.sui.io/build/comms
> > > > > > > See related Build docs work in: #1362
> > > > > > 
> > > > > > 
> > > > > > Can I help with something of this?
> > > > > 
> > > > > 
> > > > > Yes, please Roman! Can you compare the contents of the links above and ID differences so we can merge them in?
> > > > 
> > > > 
> > > > Sorry, for clarification. Сompare these? https://docs.sui.io/build/json-rpc#sui-json-rpc-api https://docs.sui.io/sui-jsonrpc
> > > 
> > > 
> > > Yes, or rather the whole set of methods at: https://docs.sui.io/build/json-rpc
> > 
> > 
> > But if I am not mistaken, they will be removed and replace from https://docs.sui.io/sui-jsonrpc
> 
> Yes I merely want to make sure we don't lose anything when we remove those contents

Got it, thanks for the explanation! So I will save all the contents that is not include in https://docs.sui.io/sui-jsonrpc

**Comment by Clay-Mysten** [comment]
> > > > > > > > @patrickkuo and I had an excellent meeting where we ironed out the Comms/Talk workflow, most notably agreeing to remove the redundant methods from our JSON RPC contents:
> > > > > > > > In: https://docs.sui.io/build/json-rpc#sui-json-rpc-api Keep RPC Discover reference.
> > > > > > > > Remove the rest once the `curl` commands are automatically included in the API reference: [#3877 (comment)](https://github.com/MystenLabs/sui/issues/3877#issuecomment-1212270291) Also, I will confirm we aren’t losing any details in the descriptions.
> > > > > > > > Next (perhaps in a distinct issue): Replace references to gateway with fullnode (soon). The RPC server is our Gateway. It’s going away. We will need to update: https://docs.sui.io/build/json-rpc To replace RPC server with Fullnode. Determine what to do with other references to our gateway (such as in the Learn section).
> > > > > > > > Update Talk index to reflect latest flow and new Talk (comms) menu: https://docs.sui.io/build/comms
> > > > > > > > See related Build docs work in: #1362
> > > > > > > 
> > > > > > > 
> > > > > > > Can I help with something of this?
> > > > > > 
> > > > > > 
> > > > > > Yes, please Roman! Can you compare the contents of the links above and ID differences so we can merge them in?
> > > > > 
> > > > > 
> > > > > Sorry, for clarification. Сompare these? https://docs.sui.io/build/json-rpc#sui-json-rpc-api https://docs.sui.io/sui-jsonrpc
> > > > 
> > > > 
> > > > Yes, or rather the whole set of methods at: https://docs.sui.io/build/json-rpc
> > > 
> > > 
> > > But if I am not mistaken, they will be removed and replace from https://docs.sui.io/sui-jsonrpc
> > 
> > 
> > Yes I merely want to make sure we don't lose anything when we remove those contents
> 
> Got it, thanks for the explanation! So I will save all the contents that is not include in https://docs.sui.io/sui-jsonrpc

Yes, that is perfect. Thank you, my friend!

**Pull request merged**
