### PR TITLE
Pipe Protocol Config into NW & Update protocol version to 11 for new NW VersionedMetadata field

### PR DESCRIPTION
**Pull request by arun-koshy**
## Description 

Ensure all latencies of steps in NW are logged from batch creation to batch being fetched for execution, so we can spot check some digests from start to finish. Additionally update how batch execution latency is calculated. Whenever we receive a batch from other workers we update the metadata to the current time signifying the time we received the batch. We will now have two metrics one calculating the overall latency using the original created at timestamp from a remote worker and one that only calculate latency from the time a batch was created/received locally.

To do this the protocol config also had to be passed in from Sui and piped through NW. The decision was made that all NW tests will be compatible with the latest protocol version and any previous versions would need to be explicitly tested. Also this PR adds protocol version 11 so that the new `VersionedMetadata` field can be used in NW code.

## Test Plan 

Existing Unit Tests

### CODE REVIEW

**Review by akichidis — COMMENTED** [review]
A couple of comments left. One thing that we'll probably miss with this change is that any network latency on batch propagation will not be caught from the validators themselves as everyone now will see the "local" time fetched. Since it's metadata though is an easy change to make/revert anyways if we see that we don't get additional value.

**Review by mwtian — COMMENTED** [review]
I hope the approach of updating batch creation time can be avoided. If the creation time becomes unexpected, it will be hard to tell if the problem happened during creation or overwriting. Is it possible to attach another timestamp, or just debug log the report batch latency so they can be subtracted if needed?

**Comment by akichidis** [comment]
> I hope the approach of updating batch creation time can be avoided. If the creation time becomes unexpected, it will be hard to tell if the problem happened during creation or overwriting. Is it possible to attach another timestamp, or just debug log the report batch latency so they can be subtracted if needed?

Agreed on keeping another timestamp for this, it will make things cleaner. I am approving to have this merged and maybe we can  work on another PR?

**Comment by arun-koshy** [comment]
I was actually thinking about updating the code later to distinguish between batches received by others vs our own batches in the latency measurements. But I think adding a `received_at` timestamp to Batch metadata will do the job. Then we can just separate the batch execution latency into two buckets (others vs ours).

However because metadata is not versioned I cant just update the existing struct without causing issues right? Can I version it now and follow the protocol upgrade flow?

**Comment by mwtian** [comment]
> I was actually thinking about updating the code later to distinguish between batches received by others vs our own batches in the latency measurements. But I think adding a `received_at` timestamp to Batch metadata will do the job. Then we can just separate the batch execution latency into two buckets (others vs ours).
> 
> However because metadata is not versioned I cant just update the existing struct without causing issues right? Can I version it now and follow the protocol upgrade flow?

We do the proper versioned update later. Btw for the information we need, is it needed across all validators?

**Review by akichidis — APPROVED** [review]
Thanks a lot @arun-koshy for this! Left a few comments 👍

**Pull request merged**
