### PR TITLE
[move] Adds a counter example

### PR DESCRIPTION
**Pull request by damirka**

### CODE REVIEW

**Comment by asonnino** [comment]
How can I create a transaction to call a function of that contract?

**Review by sblackshear — APPROVED** [review]

**Comment by sblackshear** [comment]
> How can I create a transaction to call a function of that contract?

I think @patrickkuo or @awelc will be the best to help with this, see also https://docs.sui.io/build/wallet#calling-move-code

**Comment by sblackshear** [comment]
Will need https://docs.sui.io/build/wallet#publish-packages to publish the `Counter` first

**Comment by lxfind** [comment]
@asonnino For references, you can also check our programming with objects tutorials: https://github.com/MystenLabs/sui/blob/main/doc/src/build/programming-with-objects/ch1-object-basics.md#on-chain-interactions
There are some instructions interacting with wallet too. It doesn't yet cover shared objects, but otherwise all is similar.

**Comment by damirka** [comment]
Forgot to put a license header. 😶

**Pull request merged**
