### PR TITLE
Remove deprecated & dead code

### PR DESCRIPTION
**Pull request by mystenmark**
Unlike the previous attempt to do this (#14635), this time I'm not removing anything from the read side, only removing unused code

### CODE REVIEW

**Comment by lxfind** [comment]
Can you remind us why it is safe to delete it for reads?

**Review by williampsmith — APPROVED** [review]

**Comment by mystenmark** [comment]
> Can you remind us why it is safe to delete it for reads?

It is used by unpruned nodes, so we can't delete the code that writes into the deprecated tables, or the code that reads it from json-rpc. But we can delete the stuff where we read it internally. In the PR, the checks on the epoch flags have been guaranteed to take the first branch for many months now

**Comment by lxfind** [comment]
So these read functions are used by RPC only?

**Comment by mystenmark** [comment]
> So these read functions are used by RPC only?

RPC uses these via TransactionKeyValueStoreTrait, which is the main place where we still read from the deprecated table.

**Pull request merged**
