### PR TITLE
Properly fix test_subscription test

### PR DESCRIPTION
**Pull request by lxfind**
The `start_paused` config means to start the test with time paused. The documentation isn't very clear about what happens if you depend on time in the test when time is paused, but my best guess is it's undefined?
Removing this fixed all the mysterious time interval issues.

### CODE REVIEW

**Comment by gdanezis** [comment]
> The start_paused config means to start the test with time paused. The documentation isn't very clear about what happens if you depend on time in the test when time is paused, but my best guess is it's undefined? Removing this fixed all the mysterious time interval issues.

The whole point of the time paused flag is to reliably test function where time is involved :)

**Comment by lxfind** [comment]
Oh didn't know that. But then in that case, there is no way to rely on batch behavior deterministically, right? Because you could be ticking all the time and hence batching at arbitrary times.

**Comment by bmwill** [comment]
Is https://docs.rs/tokio/latest/tokio/time/fn.advance.html properly used in the test to advance time?

**Comment by bmwill** [comment]
Probably would also need to make sure we used https://docs.rs/tokio/latest/tokio/time/struct.Instant.html instead of the stdlib type to make sure the mocked time in tests is properly handled

**Comment by lxfind** [comment]
Thanks Brandon! That might be the issue here.

Replaced all sleep with either yield or advance depending on the need.

**Comment by lxfind** [comment]
Looks like this is failing on Linux. I am out of depth.

**Comment by lxfind** [comment]
The core of this issue is this:
On Mac, the transaction stream stops at 105, and end up with a batch there, and then start from 106 afterwards.
On Linux, the transaction stream doesn't stop at 105 but continue all the way to 109.

**Pull request closed without merging**
