### PR TITLE
Support bls_min_pk verify in Move

### PR DESCRIPTION
**Pull request by benr-ml**
Support verification of BLS signatures that use G1 for public keys.
Tested with an actual Drand's response. (Will add an example of how to use Drand in move in a follow up PR.)

### CODE REVIEW

**Comment by benr-ml** [comment]
@kchalkias since genesis files keep changing all the time, I will resolve the conflicts after we finish the review.

**Review by kchalkias — COMMENTED** [review]
LGTM and will approve after genesis conflict resolution. Only one comment: Do we need any extra logic for DRAND verification to only accept canonical signatures; BLS12381 is not a prime order curve.

**Comment by benr-ml** [comment]
@kchalkias updated genesis files.
DRand only defines the message encoding (hash(prev_sig+round)), and the rest is a standard BLS signature.

**Comment by kchalkias** [comment]
Afaik there are at least two modes for DRAND (chained Vs unchained), iirc there are also versions + typically for BLS-based beacons we do check for malleability.

**Comment by benr-ml** [comment]
> Afaik there are at least two modes for DRAND (chained Vs unchained)
The public APIs use the chained mode (https://drand.love/developer/http-api/#chain-hash-public-latest) which makes sense in all use cases.

>  typically for BLS-based beacons we do check for malleability.
Could you elaborate?

**Review by huitseeker — COMMENTED** [review]
It would be great if this could refer to the RFC ciphersuite in comments, i.e. in this case `BLS_SIG_BLS12381G2_XMD:SHA-256_SSWU_RO_`, and differentiates it from the more common `BLS_SIG_BLS12381G1_XMD:SHA-256_SSWU_RO_` we use for validator signatures. A lot of folks are going to come to this with no context on BLS signatures, and for them,
> If the signature is a valid BLS12381 signature of the message and public key, return true.
> Otherwise, return false.

is not giving enough context, I'm afraid.

**Review by huitseeker — APPROVED** [review]
This LGTM, but will require re-genesis at least => please announce in the relevant channels @benr-ml

**Pull request merged**
