### PR TITLE
Update wallet.md

### PR DESCRIPTION
**Pull request by Romainua**
Here was updating `wallet merge-coin` and `wallet transfer-coin` format of wallet commands  to currently format and some minor changes

### CODE REVIEW

**Comment by Clay-Mysten** [comment]
@patrickkuo can we make these changes in `main` given we're publishing to docs.sui.io from there now? Or have they already been done there? Thanks!

**Comment by Romainua** [comment]
> @patrickkuo can we make these changes in `main` given we're publishing to docs.sui.io from there now? Or have they already been done there? Thanks!

changed base to `main`

**Comment by huitseeker** [comment]
@Romainua Would you mind issuing a rebase? You have embarked commit [4bd9581](https://github.com/MystenLabs/sui/pull/2236/commits/4bd958166308abb4c527390936276c4f0a23294b) which I don't think you wanted as part of your changes.

**Comment by Romainua** [comment]
> @Romainua Would you mind issuing a rebase? You have embarked commit [4bd9581](https://github.com/MystenLabs/sui/pull/2236/commits/4bd958166308abb4c527390936276c4f0a23294b) which I don't think you wanted as part of your changes.

sorry, rebase into `main` correct?

**Comment by Clay-Mysten** [comment]
> > @Romainua Would you mind issuing a rebase? You have embarked commit [4bd9581](https://github.com/MystenLabs/sui/pull/2236/commits/4bd958166308abb4c527390936276c4f0a23294b) which I don't think you wanted as part of your changes.
> 
> sorry, rebase into `main` correct?

@patrickkuo, please help @Romainua merge in this change to main as needed. Thank you all!

**Comment by patrickkuo** [comment]
> > > @Romainua Would you mind issuing a rebase? You have embarked commit [4bd9581](https://github.com/MystenLabs/sui/pull/2236/commits/4bd958166308abb4c527390936276c4f0a23294b) which I don't think you wanted as part of your changes.
> > 
> > 
> > sorry, rebase into `main` correct?
> 
> @patrickkuo, please help @Romainua merge in this change to main as needed. Thank you all!

I am not sure I can help resolve the conflict in the fork.... this branch need a rebase onto MystenLabs:main, there are conflict in sui/src/config/mod.rs due to recent project structure change

**Comment by Romainua** [comment]
> > > > @Romainua Would you mind issuing a rebase? You have embarked commit [4bd9581](https://github.com/MystenLabs/sui/pull/2236/commits/4bd958166308abb4c527390936276c4f0a23294b) which I don't think you wanted as part of your changes.
> > > 
> > > 
> > > sorry, rebase into `main` correct?
> > 
> > 
> > @patrickkuo, please help @Romainua merge in this change to main as needed. Thank you all!
> 
> I am not sure I can help resolve the conflict in the fork.... this branch need a rebase onto MystenLabs:main, there are conflict in sui/src/config/mod.rs due to recent project structure change

I will reopen pr

**Comment by patrickkuo** [comment]
Thanks @Romainua and sorry for the hassle, add me in the new PR and I will look at it straightaway.

**Comment by Clay-Mysten** [comment]
> Thanks @Romainua and sorry for the hassle, add me in the new PR and I will look at it straightaway.

Thank you, @patrickkuo and @Romainua! Please stick with us, my friend. We are sorting our processes out now.

**Pull request closed without merging**
