### PR TITLE
Update build-test.md & debug-publish.md

### PR DESCRIPTION
**Pull request by vietanhvo**
I think there is a mistake about the id field with type UID in Sword and Forge structs

### CODE REVIEW

**Review by tnowacki — APPROVED** [review]
Thanks!

**Review by Clay-Mysten — APPROVED** [review]
Thank you so much for making this update! Please look for this change and your name among the Contributors at the bottom of the affected page on docs.sui.io (Latest build view) in the coming days.

**Review by Clay-Mysten — CHANGES_REQUESTED** [review]
Actually, this was done in the devnet branch. Let me port to main, if needed there. Please work in the main branch in the future. See:
https://docs.sui.io/devnet/contribute#updates

Thanks!

**Comment by vietanhvo** [comment]
Got it! I will update the main branch in the future. Sorry about my mistake

**Comment by Clay-Mysten** [comment]
> Got it! I will update the main branch in the future. Sorry about my mistake

No worries, my friend. You new change looks great!
https://github.com/MystenLabs/sui/pull/4275

**Pull request closed without merging**
