### PR TITLE
[graphql][1/n] Refactor gas-related convert_to fns to utilize async-graphql's Object macro

### PR DESCRIPTION
**Pull request by wlmyng**
## Description 

This PR refactors convert_to_gas_input, convert_to_gas_cost_summary, and convert_to_gas_effects in favor of utilizing the `#[Object]` macro. These convert_to functions are intended to convert struct objects into GraphQL objects, but the issue is that they will always make computations and data fetches for each field, even if the caller did not specify those fields. For example, if I make a query for TransactionBlock for the gasInput field and only specify the gas_price, we nonetheless make the extra conversions for gas_sponsor, gas_budget, and the data fetch for gas_payment. 

Continuing with the example above, in this refactor, the struct definition of the GraphQL object GasInput now has the corresponding "native" fields, and implements From SuiGasData. The impl Object for GasInput block then resolves those fields, doing the necessary conversions and data fetches.

1/n as there are other convert_to fns I'd like to refactor.

## Test Plan 

How did you test the new or updated feature?

---
If your changes are not user-facing and not a breaking change, you can skip the following section. Otherwise, please indicate what changed, and then add to the Release Notes section as highlighted during the release process.

### Type of Change (Check all that apply)

- [ ] protocol change
- [ ] user-visible impact
- [ ] breaking change for a client SDKs
- [ ] breaking change for FNs (FN binary must upgrade)
- [ ] breaking change for validators or node operators (must upgrade binaries)
- [ ] breaking change for on-chain data layout
- [ ] necessitate either a data wipe or data migration

### CODE REVIEW

**Review by stefan-mysten — APPROVED** [review]
Thanks for cleaning this up @wlmyng

**Comment by amnn** [comment]
Thanks for this clean-up @wlmyng !  This also helps answer a question I had around how to avoid fetching fields that weren't in the query!  One question I had though:  What is your proposed rule of thumb for when to use `SimpleObject` vs when to use `Object`?  Reason I ask: I had thought that types that were purely data, without edges (like `GasCostSummary`) would be good candidates for remaining as `SimpleObject` but this PR ports that type too. (There's a clear cut case for porting `GasInput` in my opinion, because it has edges to `Object`s).

**Comment by wlmyng** [comment]
> What is your proposed rule of thumb for when to use `SimpleObject` vs when to use `Object`? Reason I ask: I had thought that types that were purely data, without edges (like `GasCostSummary`) would be good candidates for remaining as `SimpleObject` but this PR ports that type too. (There's a clear cut case for porting `GasInput` in my opinion, because it has edges to `Object`s).

Yeah that's a fair call-out. After diving into the distinctions between SimpleObject and Object within async-graphql, my take is that any object that requires a graphql type conversion (such as u64 to BigInt, exemplified by GasCostSummary) or necessitates a data retrieval would benefit from being ported. So if we need to do any kind of transformation, the type is better served as an object instead of a simple object. This might be overkill ... but as of now, I don't think for example the data provider needs to know what to convert u64 to, that can be the responsibility of the impl Object. If we later decide that we want to map u64 to another custom graphql type, the changes would be localized to that block.
By extension, we could have the Rust struct, which mirrors the GraphQL object name, encompass the necessary fields for generating the corresponding GraphQL object. I initially thought these structs could be wrapper types, so sui_graphql_rpc::GasCostSummary(sui_json_rpc_types::GasCostSummary) but 1. this would mean we couple the typings to another library 2. we pass a lot of & data and I didn't want to get into lifetimes lol

Lmk what your thoughts are. If that's too extensive, then I think in the very least we should port objects that have edges

**Comment by amnn** [comment]
I buy the separation of concerns around type conversions as well, thanks for clarifying @wlmyng ! I think that does mean basically everything gets turned into an `Object` rather than a `SimpleObject`, but that's okay with me, just wanted to make sure there was a rubrik we were following here.

**Pull request merged**
