### PR TITLE
[transaction input checker] Make batch rules more robust

### PR DESCRIPTION
**Pull request by tnowacki**
Some checks were not performed in batch for certain transaction kinds. While this might not be a problem now, it feels like it might cause an issue later if these rules are changed without changing them also for batch.

### CODE REVIEW

**Comment by lxfind** [comment]
I thought we are going to first remove Batch?

**Comment by tnowacki** [comment]
@gdanezis and other folks raised concerns of doing that since it is used for benchmarks? 

It doesn't matter too much as I found I could easily just disallow it from `Batch`. And when looking at the code for doing that, I found that the rules for `Batch` are busted :)

**Comment by lxfind** [comment]
This is not very obvious but those payment transactions can not actually show up in Batch, so it's not needed to recurse in it. But this doesn't hurt, I guess.

**Comment by tnowacki** [comment]
> This is not very obvious but those payment transactions can not actually show up in Batch, so it's not needed to recurse in it. But this doesn't hurt, I guess.

I suppose it's not _really_ necessary in the current setup for these validity checks + batch. It just felt sort of conceptually wrong. Not needed though, and since Batch will die at some 
point, happy to not land it if thats what we decide

**Review by amnn — APPROVED** [review]
Sentiment seems to be neutral to positive here, and the implementation seems fine, so accepting.

**Pull request merged**
