### PR TITLE
[RPC Server] Simplify the response schema for object_info

### PR DESCRIPTION
**Pull request by 666lcz**
The response returned by the existing `object_info` is too complicated for the client applications

## Before
```
{
    "Exists": [
        [
            "024f81362efe7404119b931bd5daa66e35d4e704",
            0,
            "ntEwRW9UM/UNNQkkAuunTtvranJ+3G5xjS7qDhz8A70="
        ],
        {
            "data": {
                "Move": {
                    "type_": {
                        "address": "0000000000000000000000000000000000000002",
                        "module": "Coin",
                        "name": "Coin",
                        "type_args": [
                            {
                                "struct": {
                                    "address": "0000000000000000000000000000000000000002",
                                    "module": "SUI",
                                    "name": "SUI",
                                    "type_args": []
                                }
                            }
                        ]
                    },
                    "contents": "Ak+BNi7+dAQRm5Mb1dqmbjXU5wQAAAAAAAAAAKCGAQAAAAAA"
                }
            },
            "owner": {
                "AddressOwner": "836f28fce574a84e4135725fdcb549679b09e62d"
            },
            "previous_transaction": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=",
            "storage_rebate": 0
        },
        {
            "WithTypes": {
                "type_": {
                    "address": "0000000000000000000000000000000000000002",
                    "module": "Coin",
                    "name": "Coin",
                    "type_args": [
                        {
                            "struct": {
                                "address": "0000000000000000000000000000000000000002",
                                "module": "SUI",
                                "name": "SUI",
                                "type_args": []
                            }
                        }
                    ]
                },
                "fields": [
                    {
                        "name": "id",
                        "layout": {
                            "struct": {
                                "WithTypes": {
                                    "type_": {
                                        "address": "0000000000000000000000000000000000000002",
                                        "module": "ID",
                                        "name": "VersionedID",
                                        "type_args": []
                                    },
                                    "fields": [
                                        {
                                            "name": "id",
                                            "layout": {
                                                "struct": {
                                                    "WithTypes": {
                                                        "type_": {
                                                            "address": "0000000000000000000000000000000000000002",
                                                            "module": "ID",
                                                            "name": "UniqueID",
                                                            "type_args": []
                                                        },
                                                        "fields": [
                                                            {
                                                                "name": "id",
                                                                "layout": {
                                                                    "struct": {
                                                                        "WithTypes": {
                                                                            "type_": {
                                                                                "address": "0000000000000000000000000000000000000002",
                                                                                "module": "ID",
                                                                                "name": "ID",
                                                                                "type_args": []
                                                                            },
                                                                            "fields": [
                                                                                {
                                                                                    "name": "bytes",
                                                                                    "layout": "address"
                                                                                }
                                                                            ]
                                                                        }
                                                                    }
                                                                }
                                                            }
                                                        ]
                                                    }
                                                }
                                            }
                                        },
                                        {
                                            "name": "version",
                                            "layout": "u64"
                                        }
                                    ]
                                }
                            }
                        }
                    },
                    {
                        "name": "value",
                        "layout": "u64"
                    }
                ]
            }
        }
    ]
}

```

## After
```
{
    "status": "Exists",
    "details": {
        "objectRef": {
            "objectId": "024f81362efe7404119b931bd5daa66e35d4e704",
            "version": 0,
            "digest": "ntEwRW9UM/UNNQkkAuunTtvranJ+3G5xjS7qDhz8A70="
        },
        "object": {
            "contents": {
                "fields": {
                    "id": {
                        "fields": {
                            "id": {
                                "fields": {
                                    "id": {
                                        "fields": {
                                            "bytes": "024f81362efe7404119b931bd5daa66e35d4e704"
                                        },
                                        "type": "0x2::ID::ID"
                                    }
                                },
                                "type": "0x2::ID::UniqueID"
                            },
                            "version": 0
                        },
                        "type": "0x2::ID::VersionedID"
                    },
                    "value": 100000
                },
                "type": "0x2::Coin::Coin<0x2::SUI::SUI>"
            },
            "owner": {
                "AddressOwner": "836f28fce574a84e4135725fdcb549679b09e62d"
            },
            "tx_digest": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="
        }
    }
}
```

There are still plenty of room for improvement(e.g., simplify the `contents` field), but that's for a separate PR

### CODE REVIEW

**Comment by patrickkuo** [comment]
Unfortunately this will break `RestGatewayClient`

https://github.com/MystenLabs/sui/blob/72dbf0bf4fd280b3bafed371aee7c6d3dad63828/sui/src/rest_gateway.rs#L191-L195

The plan was to simplifying the model once the JSON-RPC work is in, we will need to make this changes in `GatewayAPI` 
https://github.com/MystenLabs/sui/blob/72dbf0bf4fd280b3bafed371aee7c6d3dad63828/sui_core/src/gateway_state.rs#L176
instead of changing the model in the Rest layer, or else the `RestGatewayClient` implementation won't be able to talk to the rest server.

Also isn't the plan to move to JSON-RPC and remove the Rest server all together? The rest server will be removed soon....

**Comment by 666lcz** [comment]
@patrickkuo thanks for flagging this! The reason I was working on this PR is because I was working on the TypeScript SDK and found `ObjectRead` difficult to define with TypeScript.

> The plan was to simplifying the model once the JSON-RPC work is in, we will need to make this changes in GatewayAPI

This sounds great! I'll then base this PR against `pat/jsonrpsee` and change on the `GatewayAPI` level then. What do you think?

> Also isn't the plan to move to JSON-RPC and remove the Rest server all together? The rest server will be removed soon

I thought the conclusion is to [keep](https://mysten-labs.slack.com/archives/C034XQYJYJ3/p1648853253978619?thread_ts=1648844988.616839&cid=C034XQYJYJ3) the REST server code and revisit the decision sometime later. However, I am totally okay with remove the REST server code for now if it slows us down. The primary change in this PR is the conversion from `ObjectRead` to a response object, which can be used for json-rpc as well.

**Comment by patrickkuo** [comment]
This PR will fix part of this issue https://github.com/MystenLabs/sui/issues/237

**Comment by 666lcz** [comment]
@patrickkuo , there're two ways for fixing the issue you mentioned
1. Change the response at the `GatewayAPI` level as you suggested
2. Add a new RPC endpoint to return the "Parsed" object info in addition to the existing `get_object_info` endpoint.

I ended up implementing Option 2 for the following reasons:
1. Option 2 takes much less change, so that I can unblock client side work earlier
2. Right now the RPC server serves two purpose: One is to act as a `GatewayAPI`(which needs to be compatible with the embedded gateway) for the wallet CLI; and the other is to provide a developer friendly interface to all other external and internal applications. I consider the former to be more barebone and low-level, while the latter is more processed and more developer friendly. It makes sense to provide both a high level API and a low level API.

Let me know if you have any concern.

**Comment by patrickkuo** [comment]
> @patrickkuo , there're two ways for fixing the issue you mentioned
> 
> 1. Change the response at the `GatewayAPI` level as you suggested
> 2. Add a new RPC endpoint to return the "Parsed" object info in addition to the existing `get_object_info` endpoint.
> 
> I ended up implementing Option 2 for the following reasons:
> 
> 1. Option 2 takes much less change, so that I can unblock client side work earlier
> 2. Right now the RPC server serves two purpose: One is to act as a `GatewayAPI`(which needs to be compatible with the embedded gateway) for the wallet CLI; and the other is to provide a developer friendly interface to all other external and internal applications. I consider the former to be more barebone and low-level, while the latter is more processed and more developer friendly. It makes sense to provide both a high level API and a low level API.
> 
> Let me know if you have any concern.

Sounds good to me, let's have this endpoint to unblock others, I will investigate if it make sense to implement option 1 after this.

**Review by patrickkuo — APPROVED** [review]
LGTM!

**Pull request merged**
