### PR TITLE
[Other]Rename udo systemctl stop sui-node[201~ to udo systemctl stop sui-no…

### PR DESCRIPTION
**Pull request by shaflow01**
## Description 

I encountered an issue while cloning the repository in Windows, which seems to be caused by filenames in the repository not conforming to NTFS file system naming conventions.
41ded9223e223b9700aba57c4be8f3e

## Test plan 

Although it can be resolved by setting it through git config, renaming the files will be more convenient.

---

## Release notes

Check each box that your changes affect. If none of the boxes relate to your changes, release notes aren't required.

For each box you select, include information after the relevant heading that describes the impact of your changes that a user might notice and any actions they must take to implement updates. 

- [ ] Protocol: 
- [ ] Nodes (Validators and Full nodes): 
- [ ] Indexer: 
- [ ] JSON-RPC: 
- [ ] GraphQL: 
- [ ] CLI: 
- [ ] Rust SDK:

### CODE REVIEW

**Comment by shaflow01** [comment]
@ronny-mysten

**Comment by shaflow01** [comment]
@ronny-mysten Could you please check this change?It still troubles me in git clone

**Comment by shaflow01** [comment]
@amnn Could you please help me check this change? It still troubles me

**Comment by amnn** [comment]
Thanks for flagging @shaflow01, I think I know what's going on. I noticed that we had a Windows CI issue recently, and I think it's related to this. Fix coming soon.

**Comment by shaflow01** [comment]
Thank you for your kindly reply.Waiting for it to be fixed

**Comment by amnn** [comment]
Landed the fix in `main`, you should be able to pull now!

**Pull request closed without merging**
