### PR TITLE
crypto: Breakdown crypto.rs in sui-framework

### PR DESCRIPTION
**Pull request by joyqvq**
https://github.com/MystenLabs/sui/issues/6288

breakdown with some minor error code and test cleanups.

### CODE REVIEW

**Review by kchalkias — COMMENTED** [review]
let's rename `ecdsa` to `ecdsa_k1`

**Review by kchalkias — COMMENTED** [review]
let's rename `ecdsa` to `ecdsa_k1`

**Review by huitseeker — COMMENTED** [review]
This mostly LGTM, thanks for the nice work!
The only thing I'd add is that the elliptic_curve module is really defining things that are about pedersen commitments on a prime order group, and reused by some of the bulletproof constructions. It can be hard for a reader without context to parse that. Would it be possible to add this context to the rustdoc of the file, if not the file name?

**Comment by joyqvq** [comment]
what about: 
create new module that contains: 
- add/substract_ristretto_point
- pederson_commitment

in this elliptic_curve module:
- scalar from bytes/u32
?

**Comment by joyqvq** [comment]
> This mostly LGTM, thanks for the nice work! The only thing I'd add is that the elliptic_curve module is really defining things that are about pedersen commitments on a prime order group, and reused by some of the bulletproof constructions. It can be hard for a reader without context to parse that. Would it be possible to add this context to the rustdoc of the file, if not the file name?

what about:
create new module that contains:

add/substract_ristretto_point
pederson_commitment
in this elliptic_curve module:

scalar from bytes/u64
?

**Review by huitseeker — COMMENTED** [review]
> what about:
> create new module that contains:

Yes, that's completely fine. I guess what I was saying was more about comments (or part of a README) that explains the logic rather than optimizing for not needing those comments.

**Comment by joyqvq** [comment]
> > what about:
> > create new module that contains:
> 
> Yes, that's completely fine. I guess what I was saying was more about comments (or part of a README) that explains the logic rather than optimizing for not needing those comments.

got it, added to the elliptic_curve.rs and elliptic_curve.move comments. the latter is used to auto generate move documentations that should be visible for the reader to consume.

**Review by kchalkias — APPROVED** [review]
<3

**Pull request merged**
