### PR TITLE
Don't retry non-recoverable errors in benchmark

### PR DESCRIPTION
**Pull request by mystenmark**
This was causing simtest failures due to the following sequence of events:

- Client submits a tx, fails to gather an effects cert, but the tx is included in the final checkpoint
- after reconfiguration, the client retries. validators re-sign the effects, but client fails to accept the new effects cert because it does not yet know about the new committee
- validators prune tx
- client retries again
- client now gets ObjectVersionUnavailableForConsumption

The transaction can never succeed (from the client's POV) after this point, so it retries forever, generating enough errors to cause the test to fail.

### CODE REVIEW

**Comment by lxfind** [comment]
Not sure if this is the right thing to do to be honest. I am surprised we have more than 100 non-recoverable errors in the first place

**Comment by mystenmark** [comment]
Its not 100 independent errors, its a smaller number of errors being retried dozens of times

**Comment by emmazzz** [comment]
Would like to understand why we have these errors better.
It sounds like the errors include the missing committee error and the object unavailable error. 
> but client fails to accept the new effects cert because it does not yet know about the new committee 

The missing committee error is caused by the client not yet knowing the new committee. Do we understand why it doesn't know the new committee?

> validators prune tx
client retries again
client now gets ObjectVersionUnavailableForConsumption

So the fix for this error should be turning off pruning on the benchmark validator?

**Comment by mystenmark** [comment]
- The missing committee error is the real root cause of this
- The error occurs because the transaction can be executed before reconfiguration happens. There is no simple way to prevent this since they occur over entirely different channels.
- Turning off pruning would fix it in the tests, but the missing committee error is something that can (and maybe has) happened in production.

**Review by emmazzz — APPROVED** [review]

**Comment by mystenmark** [comment]
I'm going to merge this to hopefully clear the nightly simtest errors - happy to keep discussing if there's a better way to handle this. (as i said before i think fixing the missing committee error is the best way, although i'm not sure exactly how we should implement that)

**Pull request merged**
