### PR TITLE
Allow online retry of interrupted transactions. Add tests and fix bugs.

### PR DESCRIPTION
**Pull request by mystenmark**

### CODE REVIEW

**Comment by lxfind** [comment]
We probably can revert changes in https://github.com/MystenLabs/sui/pull/3718 given that we now allow retrying a tx that already has a dbguard?

**Comment by mystenmark** [comment]
> We probably can revert changes in #3718 given that we now allow retrying a tx that already has a dbguard?

I think we should keep both - this change allows a user to retry directly, but if they don't, it would still be good for the execution driver to push the cert through.

**Comment by lxfind** [comment]
Both Gossip and checkpoint would be trying to execute this I think. I don't mind also doing it here, but I think the marginal benefit is tiny and I am all for deleting code

**Review by lxfind — APPROVED** [review]

**Comment by mystenmark** [comment]
> Both Gossip and checkpoint would be trying to execute this I think. I don't mind also doing it here, but I think the marginal benefit is tiny and I am all for deleting code

@gdanezis has often made strong arguments for having a backstop that is guaranteed to make progress, so I'd like to hear his opinion here. I can remove in a separate PR if we decide its not necessary

**Pull request merged**
