### PR TITLE
source-validation-service: add kai finance to config.toml

### PR DESCRIPTION
**Pull request by kklas**
## Description 

Added Kai Finance repo for source validation.

## Test Plan 

Tested locally with curl and it works.

---
If your changes are not user-facing and not a breaking change, you can skip the following section. Otherwise, please indicate what changed, and then add to the Release Notes section as highlighted during the release process.

### Type of Change (Check all that apply)

- [ ] protocol change
- [ ] user-visible impact
- [ ] breaking change for a client SDKs
- [ ] breaking change for FNs (FN binary must upgrade)
- [ ] breaking change for validators or node operators (must upgrade binaries)
- [ ] breaking change for on-chain data layout
- [ ] necessitate either a data wipe or data migration

### CODE REVIEW

**Review by rvantonder — APPROVED** [review]
Thanks @kklas! Will comment below when this is live

**Comment by rvantonder** [comment]
Live here: https://suiexplorer.com/object/0x7a27caf0a07d7a5aceba8dfba89228c38a4b901389fed880d43c2c5ceb8651aa

thanks again @kklas!

**Comment by kklas** [comment]
Thanks @rvantonder! Have you considered making it possible to support multiple versions via git refs / tags? E.g. I can say in the config v1 is at this tag, v2 is at this other tag...

**Comment by rvantonder** [comment]
The config allows multiple branches / tags (not commit shas yet). I think there may be one thing to handle in the implementation to support actually serving it though. Based on your suggestion, a name field like "v1" "v2" to disambiguate might also be helpful. All in all, pretty easy to support with a bit of work, I'll take a look at this when I have time!

**Pull request merged**
