### PR TITLE
feat(wallet-adapter): integrate with SUIET wallet

### PR DESCRIPTION
**Pull request by bruceeewong**
This is the commit for wallet adapter from [Suiet Wallet team](https://twitter.com/suiet_wallet). We hope to integrate with the official sui wallet-adapter kit and we've submitted the adapter codes. Please review the pull request, thanks!

### CODE REVIEW

**Comment by Jordan-Mysten** [comment]
@bruceeewong We're planning on updating our wallet adapters in the near future to be based on the [new wallet standard](https://github.com/wallet-standard/wallet-standard/). I'd recommending implementing this at the wallet-level if possible, as it'll automatically be supported in the upcoming standardized wallet adapter.

**Comment by fredliang44** [comment]
@Jordan-Mysten we would like to know will the wallet adapters released in 1 week?

the reason why we are asking because we are integrating with the ecosystem projects, if it takes longer we are hoping to get merged first. Then we will adjust for the wallet standard then.

**Comment by bruceeewong** [comment]
> @bruceeewong We're planning on updating our wallet adapters in the near future to be based on the [new wallet standard](https://github.com/wallet-standard/wallet-standard/). I'd recommending implementing this at the wallet-level if possible, as it'll automatically be supported in the upcoming standardized wallet adapter.

Thanks for the reply~ As my teammate Fred said, we have several dev partners who want to integrate with our wallet. We prefer to let them use the sui official wallet kit to dev & debug. So if the new standard couldn't release in short time, how about that your team merges the current pr? Of course we'd love to follow the new standard in the future. Feel free to comment back, thanks again!

**Comment by Jordan-Mysten** [comment]
@bruceeewong @fredliang44 I can let you know more concrete timelines next week. My main concern with merging this as-is is that this package would need to be deprecated and removed after the standardized adapter lands. I ideally want to minimize the amount of packages we need to deprecate, but I'm also sympathetic to your desire to enable developer partners. It also should be possible for y'all to separately publish a wallet adapter (e.g. a package like `@suiet/wallet-adapter`), which should unblock early dev partners.

**Comment by bruceeewong** [comment]
> @bruceeewong @fredliang44 I can let you know more concrete timelines next week. My main concern with merging this as-is is that this package would need to be deprecated and removed after the standardized adapter lands. I ideally want to minimize the amount of packages we need to deprecate, but I'm also sympathetic to your desire to enable developer partners. It also should be possible for y'all to separately publish a wallet adapter (e.g. a package like `@suiet/wallet-adapter`), which should unblock early dev partners.

Make sense, thanks anyway! We'll keep watching on it.

**Comment by fredliang44** [comment]
@Jordan-Mysten Hi Jordan, we have publish our own adapter and some project already using them, really appreciate your help. I wonder can we make a PR to add our [adapter package repo](https://github.com/suiet/wallet-adapter) in the README.md of the sui wallet adapter dir, so anyone who willing to integrate multiple wallets at once can find us there.

Because we are worrying that user who import the `@mysten/wallet-adapter-all-wallets` package would expect all wallets are included there, but actually we are published with an individual package.

**Pull request closed without merging**
