### PR TITLE
Privkey

### PR DESCRIPTION
**Pull request by robert2687**
## Description 

Describe the changes or additions included in this PR.

## Test Plan 

How did you test the new or updated feature?

---
If your changes are not user-facing and not a breaking change, you can skip the following section. Otherwise, please indicate what changed, and then add to the Release Notes section as highlighted during the release process.

### Type of Change (Check all that apply)

- [ ] protocol change
- [ ] user-visible impact
- [ ] breaking change for a client SDKs
- [ ] breaking change for FNs (FN binary must upgrade)
- [ ] breaking change for validators or node operators (must upgrade binaries)
- [ ] breaking change for on-chain data layout
- [ ] necessitate either a data wipe or data migration

### CODE REVIEW

**Comment by joyqvq** [comment]
what'a context here to open a new pr?

**Comment by stefan-mysten** [comment]
@robert2687 I think you did not want to make a PR but simply to pull in the branch into your own fork.

**Comment by amnn** [comment]
I'm going to close this PR, as it seems like it wasn't intentional, but @robert2687, if I have that wrong, please feel free to re-open it and update the PR description with what you're trying to achieve.

**Comment by robert2687** [comment]
> @robert2687 I think you did not want to make a PR but simply to pull in the branch into your own fork.

Yes that's right

**Comment by robert2687** [comment]
> I'm going to close this PR, as it seems like it wasn't intentional, but @robert2687, if I have that wrong, please feel free to re-open it and update the PR description with what you're trying to achieve.

No It wasn't intentional. I was tired and ill and try learning. Now I working on different projects ,but maybe i will check it again when I finish.

**Pull request closed without merging**
