### PR TITLE
[docs] Format code in `crates/sui-framework/docs/sui-framework/bcs.md`

### PR DESCRIPTION
**Pull request by ooooo-create**
## Description 

Format the code for easy reading.

## Test plan 

How did you test the new or updated feature?

---

## Release notes

Check each box that your changes affect. If none of the boxes relate to your changes, release notes aren't required.

For each box you select, include information after the relevant heading that describes the impact of your changes that a user might notice and any actions they must take to implement updates. 

- [ ] Protocol: 
- [ ] Nodes (Validators and Full nodes): 
- [ ] Indexer: 
- [ ] JSON-RPC: 
- [ ] GraphQL: 
- [ ] CLI: 
- [ ] Rust SDK:

### CODE REVIEW

**Comment by ooooo-create** [comment]
> Thanks for pointing this out @ooooo-create . Unfortunately, these docs are autogenerated by rust so these changes would be overwritten on next build. I checked the source and it's formatted correctly there but the whitespace is ignored on output. I'll update this PR this week with the change. And I'm marking this as `Request changes` to keep track, but to be clear, there is not anything else for you to do on this. Thanks again.

I see now, thank you very much!

**Comment by ronny-mysten** [comment]
----------------------------------------------------------

**Comment by ronny-mysten** [comment]
I tried a few different approaches here with no luck. To fix, the change will have to be made to the source file: crates/sui-framework/packages/sui-framework/sources/bcs.move. Then, run `cargo doc --workspace --exclude "sui-benchmark" --no-deps`. Then check the output at crates/sui-framework/docs/sui-framework/bcs.md. The issue with all my approaches was that this content is contained within a code block, so trying to add things like `&nbsp;` and similar to force whitespace are rendered as is from the markdown transform. Because the change is cosmetic (although admittedly annoying), closing as not going to fix. Feel free to reopen if you have ideas on how to fix. 

Thanks again for taking the time. Sorry I couldn't help more.

**Comment by ooooo-create** [comment]
> I tried a few different approaches here with no luck. To fix, the change will have to be made to the source file: crates/sui-framework/packages/sui-framework/sources/bcs.move. Then, run `cargo doc --workspace --exclude "sui-benchmark" --no-deps`. Then check the output at crates/sui-framework/docs/sui-framework/bcs.md. The issue with all my approaches was that this content is contained within a code block, so trying to add things like `&nbsp;` and similar to force whitespace are rendered as is from the markdown transform. Because the change is cosmetic (although admittedly annoying), closing as not going to fix. Feel free to reopen if you have ideas on how to fix.
> 
> Thanks again for taking the time. Sorry I couldn't help more.

Hi, I try to change the code block(three backtick) to the html (`<pre><code>`) in `crates/sui-framework/packages/sui-framework/sources/bcs.move`, and add `&nbsp;` to force whitespace.Then run `cargo doc --workspace --exclude "sui-benchmark" --no-deps`, the code block in `bcs.md` seems work well in local.
image
image
but i am not sure to add `&nbsp;` in move file is a good way, it looks too long, lucky we only need up to four `&nbsp;` in a line.
At this time, because the `md` is autogened. I have a idea(just a idea, Hasn't tried yet.) to improve the autogen code to adapt the code block .

**Pull request closed without merging**
