### PR TITLE
Announce Bullshark and Shared Objects in Learn See what's new section

### PR DESCRIPTION
**Pull request by Clay-Mysten**

### CODE REVIEW

**Comment by Clay-Mysten** [comment]
Thanks to @mwtian for the review, input and approval of the replacement change. Here is another to announce Bullshark:
https://github.com/MystenLabs/sui/pull/4238

If we should also add to the See what's new section of the docs.sui.io landing page, please let me know. Thanks!

**Review by mwtian — APPROVED** [review]
Looks good! I thought Sui always had shared objects and maybe we added docs on them recently? But I don't have enough context on if shared objects are new to readers.

**Comment by Clay-Mysten** [comment]
> Looks good! I thought Sui always had shared objects and maybe we added docs on them recently? But I don't have enough context on if shared objects are new to readers.

Per @sblackshear we soft launched support in June and slowly ramped up full support.

**Comment by mwtian** [comment]
> > Looks good! I thought Sui always had shared objects and maybe we added docs on them recently? But I don't have enough context on if shared objects are new to readers.
> 
> Per @sblackshear we soft launched support in June and slowly ramped up full support.

Sounds good.

**Pull request merged**
