### PR TITLE
pick(19817): graphql: port MovePackage queries to full_objects_history

### PR DESCRIPTION
**Pull request by amnn**
## Description

Spotted that MovePackage queries were still using `objects_history`, which is not going to work after that table gets pruned to two epochs.

This PR replaces queries to `objects_history` with queries to `full_objects_history`, with support from `objects_version` and `packages` to fetch the checkpoint sequence number where necessary.

## Test plan

Existing tests:

```
sui$ cargo nextest run -p sui-graphql-e2e-tests
```

And ran the following queries on the mainnet DB:

```graphql
query AllPackages($after: String) {
  packages(first: 5 after: $after) {
    pageInfo {
      hasNextPage
      endCursor
      startCursor
    }
    nodes {
      address
      version
    }
  }
}

query AllPackagesBack($before: String) {
  packages(last: 5 before: $before) {
    pageInfo {
      hasNextPage
      endCursor
      startCursor
    }
    nodes {
      address
      version
    }
  }
}

query SystemPackages($after: String) {
  packageVersions(address: "0x2" first: 5 after: $after) {
    pageInfo {
      hasNextPage
      endCursor
      startCursor
    }

    nodes {
      address
      version
    }
  }
}

query SystemPackagesBack($before: String) {
  packageVersions(address: "0x2" last: 5 before: $before) {
    pageInfo {
      hasNextPage
      endCursor
    }

    nodes {
      address
      version
    }
  }
}

query UserPackage($after: String) {
  packageVersions(
    address: "0xbc3df36be17f27ac98e3c839b2589db8475fa07b20657b08e8891e3aaf5ee5f9"
		first: 5
    after: $after
  ) {
    pageInfo {
      hasNextPage
      endCursor
      startCursor
    }
    nodes {
      address
      version
    }
  }
}
```

---

## Release notes

Check each box that your changes affect. If none of the boxes relate to
your changes, release notes aren't required.

For each box you select, include information after the relevant heading
that describes the impact of your changes that a user might notice and
any actions they must take to implement updates.

- [ ] Protocol: 
- [ ] Nodes (Validators and Full nodes): 
- [ ] Indexer: 
- [ ] JSON-RPC: 
- [ ] GraphQL: 
- [ ] CLI: 
- [ ] Rust SDK:
- [ ] REST API:

### CODE REVIEW

**Review by ebmifa — APPROVED** [review]

**Comment by unmaykr-aftermath** [comment]
Hey @amnn, I noticed this PR and it made me wonder: why not get the `MovePackage` contents from `objects` instead? AFAIK, Move packages are immutable and thus would stay in the live `objects` table forever, unless it is pruned.

**Comment by amnn** [comment]
It's because queries to the live objects table are more expensive for GraphQL because they are consistent -- they require querying from `objects_snapshot` and `objects_history` and then reconciling the results.

**Comment by unmaykr-aftermath** [comment]
To be clear, I'm asking this since we may not wanna keep `full_objects_history` and I see `objects` as a potential alternative source to get the serialized package contents.

> It's because queries to the live objects table are more expensive for GraphQL because they are consistent -- they require querying from `objects_snapshot` and `objects_history` and then reconciling the results.

What I'm not grasping is why queries to immutable objects would have to go through this.

AFAIK, `objects` stores all live objects, including packages. That implies all package versions will live in `objects` - under different `object_id`s because package upgrades are actually new objects - and never leave that table. Given that `objects` has `checkpoint_sequence_number`, we would be able to filter the table by `<= checkpoint_viewed_at` to retain consistency (from the packages history POV).

## Edit

I found out that `checkpoint_sequence_number` was removed in [this migration](https://github.com/MystenLabs/sui/blob/3ec52d01e3af8d263871a15090b7b1eb5d5c6350/crates/sui-indexer/migrations/pg/2024-09-10-195655_drop-df-columns/up.sql#L5). The rationale for that is not really clear to me.

So it does seem that `full_objects_history` is the way to go here. On our side, however, since we haven't caught up to the latest schema changes yet, I might decide to skip that `checkpoint_sequence_number` removal from `objects` in order to use it as a source for the serialized package contents, while potentially allowing us to rely less on `full_objects_history`

**Comment by amnn** [comment]
Ah, I didn't realise you were running a version of this stack yourself, let me share some deeper context:

- One important thing to note is that `objects` is not used by the GraphQL schema anywhere -- it is used by the JSON-RPC schema, and in a world where we only had GraphQL, we would only have `objects_snapshot` (which is like `objects`, but lagging behind by a fixed delay -- currently between 300 and 900 checkpoints) and supplement that with `objects_history`, which is how we query the live object set for any checkpoint within the consistent range. So at a very basic level, the reason why we would need to go through the consistent reads path is that this is how we fetch live objects, regardless of whether they are immutable or not (if we used just `objects_snapshot`, we would miss objects that were created in the last couple of minutes). 

- Another concern is that we want the response from this query to be "consistent", meaning that if you claim to be querying at some checkpoint `C` while the network (and indexer) are at `C + n`, and there was some package introduced at `C + k`, `0 < k <= n`, then the query should not return that package.

- The other reason why the packages query needs to rely on `full_objects_history` is to deal with the system packages. These packages are updated in place even though they are immutable, so if you want to get a historical version of a system package (which this API does support), then you need to go through `full_objects_history`.

- Final thing to point out is that there is a `packages` table -- this tracks the latest version of every package that we are aware of and this is what powers type and layout resolution in the service. Initially, I did try to implement the `MovePackage` queries using this table at some point, but here's where that broke down, and why ultimately I opted to implement these queries using the objects tables:
  - That table only stores the latest version of each package -- this is important for keeping package fetching efficient for type resolution -- it means that we can efficiently multi-fetch packages -- but it means that we can't use this table for system package queries.
  - That table doesn't include enough information to construct the `Object` that a package came from (this was true at the time anyway, maybe with the recent migrations we could revisit that).

I'm curious to hear your thoughts on `full_objects_history` though, and why you want to rely on it less. Is it a footprint issue, or is it something more fundamental? Reason I ask is that we do plan to rely on this kind of table more in future, and offload queries that require fetching actual object contents to it (but make it possible to fetch object references from the other tables), and it will also ultimately replace `objects_history` which is actually a much larger (~3x larger per row, on average), table.

Even longer term, we have plans to offload these tables to a dedicated key-value store, so they won't even be in the indexer's tables anymore. At that point, the plan is to have an abstraction in GraphQL for key-value fetches, and third parties would have a couple of choices for providing something that conforms to that interface (these are all options, but we haven't settled on the set of them we would opt for):

- Everything in one table, like today.
- Separate PG DBs for key-value data and everything else.
- Use Mysten's KV tables, but pay for reads.
- Run your own KV store and talk to that.
- Serve KV reads from a fullnode (this requires some work to improve the pruning story on fullnodes so that it's feasible to store multiple days/weeks/months of data).

**Comment by unmaykr-aftermath** [comment]
I appreciate the time and effort you put into the response! I know how busy you guys are. I tried to be brief; there's only one real question at the end.

> * One important thing to note is that `objects` is not used by the GraphQL schema anywhere -- it is used by the JSON-RPC schema, and in a world where we only had GraphQL, we would only have `objects_snapshot` [...] and supplement that with `objects_history`

I had noticed indeed that the GraphQL server never uses it. I tried finding a use for it before with no success.

> * The other reason why the packages query needs to rely on `full_objects_history` is to deal with the system packages. These packages are updated in place even though they are immutable, so if you want to get a historical version of a system package (which this API does support), then you need to go through `full_objects_history`.

I see. I forgot that system packages change in-place. That and the fact that `objects` does not have `checkpoint_sequence_number` now would kill all consistency hopes for the packages query backed by that table.

> * Final thing to point out is that there is a `packages` table -- this tracks the latest version of every package that we are aware of and this is what powers type and layout resolution in the service. Initially, I did try to implement the `MovePackage` queries using this table at some point, but here's where that broke down, and why ultimately I opted to implement these queries using the objects tables: [...]

Yeah last I checked `packages` stores only the serialized `MovePackage` unfortunately. I did notice however that the primary key of table (https://github.com/MystenLabs/sui/blob/testnet-v1.35.1/crates/sui-indexer/src/schema.rs#L233-L241) includes the package version. Maybe it's possible to change the `on_conflict` clause (https://github.com/MystenLabs/sui/blob/testnet-v1.35.1/crates/sui-indexer/src/store/pg_indexer_store.rs#L825) to include the version so that we store all the system package versions since they don't change in `object_id`.

> I'm curious to hear your thoughts on `full_objects_history` though, and why you want to rely on it less. Is it a footprint issue, or is it something more fundamental? Reason I ask is that we do plan to rely on this kind of table more in future, and offload queries that require fetching actual object contents to it (but make it possible to fetch object references from the other tables), and it will also ultimately replace `objects_history` which is actually a much larger (~3x larger per row, on average), table.

Just storage footprint really. We have been running a custom indexing + pruning workflow. We never pruned the object history between the `objects_snapshot` and `objects` watermarks, but anything older than that was subject to our custom pruning setup (we keep the full history for some protocols including their upgrades, the rest could be pruned beyond the last few epochs).

To be fair however, I did notice that the storage requirements for `full_objects_history` are much lower than `objects_history`.

> Even longer term, we have plans to offload these tables to a dedicated key-value store, so they won't even be in the indexer's tables anymore. At that point, the plan is to have an abstraction in GraphQL for key-value fetches, and third parties would have a couple of choices for providing something that conforms to that interface (these are all options, but we haven't settled on the set of them we would opt for): [...]

A general question regarding future plans: is there a public channel where the communications around the indexer + GraphQL take place? Would be good to stay up to speed with the general roadmap and perhaps have a space for discussions about users' needs/questions. 

For instance, I'm running a custom indexer because we have other `WorkerPool`s that process the checkpoints produced by our co-located Full Node. Hence why I'm keeping tabs on SQL schema changes, so that we are compatible with the GraphQL implementation (running an outdated one right now).

Appreciate your time again.

**Comment by amnn** [comment]
> Maybe it's possible to change the on_conflict clause (https://github.com/MystenLabs/sui/blob/testnet-v1.35.1/crates/sui-indexer/src/store/pg_indexer_store.rs#L825) to include the version so that we store all the system package versions since they don't change in object_id.

The concern is more on the read side than the write side -- we can definitely write out all the packages, but today we really benefit from having a cheap way to batch load packages by ID, we have to work a little bit harder to write an efficient query to fetch them -- I think it might be possible to do with some postgres extensions, something like:

```
SELECT DISTINCT ON (package_id) ... FROM package WHERE package_id IN (...) ORDER BY package_id, version DESC;
```

But given we hit this table quite a lot for all the type and layout related queries that power other queries, (anything that touches an object). It's quite sensitive to any performance changes, so if we can solve the problem some other way we would probably try to.

> To be fair however, I did notice that the storage requirements for full_objects_history are much lower than objects_history.

Indeed, it's about 4x less, at about ~3.5TB for the full history so far. And the plan is that for the kind of scenario you're talking about, you could either opt to pay to use someone else's key-value store for object content queries, or serve them from your own fullnode.

> is there a public channel where the communications around the indexer + GraphQL take place? Would be good to stay up to speed with the general roadmap and perhaps have a space for discussions about users' needs/questions.

We don't have this at the moment, unfortunately -- we don't want to make any promises just yet on the schema, or how it will be to run. Once we are confident that it can stand up to a variety of production workloads, we will standardise on it, and do the official release. At that point we'll spin up the groups etc. We're happy to discuss anything -- it's all in the open -- we just can't commit to keeping things as they are until we're happy with it.

> I'm running a custom indexer because we have other WorkerPools that process the checkpoints produced by our co-located Full Node

Interesting, tell me more -- does that mean you are running your own indexer, which also populates the schema used by GraphQL? Is it based on our indexer codebase, or completely fresh?

**Comment by unmaykr-aftermath** [comment]
> But given we hit this table quite a lot for all the type and layout related queries that power other queries, (anything that touches an object). It's quite sensitive to any performance changes, so if we can solve the problem some other way we would probably try to.

I see, you have good reasons to keep it that way. I think on our side, if `full_objects_history` ever becomes a problem in size, we can solve it by doing some custom pruning, making sure to keep all packages.
 

> We don't have this at the moment, unfortunately -- we don't want to make any promises just yet on the schema, or how it will be to run. Once we are confident that it can stand up to a variety of production workloads, we will standardise on it, and do the official release. At that point we'll spin up the groups etc. We're happy to discuss anything -- it's all in the open -- we just can't commit to keeping things as they are until we're happy with it.

Understood. I'll keep watching the GH then :)


> Interesting, tell me more -- does that mean you are running your own indexer, which also populates the schema used by GraphQL? Is it based on our indexer codebase, or completely fresh?

I don't know if I can talk about it publicly just yet. Perhaps in private

**Pull request merged**
