### PR TITLE
fix typos

### PR DESCRIPTION
**Pull request by howjmay**

### CODE REVIEW

**Comment by stefan-mysten** [comment]
@howjmay thanks for the PR!

**Comment by howjmay** [comment]
thank you too

**Comment by stefan-mysten** [comment]
@mwtian these changes look good to me, but I'd love another pair of eyes when you get a moment.

**Review by stefan-mysten — APPROVED** [review]

**Review by mwtian — APPROVED** [review]

**Comment by howjmay** [comment]
thanks

**Pull request merged**
