### PR TITLE
Sadhan/fix_notification_ticket

### PR DESCRIPTION
**Pull request by sadhansood**
Add some metrics, and make sure we use Drop to properly remove the ticket from blocking batching system if it is not already invoked.

### CODE REVIEW

**Comment by lxfind** [comment]
This also means we are essentially reverting the previous fix for https://github.com/MystenLabs/sui/issues/4754 and will still have the described issue there, right?

**Comment by sadhansood** [comment]
I looked at the code in batch service again and it seems like this is not really a problem:
```// Always stop at low watermark guarantees that transactions are
    // always returned in order.
    let last_safe = transaction_notifier.low_watermark();

    // Get the stream of updates since the last point we requested ...
    if let Ok(iter) = transaction_notifier
        .clone()
        .state
        .perpetual_tables
        .executed_sequence
        .iter()
        .skip_to(&next_seq)
    {
        // ... continued here with take_while. And expand the buffer with the new items.
        temp_buffer.extend(
            iter.take_while(|(tx_seq, _tx_digest)| *tx_seq < last_safe)
                .map(|(tx_seq, _tx_digest)| (tx_seq, _tx_digest)),
        );

        // Update what the next item would be to no re-read messages in the buffer
        if !temp_buffer.is_empty() {
            next_seq = temp_buffer[temp_buffer.len() - 1].0 + 1;
        }
```
Here we just skip over missing txns while iterating over executed_sequence table. For example - if next_seq is 100, low_matermark is 200 and we have missing tx 150 in b/w, we will just skip over it while making a batch. But it is fine, because during a retry this certificate will get a new higher sequence number and will get added to executed_sequence table and a future batch.

**Comment by lxfind** [comment]
But the sequence number we get from the ticket system is just a proposed sequence number. In the lock service, I think it tries to detect if a previous sequence number has been assigned, and if so use that one instead?

**Comment by sadhansood** [comment]
Oh damn, that is right. Here is an alternate proposal which is some work: we add another table called lagging_executed_sequence which has committed txns get appended whose assigned_seq_num < proposed_seq_num (retried txns) so we know these have likely missed the batching train. When batch service is calling iter_from() it'll read from both tables and return an ordered stream from executed_sequence (as it does today) and an unordered one from lagging_executed_sequence table (since we are appending to this table as they are getting committed) which is there to fill the holes in first one.

**Comment by mystenmark** [comment]
It seems to me that we need to do the following:

- Once a sequence number is committed to the lockservice, we do not release it until the tx is fully committed.
- But before that point, we should release on drop, to indicate that the sequence number will not be used.
- note that during retry we may have two sequences that need to be notified - the proposed and the previously-committed.

**Comment by lxfind** [comment]
While we are figuring out how to properly fix the issue, could we at a minimum merge the metric changes? We need them to help get more signal in understanding why batch stalled. Maybe even add more debug logs.

**Comment by sadhansood** [comment]
Sure thing, let me send that out as a different PR while we keep the discussion ongoing here

**Pull request closed without merging**
