### PR TITLE
added select coin

### PR DESCRIPTION
**Pull request by Jibz1**
This is a breakout from [#8307](https://github.com/MystenLabs/sui/pull/8307)
- CoinType selection
- added payAllSui 
- use react query for coin transfer 
- use inputWithAction component
- Remove redux code for coin transfer 

https://user-images.githubusercontent.com/8676844/219511480-312fa9e2-b900-4506-a8d8-7b827b45b25f.mov

Screenshot 2023-02-24 at 9 11 17 PM

### CODE REVIEW

**Review by mystie711 — APPROVED** [review]

**Comment by mystie711** [comment]
just noticing this. Could we also fix the rounded corner value for the input fields @Jibz1 so they are all same?

image

**Comment by Jibz1** [comment]
@mystie711 you mean for the address field?

**Comment by mystie711** [comment]
> @mystie711 you mean for the address field?

It's the amount input field that appears to be off-spec.

**Comment by Jibz1** [comment]
Closing this PR for https://github.com/MystenLabs/sui/pull/8674

**Pull request closed without merging**
