### PR TITLE
[cli] Implement Display for BalanceChange type

### PR DESCRIPTION
**Pull request by stefan-mysten**
## Description 

Implements the Display trait for the `BalanceChange` type. This is part of a larger effort (and multiple PRs) in implementing a nice format output for `SuiTransactionBlockResponse` in the CLI, following @laura-makdah's excellent formatting in `SuiTransactionBlockEffects`.

## Test Plan 

image

---
If your changes are not user-facing and not a breaking change, you can skip the following section. Otherwise, please indicate what changed, and then add to the Release Notes section as highlighted during the release process.

### Type of Change (Check all that apply)

- [ ] protocol change
- [x] user-visible impact
- [ ] breaking change for a client SDKs
- [ ] breaking change for FNs (FN binary must upgrade)
- [ ] breaking change for validators or node operators (must upgrade binaries)
- [ ] breaking change for on-chain data layout
- [ ] necessitate either a data wipe or data migration

### Release notes

Implements the `Display` trait for the `BalanceChange` type as part of a larger effort in implementing a good-looking format output for `SuiTransactionBlockResponse` in the CLI.

### CODE REVIEW

**Review by amnn — APPROVED** [review]
Looks good, but don't forget the release notes!

**Comment by amnn** [comment]
(For next time, but the release notes should be in terms of the externally visible change -- i.e. the format of balance changes in the CLI changed).

**Comment by stefan-mysten** [comment]
I see. I did not want to add any release notes here, and was thinking only to do that for the final PR that combines everything together (e.g., when the Display trait for `SuiTransactionBlockResponse` is implemented which will format nicely these transaction responses).

**Comment by stefan-mysten** [comment]
Agreed with your line of thoughts here!

**Pull request merged**
