### PR TITLE
Dns resolve

### PR DESCRIPTION
**Pull request by longbowlu**

### CODE REVIEW

**Comment by Clay-Mysten** [comment]
Markdown LGTM.

**Comment by bmwill** [comment]
More specifically, once we've verified a particular commit as good, and have had it deployed to production, we should just push this branch to match that commit exactly

**Comment by Clay-Mysten** [comment]
> More specifically, once we've verified a particular commit as good, and have had it deployed to production, we should just push this branch to match that commit exactly

+1. Let's keep DevNet read only except for major pushes such as this and urgent cherry-picks.

**Comment by huitseeker** [comment]
@longbowlu do we want to close this one?

**Comment by huitseeker** [comment]
@longbowlu should we close this one?

**Review by Clay-Mysten — COMMENTED** [review]
Removing my approval to ensure this does not get merged while Lu contemplates closing it.

**Pull request closed without merging**
