### PR TITLE
Remove ALL_OBJ_VER flag and table from SuiDataStore

### PR DESCRIPTION
**Pull request by velvia**
The all_obj_versions table is redundant because we currently are keeping all object versions in the objects table.
Even in the future, when we will GC that table, we will enable pluggable GC traits that can clean up older objects, and if a use case called for keeping all versions simply then configure the store to use a NOP GC implementation.

Thus, removing this flag and the associated table.

### CODE REVIEW

**Review by lxfind — APPROVED** [review]
Thanks!

**Comment by mystenmark** [comment]
I thought I already did this, but I guess not! Thanks @velvia!

**Review by mystenmark — APPROVED** [review]

**Comment by velvia** [comment]
I'm not sure how to get the "Explorer Client PR checks / Lint Test & Build" to run to get status to pass.  One of the checks in there says "skipped" and it doesn't run even if I re-run that line

**Comment by velvia** [comment]
@lxfind @mystenmark do either of you know how I can get past the "Required statuses must pass before merging"?   The only thing that fails is "windows-test" which we know doesn't really work.  Unfortunately "test" is required and waiting for status, I suspect it is not reporting because Windows-test failed?  Or is this an infra issue?

/cc @bmwill

**Comment by lxfind** [comment]
rebase and push

**Pull request merged**
