### PR TITLE
[CLI] Adds initial package layout on `sui move new`

### PR DESCRIPTION
**Pull request by damirka**
## Description 

Following the discussion on scaffolding the app:

- adds `sources/{name}.move`
- adds `tests/{name}_tests.move`

```sh
sources/
    donuts.move
tests/
    donuts_tests.move
Move.toml
```

File: sources/name.move; Commented out contents:
```move
/// Module: donuts
module donuts::donuts {

}
```

File: tests/name_tests.move; Commented out contents:
```move
#[test_only]
module donuts::donuts_tests {
    // uncomment this line to import the module
    // use donuts::donuts;

    const ENotImplemented: u64 = 0;

    #[test]
    fun test_donuts() {
        // pass
    }

    #[test, expected_failure(abort_code = donuts::donuts_tests::ENotImplemented)]
    fun test_donuts_fail() {
        abort ENotImplemented
    }
}
```

## Test Plan 

Tests pass!

### Type of Change (Check all that apply)

- [ ] protocol change
- [ ] user-visible impact
- [ ] breaking change for a client SDKs
- [ ] breaking change for FNs (FN binary must upgrade)
- [ ] breaking change for validators or node operators (must upgrade binaries)
- [ ] breaking change for on-chain data layout
- [ ] necessitate either a data wipe or data migration

### CODE REVIEW

**Review by stefan-mysten — COMMENTED** [review]
Without knowing the context of the discussion, this looks fine to me. Not sure if it is what an user would expect (and this is where this kind of thing will get you different opinions, some want X, others want Y, etc), but if this is what's needed to start a quick project and have some template ready, it's fine.

**Comment by josemvcerqueira** [comment]
Awesome, do you think it would be helpful to add a comment line on top of the test file saying something along the lines of:

Learn more about testing at https://docs.sui.io/guides/developer/first-app/build-test

**Comment by damirka** [comment]
> Without knowing the context of the discussion, this looks fine to me. Not sure if it is what an user would expect (and this is where this kind of thing will get you different opinions, some want X, others want Y, etc), but if this is what's needed to start a quick project and have some template ready, it's fine.

As someone who starts a new package often, I get annoyed by the need to add the source file. Received similar feedback from other folks on the team and community members. 

As to the testing file, we do have an example of it in the Move by Example book but I think we're slowly going to the setup where developer has all things at hand with no need to look them up. Just like we recently added a richer Move.toml descriptions - https://github.com/MystenLabs/sui/pull/16191

@stefan-mysten

**Review by stefan-mysten — APPROVED** [review]
LGTM

**Pull request merged**
