### PR TITLE
Wallet welcome screen redesign 

### PR DESCRIPTION
**Pull request by Jibz1**
https://user-images.githubusercontent.com/8676844/186183242-7bfadaea-7467-4f7a-a670-b0d39795520e.mov

### CODE REVIEW

**Review by mystie711 — COMMENTED** [review]
Could we take out the "<- Back" button in the UI @Jibz1 ?

**Comment by Jibz1** [comment]
@mystie711 without the back button

https://user-images.githubusercontent.com/8676844/186186779-9e82e85f-fef6-492c-bdaf-00a5d55ea675.mov

**Review by mystie711 — COMMENTED** [review]
@Jibz1 just noticed the unselected checkbox state is incorrect. We can use the assets from Components Figma here,
https://www.figma.com/file/Z5KaPvgurJJ9d4sZQTYBPT/01-UI-Components-%3A-Explorer?node-id=1%3A1364

**Comment by Jibz1** [comment]
> @Jibz1 just noticed the unselected checkbox state is incorrect. We can use the assets from Components Figma here,
> https://www.figma.com/file/Z5KaPvgurJJ9d4sZQTYBPT/01-UI-Components-%3A-Explorer?node-id=1%3A1364

@mystie711 review

https://user-images.githubusercontent.com/8676844/186190441-556c8a8f-343c-488a-a1ef-32766a7bf3c9.mov

**Review by pchrysochoidis — APPROVED** [review]

**Comment by mystie711** [comment]
👏🏽 looking good!

**Pull request merged**
