### PR TITLE
[bridge/70] cache the result of get_mutable_bridge_object_arg

### PR DESCRIPTION
**Pull request by longbowlu**
## Description 

instead of querying the bridge arg on chain every time, we do this in the beginning of the program and cache it. If the fetch (with retry) fails, it panics.

## Test plan 

existing tests 

---

## Release notes

Check each box that your changes affect. If none of the boxes relate to your changes, release notes aren't required.

For each box you select, include information after the relevant heading that describes the impact of your changes that a user might notice and any actions they must take to implement updates. 

- [ ] Protocol: 
- [ ] Nodes (Validators and Full nodes): 
- [ ] Indexer: 
- [ ] JSON-RPC: 
- [ ] GraphQL: 
- [ ] CLI: 
- [ ] Rust SDK:

### CODE REVIEW

**Comment by lxfind** [comment]
Is this a temporary state?
My understanding is that once the bridge objects are created, all these become constants per-chain.
So instead of querying it, it seems that what we should do is to start the bridge with a config that contains these hardcoded information?

**Comment by longbowlu** [comment]
> Is this a temporary state? My understanding is that once the bridge objects are created, all these become constants per-chain. So instead of querying it, it seems that what we should do is to start the bridge with a config that contains these hardcoded information?

thought about it and prefer the coded approach because it's extra burden to place right things in the config especially for tests.

**Comment by Bridgerz** [comment]
lgtm

**Review by Bridgerz — APPROVED** [review]
lgtm

**Pull request merged**
