### PR TITLE
docs(sui-security): Fix typo

### PR DESCRIPTION
**Pull request by Cardosaum**
I'm not sure if the original version is correct, so I submitted what I think it should be.  Feel free to just ignore the suggestion if it does not apply.

### CODE REVIEW

**Review by randall-Mysten — APPROVED** [review]
Thanks for catching and submitting a fix for this!

**Comment by Cardosaum** [comment]
Sure, @randall-Mysten !

**Comment by Cardosaum** [comment]
I'm closing this issue, sorry for the mistake!

**Comment by randall-Mysten** [comment]
No worries, we need to provide better and more clear guidance on the process for this. Thanks for your help!

**Pull request closed without merging**
