### PR TITLE
Fix flaky test (#1967)

### PR DESCRIPTION
**Pull request by asonnino**
Attempt to fix 1967. 

Before stamping this PR, could you also check that the issue is fixed by running the following command? The bug is not-derministic and it is not easy to ensure it is fixed.

```bash
while true; do RUST_BACKTRACE=full cargo nextest run  -p sui-core submit_transaction_to_consensus  || break; done
```

### CODE REVIEW

**Comment by lxfind** [comment]
```
--- STDERR:                      sui-core consensus_adapter::consensus_tests::submit_transaction_to_consensus ---
thread 'consensus_adapter::consensus_tests::submit_transaction_to_consensus' panicked at 'Failed to notify consensus listener: SendError(New([0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 1, 0, 0, 0, 0, 0, 0, 0, 32, 0, 0, 0, 0, 0, 0, 0, 180, 125, 197, 89, 147, 114, 100, 223, 152, 226, 148, 158, 72, 186, 182, 171, 247, 136, 51, 171, 180, 93, 213, 137, 78, 135, 161, 206, 6, 100, 254, 41, 12, 0, 0, 0, 0, 0, 0, 0, 79, 98, 106, 101, 99, 116, 66, 97, 115, 105, 99, 115, 6, 0, 0, 0, 0, 0, 0, 0, 99, 114, 101, 97, 116, 101, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 102, 102, 102, 102, 102, 102, 102, 96, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 20, 0, 0, 0, 0, 0, 0, 0, 152, 14, 62, 166, 204, 214, 254, 171, 199, 78, 64, 203, 113, 91, 202, 162, 157, 78, 183, 104, 152, 14, 62, 166, 204, 214, 254, 171, 199, 78, 64, 203, 113, 91, 202, 162, 157, 78, 183, 104, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 85, 85, 85, 85, 85, 85, 85, 83, 0, 0, 0, 0, 0, 0, 0, 0, 32, 0, 0, 0, 0, 0, 0, 0, 216, 242, 185, 13, 171, 60, 114, 112, 250, 8, 179, 56, 131, 72, 152, 38, 145, 143, 215, 75, 155, 110, 210, 107, 123, 91, 74, 186, 203, 115, 254, 33, 16, 39, 0, 0, 0, 0, 0, 0, 96, 0, 0, 0, 0, 0, 0, 0, 208, 136, 222, 11, 115, 84, 151, 184, 179, 169, 131, 103, 185, 218, 41, 185, 127, 2, 71, 234, 19, 171, 141, 72, 131, 42, 225, 43, 149, 197, 253, 47, 145, 218, 52, 208, 212, 188, 220, 84, 249, 127, 22, 42, 66, 214, 241, 86, 16, 58, 65, 62, 140, 212, 51, 227, 90, 192, 238, 70, 75, 48, 171, 14, 190, 173, 160, 97, 38, 199, 141, 152, 180, 161, 166, 159, 110, 230, 24, 150, 148, 240, 244, 117, 21, 56, 218, 130, 79, 26, 220, 139, 20, 161, 181, 98, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 32, 0, 0, 0, 0, 0, 0, 0, 243, 58, 218, 61, 187, 113, 45, 141, 22, 40, 82, 114, 230, 149, 41, 37, 183, 116, 187, 144, 60, 82, 6, 115, 24, 30, 103, 49, 197, 205, 23, 106, 184, 85, 88, 202, 112, 15, 131, 245, 243, 44, 215, 46, 235, 114, 137, 39, 214, 187, 216, 37, 25, 34, 87, 33, 198, 242, 251, 141, 232, 76, 104, 239, 185, 164, 196, 234, 206, 126, 160, 181, 250, 218, 40, 189, 6, 15, 68, 153, 148, 204, 3, 66, 159, 73, 169, 72, 105, 47, 16, 5, 222, 14, 239, 9], Sender { inner: Some(Inner { state: State { is_complete: false, is_closed: false, is_rx_task_set: false, is_tx_task_set: false } }) }))', crates/sui-core/src/consensus_adapter.rs:131:14
stack backtrace:
   0:        0x104327f90 - std::backtrace_rs::backtrace::libunwind::trace::h449592924b3bd63f
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:        0x104327f90 - std::backtrace_rs::backtrace::trace_unsynchronized::ha2aaeafed0c31c90
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x104327f90 - std::sys_common::backtrace::_print_fmt::h58db85a17304976f
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:66:5
   3:        0x104327f90 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h10cf06316d33e2a9
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:45:22
   4:        0x10434a170 - core::fmt::write::h1faf18c959c3a8df
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/fmt/mod.rs:1190:17
   5:        0x1043203b4 - std::io::Write::write_fmt::h86ab231360bc97d2
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/io/mod.rs:1657:15
   6:        0x10432a58c - std::sys_common::backtrace::_print::h771b4aab9b128422
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:48:5
   7:        0x10432a58c - std::sys_common::backtrace::print::h637de99a9f76e8a7
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:35:9
   8:        0x10432a58c - std::panicking::default_hook::{{closure}}::h36e628ffaf3cd44f
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:295:22
   9:        0x10432a204 - std::panicking::default_hook::h3ee1564a7544e58f
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:314:9
  10:        0x10432abec - std::panicking::rust_panic_with_hook::h191339fbd2fe2360
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:698:17
  11:        0x10432a974 - std::panicking::begin_panic_handler::{{closure}}::h91c230befd9929e3
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:588:13
  12:        0x104328478 - std::sys_common::backtrace::__rust_end_short_backtrace::haaaeebb1d37476b3
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:138:18
```

**Comment by asonnino** [comment]
> > --- STDERR:                      sui-core consensus_adapter::consensus_tests::submit_transaction_to_consensus ---
> > thread 'consensus_adapter::consensus_tests::submit_transaction_to_consensus' panicked at 'Failed to notify consensus listener: SendError(New([0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 1, 0, 0, 0, 0, 0, 0, 0, 32, 0, 0, 0, 0, 0, 0, 0, 180, 125, 197, 89, 147, 114, 100, 223, 152, 226, 148, 158, 72, 186, 182, 171, 247, 136, 51, 171, 180, 93, 213, 137, 78, 135, 161, 206, 6, 100, 254, 41, 12, 0, 0, 0, 0, 0, 0, 0, 79, 98, 106, 101, 99, 116, 66, 97, 115, 105, 99, 115, 6, 0, 0, 0, 0, 0, 0, 0, 99, 114, 101, 97, 116, 101, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 102, 102, 102, 102, 102, 102, 102, 96, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 20, 0, 0, 0, 0, 0, 0, 0, 152, 14, 62, 166, 204, 214, 254, 171, 199, 78, 64, 203, 113, 91, 202, 162, 157, 78, 183, 104, 152, 14, 62, 166, 204, 214, 254, 171, 199, 78, 64, 203, 113, 91, 202, 162, 157, 78, 183, 104, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 85, 85, 85, 85, 85, 85, 85, 83, 0, 0, 0, 0, 0, 0, 0, 0, 32, 0, 0, 0, 0, 0, 0, 0, 216, 242, 185, 13, 171, 60, 114, 112, 250, 8, 179, 56, 131, 72, 152, 38, 145, 143, 215, 75, 155, 110, 210, 107, 123, 91, 74, 186, 203, 115, 254, 33, 16, 39, 0, 0, 0, 0, 0, 0, 96, 0, 0, 0, 0, 0, 0, 0, 208, 136, 222, 11, 115, 84, 151, 184, 179, 169, 131, 103, 185, 218, 41, 185, 127, 2, 71, 234, 19, 171, 141, 72, 131, 42, 225, 43, 149, 197, 253, 47, 145, 218, 52, 208, 212, 188, 220, 84, 249, 127, 22, 42, 66, 214, 241, 86, 16, 58, 65, 62, 140, 212, 51, 227, 90, 192, 238, 70, 75, 48, 171, 14, 190, 173, 160, 97, 38, 199, 141, 152, 180, 161, 166, 159, 110, 230, 24, 150, 148, 240, 244, 117, 21, 56, 218, 130, 79, 26, 220, 139, 20, 161, 181, 98, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 32, 0, 0, 0, 0, 0, 0, 0, 243, 58, 218, 61, 187, 113, 45, 141, 22, 40, 82, 114, 230, 149, 41, 37, 183, 116, 187, 144, 60, 82, 6, 115, 24, 30, 103, 49, 197, 205, 23, 106, 184, 85, 88, 202, 112, 15, 131, 245, 243, 44, 215, 46, 235, 114, 137, 39, 214, 187, 216, 37, 25, 34, 87, 33, 198, 242, 251, 141, 232, 76, 104, 239, 185, 164, 196, 234, 206, 126, 160, 181, 250, 218, 40, 189, 6, 15, 68, 153, 148, 204, 3, 66, 159, 73, 169, 72, 105, 47, 16, 5, 222, 14, 239, 9], Sender { inner: Some(Inner { state: State { is_complete: false, is_closed: false, is_rx_task_set: false, is_tx_task_set: false } }) }))', crates/sui-core/src/consensus_adapter.rs:131:14
> > stack backtrace:
> > 0:        0x104327f90 - std::backtrace_rs::backtrace::libunwind::trace::h449592924b3bd63f
> > at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
> > 1:        0x104327f90 - std::backtrace_rs::backtrace::trace_unsynchronized::ha2aaeafed0c31c90
> > at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
> > 2:        0x104327f90 - std::sys_common::backtrace::_print_fmt::h58db85a17304976f
> > at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:66:5
> > 3:        0x104327f90 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h10cf06316d33e2a9
> > at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:45:22
> > 4:        0x10434a170 - core::fmt::write::h1faf18c959c3a8df
> > at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/fmt/mod.rs:1190:17
> > 5:        0x1043203b4 - std::io::Write::write_fmt::h86ab231360bc97d2
> > at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/io/mod.rs:1657:15
> > 6:        0x10432a58c - std::sys_common::backtrace::_print::h771b4aab9b128422
> > at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:48:5
> > 7:        0x10432a58c - std::sys_common::backtrace::print::h637de99a9f76e8a7
> > at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:35:9
> > 8:        0x10432a58c - std::panicking::default_hook::{{closure}}::h36e628ffaf3cd44f
> > at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:295:22
> > 9:        0x10432a204 - std::panicking::default_hook::h3ee1564a7544e58f
> > at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:314:9
> > 10:        0x10432abec - std::panicking::rust_panic_with_hook::h191339fbd2fe2360
> > at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:698:17
> > 11:        0x10432a974 - std::panicking::begin_panic_handler::{{closure}}::h91c230befd9929e3
> > at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:588:13
> > 12:        0x104328478 - std::sys_common::backtrace::__rust_end_short_backtrace::haaaeebb1d37476b3
> > at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:138:18
> 
> thanks!

Btw, I found a way to reproduce (using a linux AWS instance)

**Comment by asonnino** [comment]
Seems to be fixed on my end

**Review by lxfind — APPROVED** [review]
Passing now. Thanks!

**Pull request merged**
