### PR TITLE
Add few debug assert to gas computation

### PR DESCRIPTION
**Pull request by dariorussi**
## Description 

Add some debug assert to make sure that the gas computation (not storage) is aligned with bucket boundaries

## Test Plan 

Existing tests

---
If your changes are not user-facing and not a breaking change, you can skip the following section. Otherwise, please indicate what changed, and then add to the Release Notes section as highlighted during the release process.

### Type of Change (Check all that apply)

- [ ] user-visible impact
- [ ] breaking change for a client SDKs
- [ ] breaking change for FNs (FN binary must upgrade)
- [ ] breaking change for validators or node operators (must upgrade binaries)
- [ ] breaking change for on-chain data layout
- [ ] necessitate either a data wipe or data migration

### CODE REVIEW

**Comment by dariorussi** [comment]
@sblackshear take a look and see if that is what you had in mind

**Comment by dariorussi** [comment]
well this needs a bit more attention given the number of failures...

**Comment by dariorussi** [comment]
I suspect the problems may be related to the fact that summary is called even for transactions that do bot bucketize (system txn) which may cause the assert to fire. 
I'll double check but it may be a bit trickier than we wanted to put those asserts in

**Review by tnowacki — COMMENTED** [review]
I think this looks fine to me? I have a macro that is just in execution now bug could be moved:
https://github.com/MystenLabs/sui/blob/main/crates/sui-adapter/src/lib.rs#L13
They give a debug assert in debug builds, but an invariant violation `ExecutionError` otherwise. 
I'm not sure what you want for these cases though. 
The question I would ask is what happens if these checks fail? If it's detrimental to the network, let's give an error

**Comment by sblackshear** [comment]
> I suspect the problems may be related to the fact that summary is called even for transactions that do bot bucketize (system txn) which may cause the assert to fire.

This sounds like a plausible theory--I think there is an `GasStatus""is_unmetered()` function that should be true iff it's a system tx that you should be able to use for this.

**Pull request closed without merging**
