### PR TITLE
Add CertifiedTransactionEffects

### PR DESCRIPTION
**Pull request by lxfind**
This PR adds `CertifiedTransactionEffects` type.
Made authority_aggregate to return it after execution. Propagate the type to all callers.
This will be needed once we connect QuorumDriver with fullnode.

### CODE REVIEW

**Review by gdanezis — APPROVED** [review]
Great stuff!

**Comment by bmwill** [comment]
>This will be needed once we connect QuorumDriver with fullnode.

PR looks good but i don't follow this. QuorumDriver is supposed to be a stateless and independent component, how is this needed with fullnodes?

**Comment by bmwill** [comment]
I do not believe that will scale well both from a data dissemination perspective as well now the number of entities I need to follow is essentially all fullnodes

**Comment by lxfind** [comment]
hmm not sure what you mean.
This is purely an optimization: since a fullnode is also operating a QuorumDriver, a fullnode can always subscribe to its own QuorumDriver and get notified on finalized effects as soon as they are formed. This will be allow some transactions to be "finalized" earlier on the fullnode. For fullnode that's a popular QuorumDriver, this provides a solid benefit for them, and hence a fullnode is also incentivized to operate a good QuorumDriver.

**Pull request merged**
