### PR TITLE
tracing: don't emit span New and Close events

### PR DESCRIPTION
**Pull request by bmwill**

### CODE REVIEW

**Review by aschran — APPROVED** [review]

**Comment by mwtian** [comment]
Does this remove new and close events outside of anemo as well?
cc @velvia

**Comment by bmwill** [comment]
Yes it does

**Comment by mwtian** [comment]
Does this make `#[instrument(level = "debug", skip_all)]` etc no-ops now? Do we need to manually add more debug logs?

cc @akichidis

**Comment by bmwill** [comment]
No, they aren't no ops. The spans are still opened and their context is shared with all events that happen while they're open.

**Comment by mwtian** [comment]
Yeah, definitely `#[instrument(...)]` is still doing work, but it seems we will lose the logs of new and close for enabling logging at debug verbosity for Narwhal, which is what we care about the most. e.g. if we need to add separate log statements for https://github.com/mwtian/sui/blob/19e45f4964c1231b235c36d7f4dbbbc9633a73e5/narwhal/primary/src/core.rs to print `header_digest`, it will be a bit tedious. We will also lose latency info in a few places.

One question is what is the disadvantage of going back two steps, i.e. re-enabling logging new and close events based on the verbosity in `#[instrument(...)]`, and log anemo span new and close at debug or trace verbosity?

**Comment by bmwill** [comment]
The anemo trace spans need to be enabled so that appropriate context exists for when we end up seeing rpc errors. Before when they were at debug, there wasn't a lot of context on the error logs

**Pull request merged**
