### PR TITLE
update print for create wallet

### PR DESCRIPTION
**Pull request by Romainua**
Update first print! for creating wallet, I think it will be better for visual perception

### CODE REVIEW

**Review by patrickkuo — APPROVED** [review]

**Review by Clay-Mysten — CHANGES_REQUESTED** [review]
Hi Romainua Roman,

Thanks again for all of these fixes. Please note, we just merged many changes from our `main` (upstream) branch to `devnet` which addresses some but not all of these changes.

Can you rebase and include only the unique fixes? That should address the merge conflicts.

Also, please consider working in `main` right along with us. Let me know if you have any questions.

**Comment by Romainua** [comment]
> Hi Romainua Roman,
> 
> Thanks again for all of these fixes. Please note, we just merged many changes from our `main` (upstream) branch to `devnet` which addresses some but not all of these changes.
> 
> Can you rebase and include only the unique fixes? That should address the merge conflicts.
> 
> Also, please consider working in `main` right along with us. Let me know if you have any questions.

Does the change in the `devnet` come from the `main`? So I'll work there

**Comment by Clay-Mysten** [comment]
> > Hi Romainua Roman,
> > Thanks again for all of these fixes. Please note, we just merged many changes from our `main` (upstream) branch to `devnet` which addresses some but not all of these changes.
> > Can you rebase and include only the unique fixes? That should address the merge conflicts.
> > Also, please consider working in `main` right along with us. Let me know if you have any questions.
> 
> Does the change in the `devnet` come from the `main`? So I'll work there

Yes, please! I'm sorry for the confusion. We cut `devnet` from `main` but are just settling on doing the same for docs.sui.io, which will allows the docs and code to be in sync but the stable `devnet` version we recommend to be slightly behind.

We are working to formalize this and appreciate your feedback too! Please let us know here or at:
doc@mystenlabs.com

Thanks again and sorry for the confusion.

**Comment by Romainua** [comment]
> 

Everything is very cool, sometimes I find some outdated information in the doc, but I think this is not a problem. Sorry, I didn't quite understand what to write to the email 😄

**Comment by Clay-Mysten** [comment]
> > 
> 
> Everything is very cool, sometimes I find some outdated information in the doc, but I think this is not a problem. Sorry, I didn't quite understand what to write to the email 😄

We appreciate your help immensely. I just want to make sure you are editing the latest contents so as to not duplicate work and get the most out of your help. Please work in the `main` branch, and we will gladly review/approve changes.

Thank you so much!

**Review by Clay-Mysten — APPROVED** [review]

**Review by huitseeker — CHANGES_REQUESTED** [review]
This will need a rebase

**Pull request closed without merging**
