### PR TITLE
wallet-ext: settings menu redesign

### PR DESCRIPTION
**Pull request by pchrysochoidis**
* storybook add memory router to every story
* ui button component add styles tiny size and plain variant
  * Screen Shot 2023-02-13 at 7 23 34 PM

* move loading functionality from Button to ButtonOrLink component so we can reuse it
* update PageTitle component and use it in every page
  * Screen Shot 2023-02-14 at 2 58 22 PM
  * Screen Shot 2023-02-14 at 2 58 15 PM
  * Screen Shot 2023-02-14 at 2 58 26 PM
* add Link component
  
  https://user-images.githubusercontent.com/10210143/218554452-2a118a62-e1bf-432a-a349-03fbfc5c2d72.mov

* add Pill component

https://user-images.githubusercontent.com/10210143/218798176-7a5addd8-af26-4688-87aa-fe44bad8af44.mov

* add InputWithAction component

https://user-images.githubusercontent.com/10210143/218797944-21b00be8-953d-4310-b83d-6ed8f239a42b.mov

* update Settings Menu

https://user-images.githubusercontent.com/10210143/218555029-f528d9dc-7c91-4bfb-88a5-5ca256dd84b6.mov

closes: APPS-285

### CODE REVIEW

**Comment by mystie711** [comment]
Looking great over all @pchrysochoidis! 
Some observations,
settings

**Review by Jibz1 — APPROVED** [review]

**Comment by mystie711** [comment]
Also noticed a Figma inconsistency. Updated design. Please update the padding on left/right for the settings rows as well.
image

**Comment by pchrysochoidis** [comment]
@mystie711 
* Logo position should be a bit better now after merging https://github.com/MystenLabs/sui/pull/7902 (there is a small difference still but we need to replace the logo font icon with an svg - will do it in another PR)

| before | after |
| - | - |
| Screen Shot 2023-02-13 at 10 56 44 PM | Screen Shot 2023-02-13 at 10 57 03 PM |

* menu item arrow is bigger now
* fixed menu item row is height
* removed icon from faucet button
* Terms of Service ->  Terms of service
* fixed padding
* double checked colors seem the same as figma

| before | after |
| - | - |
| Screen Shot 2023-02-13 at 11 09 58 PM | Screen Shot 2023-02-13 at 11 06 11 PM |
| Screen Shot 2023-02-13 at 11 12 25 PM | Screen Shot 2023-02-13 at 11 13 04 PM |
| Screen Shot 2023-02-13 at 11 12 30 PM | Screen Shot 2023-02-13 at 11 13 09 PM |
| Screen Shot 2023-02-13 at 11 12 36 PM | Screen Shot 2023-02-13 at 11 13 13 PM |

Also kept the red color for Logout until we implement the confirmation modal

**Comment by mystie711** [comment]
Great progress @pchrysochoidis! Just a few more items,

- The "<- " icon in header seems to be smaller than one in Figma. Please double check the icon size in use.
- The input box ui and interaction seems to have delta from [Figma](https://www.figma.com/file/xu2VnyPAuruNi74UQzGigW/02-Wallet?node-id=3030%3A55105&t=FrsvbXrU7Mi4lpDk-1)? Please also double check the font style of the auto-lock description text. the font leading is to tight compared to Figma.

**Comment by pchrysochoidis** [comment]
> Great progress @pchrysochoidis! Just a few more items,
> 
> * The "<- " icon in header seems to be smaller than one in Figma. Please double check the icon size in use.
> * The input box ui and interaction seems to have delta from [Figma](https://www.figma.com/file/xu2VnyPAuruNi74UQzGigW/02-Wallet?node-id=3030%3A55105&t=FrsvbXrU7Mi4lpDk-1)? Please also double check the font style of the auto-lock description text. the font leading is to tight compared to Figma.

@mystie711 these should be addressed now

Screen Shot 2023-02-14 at 3 02 58 PMScreen Shot 2023-02-14 at 3 03 04 PMScreen Shot 2023-02-14 at 3 03 09 PMScreen Shot 2023-02-14 at 3 03 40 PMScreen Shot 2023-02-14 at 3 03 47 PMScreen Shot 2023-02-14 at 3 05 03 PM

**Comment by mystie711** [comment]
Awesome!. 
Could the "spinner" show inside the (MAX) button pill...effectively replacing the MAX text while it is in progress?

**Comment by pchrysochoidis** [comment]
> Awesome! Could the "spinner" show inside the (SAVE) button pill...effectively replacing the SAVE text while it is in progress? This should probably be a part of the button component like we discussed in-person.
> 
> Going to also capture this in Figma component section for easy reference.

> Could the "spinner" show inside the (SAVE) button pill
Yes, this is inside the Save Pill, it hides the text and displays the spinner. The problem is probably that when disabled the Pill does't have any border/background. (based of figma [here](https://www.figma.com/file/Z5KaPvgurJJ9d4sZQTYBPT/01-Components-%3A-Explorer?node-id=989%3A12763&t=O2vjbCe5ud1XyQ6I-4))

**Comment by pchrysochoidis** [comment]
@mystie711 Done


https://user-images.githubusercontent.com/10210143/218798356-24cbe794-3262-429a-9c52-e53166516915.mov

**Review by mystie711 — APPROVED** [review]
LGTM!

**Pull request merged**
