### PR TITLE
Update sui-json.md

### PR DESCRIPTION
**Pull request by Romainua**
Changed the type of list for `Identifier`. There was white list, doen’t look good on doc.

### CODE REVIEW

**Review by randall-Mysten — APPROVED** [review]
Good call, thanks for catching!

**Comment by randall-Mysten** [comment]
@Romainua  Oops, this is trying to merge to devnet, needs to go to main please

**Comment by Romainua** [comment]
> @Romainua Oops, this is trying to merge to devnet, needs to go to main please

Sorry, changed.

**Comment by randall-Mysten** [comment]
@Romainua I totally don't do the same once a week ;) Could you also rebase - seeing conflicts

**Pull request closed without merging**
