### PR TITLE
Update cli-client.md

### PR DESCRIPTION
**Pull request by georgescharlesbrain**
typo

### CODE REVIEW

**Review by ronny-mysten — APPROVED** [review]
Thanks, Georges!

**Comment by randall-Mysten** [comment]
Hi @georgescharlesbrain This is trying to merge to `devnet` but it need to go to `main`.

**Comment by georgescharlesbrain** [comment]
Hi, yes, I started from the docs, as always. Not sure why it wasn't automatically set to main.

Corrected it.

**Comment by randall-Mysten** [comment]
The site loads with the Devnet version selected by default, so the link at the bottom to GH opens that branch. Latest is built from the main branch.

**Review by randall-Mysten — APPROVED** [review]

**Pull request merged**
