### PR TITLE
[refactor] refactor EffectsEnvelope as Envelope

### PR DESCRIPTION
**Pull request by punwai**

### CODE REVIEW

**Comment by lxfind** [comment]
Looks like this is stacked on top of https://github.com/MystenLabs/sui/pull/4142? I think you can compare to that branch to get only the diff between them

**Comment by punwai** [comment]
@lxfind I opened this one so I don't have to open another one once we merge the TransactionEnvelope refactor.

**Comment by lxfind** [comment]
What I meant is in the top you can compare this branch to the other branch, so that github will display the difference between the two branches.

**Comment by lxfind** [comment]
@randall-Mysten Hey Randall, for PRs that are mostly code changes, after you reviewed the documentation change, please don't approve it yet, as we still need to review the code changes (otherwise PRs can merge once approved). Instead you can comment with something like "doc change LGTM" and etc. Thanks!

**Review by lxfind — COMMENTED** [review]
Will review once the previous PR merged so I can see the content of this PR cleanly.

**Review by kchalkias — COMMENTED** [review]
status of this PR? @lxfind do you support this change?

**Comment by punwai** [comment]
@kchalkias Oops, this is my fault. I have to merge the previous PR, then @lxfind will be able to review this one.

**Comment by randall-Mysten** [comment]
Please reopen if this is still a relevant issue. Closing stale PRs

**Pull request closed without merging**
