### PR TITLE
Minor update to json-rpc.md

### PR DESCRIPTION
**Pull request by patrickkuo**
Removed sync account example it will be deprecated soon.
removed dups `In the following sections we will show how to use Sui's JSON-RPC API.....`
use proper headers instead of rpc method name

### CODE REVIEW

**Comment by patrickkuo** [comment]
FYI @Romainua

**Review by Clay-Mysten — APPROVED** [review]
Thanks, Patrick! This LGTM with some small changes I made in a commit here.

**Comment by Clay-Mysten** [comment]
FYI @Romainua

**Comment by Romainua** [comment]
LGTM, will check in doc and check all output and methods

**Pull request merged**
