### PR TITLE
[execution] Recompute has_public_transfer on load

### PR DESCRIPTION
**Pull request by tnowacki**
## Description 

- has_public_transfer is conceptually static, but is not for core types due to in-place upgrades
- The flag originally existed to avoid having to load the VM in the very early days of Sui. This is no longer the case and the type is loaded anyway. So we should just recompute the flag.

## Test Plan 

How did you test the new or updated feature?

---
If your changes are not user-facing and not a breaking change, you can skip the following section. Otherwise, please indicate what changed, and then add to the Release Notes section as highlighted during the release process.

### Type of Change (Check all that apply)

- [x] protocol change
- [ ] user-visible impact
- [ ] breaking change for a client SDKs
- [ ] breaking change for FNs (FN binary must upgrade)
- [ ] breaking change for validators or node operators (must upgrade binaries)
- [ ] breaking change for on-chain data layout
- [ ] necessitate either a data wipe or data migration

### CODE REVIEW

**Comment by tnowacki** [comment]
Does anyone have suggestions on testing this?

My thoughts are a I could:
- Make a coin
- Manually set the field of `has_public_transfer` to false
- Then execute a transfer and see that it passes

But I do not know of any test suite that sits so close to execution in that way (most of our tests are really e2e these days)

**Comment by amnn** [comment]
Re: testing -- I would look at how we test system package upgrades, here:

https://github.com/MystenLabs/sui/blob/d989004c1c831b6ad986dc0010d0e1761fdb9e99/crates/sui-e2e-tests/tests/protocol_version_tests.rs#L296

It has all the pieces you need:

- A way to change a type (via an upgrade).
- A way to run functions before and after an upgrade (before to create an instance of the type, after to do something to it that requires store).

**Comment by amnn** [comment]
In fact there is already a test that adds `store` to a type `test_framework_add_struct_ability` that you could augment:

https://github.com/MystenLabs/sui/blob/d989004c1c831b6ad986dc0010d0e1761fdb9e99/crates/sui-e2e-tests/tests/protocol_version_tests.rs#L325

It already checks that you can take advantage of the new ability within Move, for an instances of the type created before and after the change.  It just remains to add a test that you can also do it outside of Move.

**Comment by tnowacki** [comment]
> * A way to run functions before and after an upgrade (before to create an instance of the type, after to do something to it that requires store).

Amazing! Thanks!

**Review by amnn — APPROVED** [review]
LGTM!  I've made a note to follow up in RPC 2.0 to hide this field from structured output.

**Pull request merged**
