### PR TITLE
Move suivm to latest

### PR DESCRIPTION
**Pull request by dariorussi**
## Description 

Move suivm to latest. Suivm is getting in the way of a bunch of work happening in the execution layer.
This is also showing the issues related to branches that are live for long. It is at times inevitable but we need to be careful about what people review and how to go back to latest.
Hopefully the work to make latest the working branch will make this less of a problem. We'll see

## Test Plan 

Existing tests

---
If your changes are not user-facing and not a breaking change, you can skip the following section. Otherwise, please indicate what changed, and then add to the Release Notes section as highlighted during the release process.

### Type of Change (Check all that apply)

- [ ] protocol change
- [ ] user-visible impact
- [ ] breaking change for a client SDKs
- [ ] breaking change for FNs (FN binary must upgrade)
- [ ] breaking change for validators or node operators (must upgrade binaries)
- [ ] breaking change for on-chain data layout
- [ ] necessitate either a data wipe or data migration

### CODE REVIEW

**Comment by dariorussi** [comment]
I think we are moving the right files and they look ok.
However I am failing `sui-benchmark::simtest test::test_simulated_load_restarts` and I am not really sure what to do.
Any help or suggestion welcome @mystenmark @lxfind

**Comment by lxfind** [comment]
That's https://mysten-labs.slack.com/archives/C045PNBDFDJ/p1694802046283779

**Comment by amnn** [comment]
Is the plan to land this after `latest` becomes the working branch?

**Review by amnn — APPROVED** [review]
Changes are in any case fine, so accepting to unblock, pending the question about how this lands relative to the change that makes `latest` the working branch.

**Comment by dariorussi** [comment]
> Is the plan to land this after latest becomes the working branch?

no before as this is almost a precondition for that

**Pull request merged**
