### PR TITLE
Add default assignees to Sui link checker in CI

### PR DESCRIPTION
**Pull request by Clay-Mysten**

### CODE REVIEW

**Comment by Clay-Mysten** [comment]
Adding my fellow victims, I mean volunteers for approval first. :-D

**Review by lxfind — APPROVED** [review]
What did I just sign up for?

**Comment by Clay-Mysten** [comment]
> What did I just sign up for?

Weekly emails on broken links.  I will take care of them yet need backups for OOO and such. Thank you!

**Comment by huitseeker** [comment]
> Weekly emails on broken links. I will take care of them yet need backups for OOO and such. Thank you!

To be precise, this is the assignees for the sort of report created here: https://github.com/MystenLabs/sui/issues/1769

**Pull request merged**
