### PR TITLE
Update faq.md

### PR DESCRIPTION
**Pull request by Romainua**
If I'm not wrong, Sui Community Mod Program is open, I think we can change ansewer for `Do you need moderators in Discord? Can I be the mod for my country?`

### CODE REVIEW

**Comment by Clay-Mysten** [comment]
I'm on vacation.  Please have someone else review. Thanks!

**Comment by Romainua** [comment]
@kyleqian Could you check it?

**Comment by Clay-Mysten** [comment]
> > I'm on vacation. Please have someone else review. Thanks!
> 
> sorry for bothering!

No worries! Thanks so much for your help. @losamsel can you review this?

**Review by bwann52 — APPROVED** [review]

**Review by Clay-Mysten — APPROVED** [review]
Thanks so much for this update! And sorry for the delayed review.

**Pull request merged**
