### PR TITLE
[CLI/PTB] Avoid fetching the protocol config when building a PTB

### PR DESCRIPTION
**Pull request by amnn**
## Description

...and make its corresponding module in `sui_programmability/examples/basics` line up.

## Test plan

```
sui$ cargo nextest run -p sui-framework-tests
```

+ :eyes: for docs

### CODE REVIEW

**Review by stefan-mysten — APPROVED** [review]
Nice! Just to make sure I understand, why are we not worried about the package size limit? I probably am confused because I do not understand what the `resolve_to_package` function actually does.

**Comment by amnn** [comment]
`resolve_to_package` finds the package from on-chain so we can answer questions about types and function signatures etc. We're not worried about the max package size because the package was published on-chain, so the chain has already validated that it's under the max package size (and even if it wasn't, this is a local tool, while this limit is intended to protect validators).

**Comment by stefan-mysten** [comment]
> `resolve_to_package` finds the package from on-chain so we can answer questions about types and function signatures etc. We're not worried about the max package size because the package was published on-chain, so the chain has already validated that it's under the max package size (and even if it wasn't, this is a local tool, while this limit is intended to protect validators).

Thanks, I think that's what I missed, that we're just looking at an already published package. However, what happens if we're trying to run `sui client ptb publish`, I assume this `resolve_to_package` is not called, right?

**Comment by amnn** [comment]
That's right, it's only called to resolve types on inputs which must therefore come from existing packages.

**Pull request merged**
