### PR TITLE
Fix e2e test hanging on local runs

### PR DESCRIPTION
**Pull request by wlmyng**
## Description 

When running `cargo nextest run --test-threads 1 --package sui-graphql-rpc --test e2e_tests --test examples_validation_tests --features pg_integration` locally, these tests will hang on the first one. Explicitly sending a cancellation signal and waiting for the indexer and graphql handles to spin down seems to solve the issue.

Would be nice to run these in parallel too, but punting them for when we have an embedded db setup.

## Test plan 

Tests pass locally

---

## Release notes

Check each box that your changes affect. If none of the boxes relate to your changes, release notes aren't required.

For each box you select, include information after the relevant heading that describes the impact of your changes that a user might notice and any actions they must take to implement updates. 

- [ ] Protocol: 
- [ ] Nodes (Validators and Full nodes): 
- [ ] Indexer: 
- [ ] JSON-RPC: 
- [ ] GraphQL: 
- [ ] CLI: 
- [ ] Rust SDK:
- [ ] REST API:

### CODE REVIEW

**Review by stefan-mysten — APPROVED** [review]
Thanks @wlmyng 🚀

**Review by amnn — COMMENTED** [review]
Thanks for fixing this @wlmyng. 

Having to call `cluster.cleanup_resources().await` seems potentially error-prone, is there a way to avoid that step?

**Comment by wlmyng** [comment]
> Thanks for fixing this @wlmyng. 
> 
> 
> 
> Having to call `cluster.cleanup_resources().await` seems potentially error-prone, is there a way to avoid that step?

I concur, and did give trying to avoid this a go. The thing is the join! bit is async, so wasn't sure if that would play well if I were to implement `Drop`

Thinking about ts jest, there's a way to setup and spin down each test and I imagine there's probably a way to do so in rust as well

**Comment by amnn** [comment]
> there's a way to setup and spin down each test and I imagine there's probably a way to do so in rust as well

I don't think there is, sadly :(

The fact that the test hangs without the cancellation makes me think that there is some kind of implicit join going on anyway. I wonder if we did just the call to `cancel()` in the `Drop` impl, whether that would fix things?

**Comment by wlmyng** [comment]
> > there's a way to setup and spin down each test and I imagine there's probably a way to do so in rust as well
> 
> 
> 
> I don't think there is, sadly :(
> 
> 
> 
> The fact that the test hangs without the cancellation makes me think that there is some kind of implicit join going on anyway. I wonder if we did just the call to `cancel()` in the `Drop` impl, whether that would fix things?

I can give it another try 👉

**Pull request merged**
