### PR TITLE
docs: update the fullnode docs

### PR DESCRIPTION
**Pull request by alinustorvalt**
fullnode-template.yaml

### CODE REVIEW

**Review by Clay-Mysten — APPROVED** [review]
Thank you!

**Comment by alinustorvalt** [comment]
My pleasure

Pada tanggal Min, 17 Jul 2022 7.35 AM, Clay-Mysten ***@***.***>
menulis:

**Review by Clay-Mysten — CHANGES_REQUESTED** [review]
Let me get the Fullnode team to take a look

**Comment by bmwill** [comment]
I'm not quite sure what you're trying to do with this PR. The docs are located in /doc/src/build/fullnode.md and this PR does not update that file, instead its adding a genesis blob as well as some random files which is not what we want to do.

Closing, feel free to reopen or open a new PR which does update the documentation if needed.

**Pull request closed without merging**
