### PR TITLE
Fix issues with `update_randomness_state` in framework

### PR DESCRIPTION
**Pull request by aschran**
## Description 

- Corrects issue where first write of epoch 0, round 0 was rejected.
- Corrects issue where writes after epcoh increment were rejected.

## Test Plan 

Reproed issue with unit tests, changes fixed failing tests.

### CODE REVIEW

**Review by benr-ml — APPROVED** [review]

**Comment by lxfind** [comment]
What was the reason to create a bytecode snapshot for v34?

**Comment by aschran** [comment]
Isn't it necessary to update the snapshot when modifying the framework?

**Comment by lxfind** [comment]
Only if you need to cherry-pick it to release branch as a hot fix.

**Comment by aschran** [comment]
Ok, that's what I've had to do in the past. Apologies if it was unnecessary

**Pull request merged**
