### PR TITLE
[explorer] Fix smart contract rendering

### PR DESCRIPTION
**Pull request by 666lcz**
Before:
There will be an error for rendering Move package object(example: https://explorer-internal-testing.s3-website-us-east-1.amazonaws.com/objects/8070E826B3668A048A59A095DE23EC26491CA2D9)
CleanShot 2022-05-04 at 01 42 31

After:
CleanShot 2022-05-04 at 01 42 22
CleanShot 2022-05-04 at 01 44 09

### CODE REVIEW

**Review by Andrew47 — CHANGES_REQUESTED** [review]
@666lcz - We have a PR that covers this here: https://github.com/MystenLabs/sui/pull/1535/files.

The main change from this PR would be adding `whitespace-pre` to the CSS.

**Comment by 666lcz** [comment]
@Andrew47 , if you examine the changed file, you will see the fix is different. We need both! This PR fixes the SDK <> backend, while [your PR](https://github.com/MystenLabs/sui/pull/1535) fixes the layout. Without this change, https://github.com/MystenLabs/sui/pull/1535 is not going to work

**Comment by 666lcz** [comment]
Rebase and re-test

@Andrew47 , note that the devnet gateway is currently down,  if you would like to repro this locally,
1. follow https://github.com/MystenLabs/sui/tree/main/explorer/client#connecting-to-local-rpc-server
2.Use this command to publish a package
```
cd <sui repo>
wallet publish --path sui_programmability/tutorial --gas-budget 30000

```
Otherwise you can just watch the video below where I have thoroughly test the flow

https://user-images.githubusercontent.com/76067158/166800460-c6ab13ba-52c1-4d44-b678-76b87cf22e88.mp4

**Review by Andrew47 — APPROVED** [review]
Given the backend is down, the video proof will do for now.

**Pull request merged**
