### PR TITLE
[graphql] data provider trait to support swapping out providers for snapshot testing

### PR DESCRIPTION
**Pull request by wlmyng**
## Description 

DataProvider trait + pass Box<dyn DataProvider> to graphql objects

## Test Plan 

How did you test the new or updated feature?

---
If your changes are not user-facing and not a breaking change, you can skip the following section. Otherwise, please indicate what changed, and then add to the Release Notes section as highlighted during the release process.

### Type of Change (Check all that apply)

- [ ] protocol change
- [ ] user-visible impact
- [ ] breaking change for a client SDKs
- [ ] breaking change for FNs (FN binary must upgrade)
- [ ] breaking change for validators or node operators (must upgrade binaries)
- [ ] breaking change for on-chain data layout
- [ ] necessitate either a data wipe or data migration

### CODE REVIEW

**Comment by oxade** [comment]
Nice one!
> How did you test the new or updated feature?

Did you test the server to ensure things work as before?

**Comment by wlmyng** [comment]
> Nice one!
> 
> > How did you test the new or updated feature?
> 
> 
> 
> Did you test the server to ensure things work as before? Can you show output?

I did a query and got the expected valid response, but didn't exhaustively verify

**Comment by oxade** [comment]
> > Nice one!
> > > How did you test the new or updated feature?
> > 
> > 
> > Did you test the server to ensure things work as before? Can you show output?
> 
> I did a query and got the expected valid response, but didn't exhaustively verify

Thats okay, send it!
My subsequent PRs should make it easier to test new features like these.

**Review by oxade — APPROVED** [review]
Love it

**Pull request merged**
