### PR TITLE
Coin transformer utility

### PR DESCRIPTION
**Pull request by oxade**
Screen Shot 2022-09-08 at 15 01 04

Addresses [issue](https://github.com/MystenLabs/sui/issues/4530)

In many cases for coin mgmt we want to transform a vector of M coins with arbitrary amounts to another vector of N coins with different amounts, where **M may not equal N**.
This PR adds a `Transformer` which takes such inputs and produces coins which satisfy the requirement.
Hence we can transform coins of [1,2,3,4] to [3,3,1,3] if needed.
This satisfies various use cases for example:
1. Pay multiple recipients with multiple coins. See [example](https://github.com/MystenLabs/sui/pull/4452)
https://github.com/MystenLabs/sui/issues/4198
We will simply need to transform some coins into the amounts needed, then transfer them
2. Pay for multiple TXes with multiple coins
We will transform the gas coins and then use them as needed
3. Coin management: we will be able to convert an arbitrary number of coins to another.

* why do we use a priority queue?
-> to minimize dust creation. For example requesting [3, 4] from coins [8, 1] would naively yield [3, 4, 1, 1] because 8 is split first into [3, 5] and then [4, 1]. With the pq based approach we get [3, 4, 2] because we use the 1 first, then take 2 from 8, leaving 6 then 4 from 6 leaving 2.
-> To preserve input object IDs as much as possible
* can we get rid of priority queue?
yes but dust might be created

Features added:
### 1. Transformer
A feature which takes M coins and a vector of amounts, and produces a vector of coins which satisfy the amounts requested as much as possible, such that sum(output coins) = sum(input coins). Hence if total amount requested is too large (we have deficit), we will fulfill what we can. If on the other hand total amount requested is less than what we have in coins, we will fulfill all and potentially have surplus.

Transforms a vector of coins to another with the specified amounts if possible
We define `amount_to_fulfill` as total sum of values in `amounts`
We define `amount_available` as total sum of values in `coins`
This function also tries to avoid creating dust by merging smaller coins together where possible
We greedily try to fulfill `amount` in the order specified
Hence if amounts is [30, 50, 5], we will try to satisfy 30, then 50, then 5.
This implies that for example if we had `amount_available` as 40, we will fulfill amounts[0], and part of amounts[1], but never amounts[2]
Hence we will end up with [30, 10]. The last amount of 5 will not be reached.
Depending on the `amount_to_fulfill` and amount_available, we may end up with more or less coins returned
**Case 1: Deficit**
If `amount_to_fulfill` > `amount_available`, we will not be able to fulfil all
This means we will fulfil as many coins as possible but will not reach total_amount_requested.
Hence len(output) <= len(amounts)
**Case 2: Surplus**
If `amount_to_fulfill` < `amount_available`, we will be able to fulfil all, and will have surplus coins
Hence len(output) > len(amounts)
**Case 3: Exact**
If `amount_to_fulfill` == `amount_available`, we will be able to fulfil all, with no surplus coins
Hence len(output) == len(amounts)

### 2. Transform and Transfer Multiple
This builds on transformer and allows taking N coins, some amount vector, some recipients, and sending the amounts to the recipients as best as possible. 
We allow best effort case: If we cannot create enough for all recipients we stop (but not abort)  at whichever we can.
We allow all or nothing case: If we cannot create enough for all recipients abort.

### 3. Transform and Transfer Single
This builds on transformer and allows taking N coins, some amount vector, one recipient, and sending the amounts to the recipient as best as possible.

### 4. More Priority Queue Features
PR adds some features for priority queue and relaxes the `drop` requirement by letting callers decide what to do with leftover items.

Seeking feedback on:
* This algo tries to avoid creating dust by merging small coins it creates.
* We allow specifying zero value amounts and the algo will comply
* We process amounts in the order specified in the vector. This means index of the amount is used as the priority

Potential improvements for later:
* We use priority queue which is recursive in the current impl. We can do better with iterative soln if needed.
* Lots of vector operations moving data around. This could be expensive so we might want to add more native operations for things like borrowing a slice of a vec
* Multiple places we can improve gas usage

### CODE REVIEW

**Comment by oxade** [comment]
On second thought 
This is a bit bulky for coin module
Will move it into a coin_utils module

**Comment by tnowacki** [comment]
As discussed offline, I wonder if we really care about preserving object IDs for this API in the best case scenario. 
My argument is that it will always destroy/disrupt object IDs in the worst case scenario, so if I was using this API, I would just expect it to destroy my existing objects. The only way it wouldn't is if I knew exactly which objects would be remaining at the end. But I feel that if I knew that and predicted that, I just wouldn't have included those objects in the function in the first place. 

So I would propose just a simpler `merge_and_split` API with the same behavior as the diagram above, but without preserving object IDs. This lets the implementation become _much_ simpler. We can then probably remove some of the extra functions here, and put it all back into `coin`.

All that being said, I typically do not have good insight into what people in the wallet land want/need/expect. So it would be good to get some insight there.

**Comment by oxade** [comment]
> As discussed offline, I wonder if we really care about preserving object IDs for this API in the best case scenario. 
> 
> My argument is that it will always destroy/disrupt object IDs in the worst case scenario, so if I was using this API, I would just expect it to destroy my existing objects. The only way it wouldn't is if I knew exactly which objects would be remaining at the end. But I feel that if I knew that and predicted that, I just wouldn't have included those objects in the function in the first place. 
> 
> 
> 
> So I would propose just a simpler `merge_and_split` API with the same behavior as the diagram above, but without preserving object IDs. This lets the implementation become _much_ simpler. We can then probably remove some of the extra functions here, and put it all back into `coin`.
> 
> 
> 
> All that being said, I typically do not have good insight into what people in the wallet land want/need/expect. So it would be good to get some insight there. 
> 
> 

Thanks for the feedback @tnowacki 
I had put the PR back in draft as I'm rethinking the general logic and needs of customers so it's low prio right now.
For now please hang tight and I'll update and reopen this soon enough.

**Review by kchalkias — COMMENTED** [review]
Hey @oxade what's the status of this PR and how it's aligned w/ @sblackshear's proposal?

**Comment by oxade** [comment]
> Hey @oxade what's the status of this PR and how it's aligned w/ @sblackshear's proposal?

@kchalkias will close this for now and see how the Pay API evolves.

**Pull request closed without merging**
