### PR TITLE
docker: update sui-node-deterministic to use glibc with stagex 2024.11.0

### PR DESCRIPTION
**Pull request by RyanSquared**
## Description 

Change sui-node-deterministic to use glibc, requiring the latest stagex release.

## Test plan 

How did you test the new or updated feature?

---

## Release notes

Check each box that your changes affect. If none of the boxes relate to your changes, release notes aren't required.

For each box you select, include information after the relevant heading that describes the impact of your changes that a user might notice and any actions they must take to implement updates. 

- [ ] Protocol: 
- [ ] Nodes (Validators and Full nodes): 
- [ ] Indexer: 
- [ ] JSON-RPC: 
- [ ] GraphQL: 
- [ ] CLI: 
- [ ] Rust SDK:
- [ ] REST API:

### CODE REVIEW

**Comment by RyanSquared** [comment]
This is branched from a rather old version just so i had an unchanging base to work with, but should work fine with the latest sui.

The hash I got from building was: `sha256:52d8c24f29f3d07928c5f5cb343d97412acbd857e54a7e544bf16300489292fa`

**Comment by jnaulty** [comment]
Thanks for opening this PR @RyanSquared 

Will test this build out.

Then we can update it to more recent version that we can run through perf tests

Tagging: https://github.com/MystenLabs/sui/issues/13476  for additional context

**Comment by jnaulty** [comment]
Didn't get the image to match
```
admin@ip-172-31-1-90:~/sui$ docker inspect sui-node:latest
[
    {
        "Id": "sha256:36a4992a1359e9c2fbe204588303760427466a6574a0d2831f915eb3fa764fcd",
        "RepoTags": [
            "sui-node:latest"
        ],
        "RepoDigests": [
            "sui-node@sha256:36a4992a1359e9c2fbe204588303760427466a6574a0d2831f915eb3fa764fcd"
        ],
        "Parent": "",
        "Comment": "buildkit.dockerfile.v0",
        "Created": "1970-01-01T00:00:01Z",
        "DockerVersion": "27.0.2",
        "Author": "",
        "Config": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
            "Cmd": null,
            "Image": "",
            "Volumes": null,
            "WorkingDir": "/",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "build-date": "",
                "git-revision": "7ce86baf4d24"
            }
        },
        "Architecture": "amd64",
        "Os": "linux",
        "Size": 112238174,
        "GraphDriver": {
            "Data": null,
            "Name": "overlayfs"
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:0b45a0935592edc03acaa1852b7c0364a373c5b6923bafea487895750da63214",
                "sha256:6e453917040b87e402e159e1e051a8a31052454f1221528fec61c671ad050128"
            ]
        },
        "Metadata": {
            "LastTagTime": "2024-11-23T00:39:31.024061918Z"
        }
    }
]
```

**Comment by RyanSquared** [comment]
Mine was tainted because I built it on the wrong commit.

```
 => => exporting manifest sha256:36a4992a1359e9c2fbe204588303760427466a6574a0d2831f915eb3fa764fcd                                                                                         0.0s
```

**Review by jnaulty — APPROVED** [review]

**Pull request merged**
