### PR TITLE
[sui-framework] Remove ChildRef. Added TypedID.

### PR DESCRIPTION
**Pull request by tnowacki**
- New typed_id module
- Removed ChildRef, replaced usages with ID or TypedID
- Transfers of child objects are now controlled through the
  "private" transfer mechanism

### CODE REVIEW

**Comment by tnowacki** [comment]
Open questions:
- Should `ChildID` be defined in the `ID` module?
- Should `ChildID` just be called `ChildRef`?
- What should be the name of this function: `inner<T: key>(&ChildID<T>): &ID`?

**Comment by lxfind** [comment]
When would someone wants to use TypedID?

**Comment by tnowacki** [comment]
> When would someone wants to use TypedID?

It's a good question, as it is mostly useless. I think in many/most cases, people will just use `ID`, hence why I put it in a separate module.

But I think the `geniteam::Farm` example is greatly improved with `TypedID`
```
struct Farm has key {
    id: VersionedID,
    ...
    pet_monsters: TypedID<Collection<Monster>>,
    applied_farm_cosmetic_0:  Option<TypedID<FarmCosmetic>>,
    applied_farm_cosmetic_1:  Option<TypedID<FarmCosmetic>>,
}
```

To me, this example would be a lot less clear with just `ID`
```
struct Farm has key {
    id: VersionedID,
    ...
    pet_monsters: ID,
    applied_farm_cosmetic_0:  Option<ID>,
    applied_farm_cosmetic_1:  Option<ID>,
}
```
Additionally, it's a bit nice since the type checker will then make sure the right `ID` ends up in the right slight (at least up to fields of the same type)

**Comment by tnowacki** [comment]
Added docs

**Review by lxfind — APPROVED** [review]

**Comment by tnowacki** [comment]
I'm also aware that a lot of the tutorial docs are broken as a result of this PR. With other changes coming, I'll need to do a bigger cleanup after the dust settles.

**Pull request merged**
