### PR TITLE
wallet-ext: approve transaction wait for details before enable submitting

### PR DESCRIPTION
**Pull request by pchrysochoidis**
* show waring confirmation modal for a transaction that dry run failed before submitting
* update loading states for gas fee and tx details, show `Estimating...`/`Gathering data...` when loading
and `Estimation failed`/`Couldn't gather data` for errors
* update confirmation dialog buttons to show loading state until
onResponse method is complete

https://user-images.githubusercontent.com/10210143/230473415-4c94b3fc-b517-466a-9357-895b84d6e47b.mov

https://user-images.githubusercontent.com/10210143/230473424-5e231b1d-ee2f-4666-9d51-b1d38647128e.mov

closes APPS-720

### CODE REVIEW

**Comment by bwann52** [comment]
Don't capitalize Continue, and please check text to "You will still be charged a gas fee for this transaction."

**Comment by pchrysochoidis** [comment]
> Don't capitalize Continue, and please check text to "You will still be charged a gas fee for this transaction."

Continue changed to Approve (after discussing with @mystie711 ) should I change to `approve` (A -> a)?

The text is updated to match the one you mention here

**Review by Jibz-Mysten — APPROVED** [review]
LGTM

**Comment by mystie711** [comment]
Just noticing that the Reject/Approve buttons are not the right size compared to Figma @pchrysochoidis.

**Pull request merged**
