### PR TITLE
[explorer] use suix_getEpochMetrics to fetch home page data to speed up performance

### PR DESCRIPTION
**Pull request by williamrobertson13**
## Description 

We use `suix_getEpochs` to fetch metrics for the transaction block graph and epochs tab, but this API returns validator data for each epoch which ends up transmitting a lot of data (~6MB) to the client. This also results in the API taking ~5 seconds end-to-end.

@gegaowp made a new `suix_getEpochMetrics` that is similar to the above endpoint but leaves out the validator data, so we can use that instead + now the page is a lot snappier 😄 

Before:
https://suiexplorer.com/

After:
https://explorer-git-wrobertson-exploerspeed-mysten-labs.vercel.app/

## Test Plan 
- Manual testing (chart data matches prod, table loads and paginates correctly)

---
If your changes are not user-facing and not a breaking change, you can skip the following section. Otherwise, please indicate what changed, and then add to the Release Notes section as highlighted during the release process.

### Type of Change (Check all that apply)

- [ ] protocol change
- [ ] user-visible impact
- [ ] breaking change for a client SDKs
- [ ] breaking change for FNs (FN binary must upgrade)
- [ ] breaking change for validators or node operators (must upgrade binaries)
- [ ] breaking change for on-chain data layout
- [ ] necessitate either a data wipe or data migration

### CODE REVIEW

**Review by Jordan-Mysten — APPROVED** [review]

**Review by gegaowp — APPROVED** [review]
LGTM!

curious on the epoch page like https://suiexplorer.com/epoch/215 we will still use the old getEpochs endpoint right?

**Comment by williamrobertson13** [comment]
> https://suiexplorer.com/epoch/215

Good thought - yeah we still use `getEpochs` on that page, but we only fetch 1 epoch and we actually use the validator data so I don't see any need to re-work that

**Comment by williamrobertson13** [comment]
@gegaowp I was doing some testing before landing and noticed this RPC method isn't implemented for testnet. Any idea what's up with that?

image

**Comment by gegaowp** [comment]
@williamrobertson13 it's not indeed b/c I did not roll indexer v2 to testnet / devnet yet.

**Comment by williamrobertson13** [comment]
> @williamrobertson13 it's not indeed b/c I did not roll indexer v2 to testnet / devnet yet.

Ahhh gotchya (I should've read the announcement post better 😆). I'm going to hold off on landing this until that rolls out just because I don't feel like going back and supporting both versions & don't want to land this if it only works for mainnet

**Comment by williamrobertson13** [comment]
hey @gegaowp! now this RPC doesn't seem to exist on mainnet indexer (it does work for testnet though!) 🤔 

https://explorer-git-wrobertson-exploerspeed-mysten-labs.vercel.app/?network=mainnet
https://explorer-git-wrobertson-exploerspeed-mysten-labs.vercel.app/?network=testnet

**Pull request merged**
