### PR TITLE
revert to manual dbmap init

### PR DESCRIPTION
**Pull request by oxade**

### CODE REVIEW

**Review by gdanezis — APPROVED** [review]
Many thanks for the revert Ade! Sadly at the point we are in the project we do need control over raw resources. Down the line when things settle, we can make abstractions that express better what we settled on.

**Review by huitseeker — COMMENTED** [review]
Beware: we should be very careful about maintaining the invariant that the default way to open a DB comes with options that limit the memory usage, brought about in https://github.com/MystenLabs/mysten-infra/pull/109/.

TL;DR: we have project-wide default options, and devs should go out of their way to omit them.

**Comment by oxade** [comment]
Hey @gdanezis the reason I have not merged this yet is that it does not entirely solve the problem of allowing callers of `open` to specify the options per table. The impl above forces every caller to use the same configs, which is not ideal.

See [this PR](https://github.com/MystenLabs/mysten-infra/pull/116) for one way we could do it.
It basically gives you a way to specify the options for each table before opening.

This will also enable us solve the Sui-Narwhal db open issue you flagged [here](https://github.com/MystenLabs/narwhal/issues/671) which lets Sui specify the table options

Let me know if you want this new approach instead.

**Comment by huitseeker** [comment]
@oxade should we close this in favor of #4025 ?

**Comment by oxade** [comment]
> @oxade should we close this in favor of #4025 ?

Yes. Will close once other is merged

**Pull request closed without merging**
