### PR TITLE
[GraphQL/Snapshot] Write the current schema before snapshot test

### PR DESCRIPTION
**Pull request by amnn**
## Description

In the previous set-up, if the snapshot test failed, it would need to be run a second time, after calling `cargo insta review` to ensure `schema/current_progress_schema.graphql` was properly updated.

There was nothing prompting you to do this which meant that when you forgot, the changes to `current_progress_schema.graphql` ended up being applied in the following PR, not the current one.

This PR changes the behaviour so that writing out the current progress becomes the first operation in the test (before the assertion), meaning the test only needs to be run once, and then reviewed.

It also cleans up the test file to remove the redundant extra module wrapper (because the test is in the `tests` directory, it doesn't need its own `test` module).

## Test Plan

```
sui-graphql-rpc$  cargo nextest run -- test_schema_sdl_export
```

### CODE REVIEW

**Review by wlmyng — APPROVED** [review]
Fantastic, this was a pain point I wanted to address but never got around to

**Comment by wlmyng** [comment]
Although I guess you could argue that, if there were any undesired changes, it would be caught by the snapshot test first. But at lest from my experience, it was always a "yes please just update the snapshot" lol

**Comment by amnn** [comment]
Well if there are undesirable changes, it will still get caught by the snapshot test, and then the next time you run it to get all green, the current progress one would also be updated.

Originally, I had a version of this PR that merged the two processes by getting insta to put the snapshot in the schema directory but it's not quite what we want because there's no way for insta to set an extension other than `.snap` and it adds a header that will confuse GraphQL syntax highlighters, so that's how we ended up here!

**Comment by wlmyng** [comment]
> Well if there are undesirable changes, it will still get caught by the snapshot test, and then the next time you run it to get all green, the current progress one would also be updated.

Oh yes, that is true. Dope!

**Pull request merged**
