### PR TITLE
show git clone proress and git version check.

### PR DESCRIPTION
**Pull request by v1xingyue**
## Description 

When execute `sui move` build and other command, git will be needed installed.
And also show clone progress will be much better.

### CODE REVIEW

**Comment by stefan-mysten** [comment]
Similar to/duplicate of #18636. 
@tzakian I think one of these two changes could be nice to have. What do you think?

**Comment by v1xingyue** [comment]
Ya. That should be about same feature. The difference is that I change the git program command output to current stdout, while his code is waiting the git command end and get output to print. I think my changing is much better.

**Comment by v1xingyue** [comment]
Hi. This PR is too long time? Will you consider merge this?

**Comment by stefan-mysten** [comment]
Closing this one as #18636 was merged. Thanks @v1xingyue for this PR.

**Pull request closed without merging**
